AyuntamientoMadrid/consul

app/models/proposal.rb, spec/models/proposal_spec.rb
Maintains a proposal's responsible name when the author is erased.
=> maintains responsible name when user is erased

app/controllers/valuation/spending_proposals_controller.rb, db/schema.rb, spec/features/admin/spending_proposals_spec.rb, spec/features/emails_spec.rb
Disable sending email when spending proposal is marked as unfeasible
=> Disable emails

app/helpers/spending_proposals_helper.rb, app/models/spending_proposal.rb, app/views/admin/spending_proposals/index.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, spec/features/admin/spending_proposals_spec.rb
adds two more selects to admin' spending proposals index to limit results by geozone and district-wide
=> Limiting results in admin interface

app/controllers/spending_proposals_controller.rb, app/helpers/spending_proposals_helper.rb, app/models/ballot.rb, app/views/spending_proposals/show.html.erb, spec/factories.rb, spec/features/ballots_spec.rb, spec/models/ballot_spec.rb
Proposals with feasibility undecided (feasible == nil) are not listed in the index and can not be voted in ballots.
=> Feasibility undecided

app/views/ballots/_ballot.html.erb, app/views/shared/_social_media_meta_tags_participatory_budget.html.erb, app/views/spending_proposals/show.html.erb, app/views/spending_proposals/welcome.html.erb, config/locales/en.yml, config/locales/es.yml
Si hay seleccionada alguna propuesta de distrito, se muestran los botones de compartir en redes sociales con un texto que incluye la cantidad y en qué distrito se está votando.
En principio está bien de apariencia, pero por si acaso @decabeza echa un ojo a ver si quieres moverlo de sitio/retocar estilos antes de dar tu visto bueno.
=> Social share ballot

app/models/abilities/administrator.rb, app/models/abilities/valuator.rb, spec/features/admin/spending_proposals_spec.rb, spec/features/spending_proposals_spec.rb, spec/features/users_spec.rb, spec/models/abilities/administrator_spec.rb, spec/models/abilities/valuator_spec.rb
- Admins cannot update nor destroy spending proposals after valuation has finished
- Removes duplicate permissions between admins and valuators
=> updates spending proposal permissions

app/controllers/admin/stats_controller.rb, app/views/admin/stats/redeemable_codes.html.erb, app/views/admin/stats/show.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, config/routes.rb, spec/features/admin/stats_spec.rb
Añade una página con estadísticas sobre códigos de verificación por carta:
- Número total de códigos utilizados por usuarios
- Número de códigos utilizados desde la campaña de las 400.000 cartas
=> Estadísticas de verificación por código en cartas

app/controllers/users/sessions_controller.rb, spec/features/sessions_spec.rb
Temporary to redirect users to participatory budgets
=> Do not store refer after sign out

app/controllers/admin/newsletters_controller.rb, config/environments/preproduction.rb
- Consistent preproduction and production x-sendfile configuration
- Uses send_data instead of send_file to send newsletter file
=> Fixes newsletter zip download

app/helpers/users_helper.rb, app/models/comment.rb, app/views/comments/show.html.erb, app/views/moderation/comments/index.html.erb, spec/features/moderation/comments_spec.rb
- Moderators can see flagged probe option comments (fixes exception 758)
- Refactors commentable methods
- Adds commentable specs for moderators
=> Flagged probe option comments

lib/tasks/polls.rake
Adds the following rake tasks:
* `polls:danger:destroy_all` (since questions have the paranoia gem it is not as simple as one would have imagined to remove all polls)
* `polls:generate_2017_nvotes_tsv` to generate the tsv for nvotes
* `polls:add_2017_nvotes_poll_id` to set the correct tsv poll id on each generated poll
It also modifies the descriptions of the generated polls for Barajas & San Blas, standardizing the way the options are shown. And it removes all mentions of "Ford".
=> improves poll.rake

app/models/poll.rb
Temp fix. Once rotation is over both fields should be migrated from datetime to date type.
=> uses starts_at/ends_at as dates instead of times

app/models/budget/investment.rb, spec/models/budget/investment_spec.rb
allows voting only in headings where you have already voted
=> Reclasification

config/initializers/acts_as_taggable_on.rb, spec/features/api/csv_exporter_spec.rb
Problem is that we have some duplicated tags in production with
uppercase and lowercase (e.g. "Medios" and "medios"). The gem expects
them to be all lowercase. And as such, some methods of the gem fail
(`Proposal.tagged_with('Medios')` returns 0 results). So I have
implemented my own thing using activerecord relationships.
Reference issue in acts_as_taggable_on:
https://github.com/mbleigh/acts-as-taggable-on/issues/661
=> circumvents acts_as_taggable_on problem with uppercased tags

app/models/concerns/verification.rb, app/views/admin/hidden_users/show.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, spec/features/admin/users_spec.rb, spec/features/legislation/processes_spec.rb
- We were missing a method (user_type) only available in Consul due to refactoring in Madrid
- Some misplaced translations (hidden_users vs users)
- Add a spec that is not aplicable to Madrid (display no archived processes)
=> Fixs specs and translations

config/environments/production.rb
What
====
Changes log level in production from debug to warning
Why
===
We are using 10G of hard drive space per day
Warning
===
Doing this in Madrid to avoid conflicts with an open PR in Consul consul/consul#1664
=> Reduce the amount of logs in production

app/assets/stylesheets/custom.scss, app/assets/stylesheets/custom/_once_plazas.scss, app/views/pages/processes/once_plazas/index.html.erb, app/views/polls/results_2017.html.erb, app/views/welcome/_budgets_module_extra.html.erb, app/views/welcome/_features.html.erb, app/views/welcome/_polls_reports.html.erb, app/views/welcome/index.html.erb
Para que sea más fácil navegar (sobre todo en la versión móvil) se han añadido enlaces a las imágenes `<figure>` y títulos `<figcaption>` de las páginas _welcome_, _landing_ del proceso "Once Plazas" y en la página de `resultados de la votación`.
=> Adds links to figure and figcaptions

app/views/pages/more_info/kit_decide/index.html.erb
- Añade un `id` en el menú de la página "Kit decide" necesario para que funcione el `sticky`
=> Kit decide

app/controllers/budgets/results_controller.rb, app/models/abilities/administrator.rb, spec/features/budgets/results_spec.rb, spec/models/abilities/administrator_spec.rb, spec/models/abilities/common_spec.rb, spec/models/abilities/everyone_spec.rb
What
====
- Allows admins to see budget results in the _reviewing_ballots_ phase
- Allows all users to see budget results in the _finished_ phase 
- Loads the results for the first heading if no heading is specified
- Removes duplicate permission in _abilities/everyone.rb_
How
===
- Using _cancan_ permissions
Test
====
- Log in as an admin and visit the results page of a budget
- Without being logged in visit the results page of a budget
Deployment
==========
- As usual
Warnings
========
- You might have to set manually the budget phases to test manually
=> Allow admins to see budget results

config/schedule.rb, lib/api/csv_exporter.rb, spec/support/common_actions.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/transparencia/issues/134
What
====
The csv files that are exported everynight live on each server, and since we have a ton of pdf/documents on the git repo and server capacity is limited... some nights we run out of spaces and files are not generated... breaking the daily release of data.
We need to use the new shared server that lives linked at `/public/system` so we:
- Don't run out of space
- Don't hold same files on 3 servers (just on one)
How
===
- Changing de destination folder for csv files on csv export rake task
- Changing the rake task scheduler role to "cron", since only one out of the 3 production servers (and one out of 2 preproduction) have that role, so only one will try to write on the shared …
=> CSV export to shared server

app/controllers/budgets/results_controller.rb, app/views/budgets/results/show.html.erb, app/views/budgets/show.html.erb, app/views/budgets/stats/show.html.erb, config/locales/en/budgets.yml, config/locales/es/budgets.yml, config/routes.rb, spec/features/budgets/results_spec.rb
Where
=====
* **Related Issue:**
- https://github.com/AyuntamientoMadrid/consul/issues/844 (points 1 & 2)
- https://github.com/consul/consul/issues/1737 (point 1)
What
====
1- Custom translated route for results `resultados`
2- Link between Stats and Results pages with custom routes `resultados` and `estadisticas`
3- Make Results current heading active
4- Order Results headings by id (make "All city" be the first heading on results page)
How
===
- Adding a new named custom route for results
- Adding missing tab links on both stats and results pages (making sure the Results tab on Stats page only shows when Budget is on Finished status) for everything else the Abilities take care
- Check the current heading from the params (using slugs, instead of id's as consul still behind on that)
- …
=> Budget results improvements

app/assets/stylesheets/custom.scss, app/assets/stylesheets/layout.scss, app/views/budgets/results/_results_table.html.erb, app/views/budgets/results/show.html.erb, app/views/budgets/show.html.erb, app/views/budgets/stats/show.html.erb, app/views/pages/more_info/budgets/_welcome_header_finished.html.erb, app/views/pages/more_info/budgets/welcome.html.erb, app/views/welcome/_budgets_module_finished.html.erb, app/views/welcome/_budgets_module_reviewing.html.erb, app/views/welcome/index.html.erb, config/locales/custom/en/custom.yml, config/locales/custom/es/custom.yml, config/locales/en/budgets.yml, config/locales/es/budgets.yml, config/routes.rb, spec/features/admin/budget_investments_spec.rb, spec/features/budgets/results_spec.rb
What
====
- Adds custom budget heading result's path 
`/presupuestos-participativos-2017/resultados/arganzuela`
- Marks first heading as selected when going to 
`/presupuestos-participativos-2017/resultados`
How
===
- Adding a custom route for heading results
- Using an instance variable instead of params to know what is the current heading
Screenshots
===========
- Custom heading route
- Mark first heading as selected
=> Budget results urls

app/views/pages/more_info/_other.html.erb
Elimina el enlace duplicado "Utiliza Decide Madrid en tu municipio" en la sección de "Otra información de interés" en la página de "/mas-informacion".
Este enlace además llevaba a la sección de "faq" (ya enlazada en el sidebar de esa misma página)
=> Enlace duplicado en más información

app/views/budgets/recommendations/index.html.erb
*   **Related Rollbar Issue:** https://rollbar.com/voodoorai2000/Participacion/items/1211/
*   When there is no current budget, code fails with a 500 internal server error.
*   Simple fix, sending budgets url instead of budget url for now. Needs some thinking and create an issue to describe a possible "current budget" feature.
No need
Don't think og metatags deserve a feature test.
*   Remember to close the rollbar issue afterwards
None
=> Temp fix for budget recommendation metatags

app/views/legislation/processes/index.html.erb
Qué
====
Mejorar el SEO haciendo que el enlace canonical de la página principal de procesos apunte a sí misma.
Cómo
===
Cambiado:
`<link rel="canonical" href="https://decide.madrid.es/legislation/processes">`
a:
`<link rel="canonical" href="https://decide.madrid.es/procesos">`
=> Canonical href en procesos

app/views/budgets/stats/show.html.erb
Qué
====
Borra una tag `</thead>` duplicada en la página de estadísticas de presupuestos participativos.
=> Duplicated </thead>

app/views/welcome/_cards.html.erb, app/views/welcome/index.html.erb, config/locales/custom/en/custom.yml, config/locales/custom/es/custom.yml
Qué
====
Añade el atributo `alt` que faltaba en algunas imágenes de la _homepage_.
=> Homepage alt images

app/views/custom/probe_options/_comments.html.erb
Qué
====
El atributo `name` está obsoleto. Esta PR elimina un enlace vacío con dicho atributo. El funcionamiento de los comentarios sigue siendo el correcto.
=> Probe show comments

README.md, README_ES.md
What
====
- People keep forking this repo instead of consul repo
How
===
- Add big alert on readme. In my opinion README should just state something like "This is a fork of CONSUL and here some badges and contributors and stuff.."
=> Readme alert about fork

app/views/budgets/investments/_investment_show.html.erb, app/views/proposals/show.html.erb, db/dev_seeds.rb, db/seeds.rb, spec/shared/features/documentable.rb, spec/shared/features/nested_documentable.rb
What
====
For now we have to prevent users from uploading documents to proposals and investments (only on creation will be possible to attach a document)
How
===
- Creating a new `Setting['feature.document_on_show']` with a default `false` value to easy enable/disable the feature both on views and specs
- Adding  `Setting['feature.document_on_show'] &&` to the if conditions that check if the link should be rendered... Maybe bit obscure but its short and effective compared to commenting out blocks
- Setting a `true` value on the before blocks of the documentable specs, and resetting it to `false` on the after block.
Screenshots
===========
Test
====
Probably will fail, but we don't care :D
Deployment
==========
To pre to check and merge to stable before deploying it to pro.  I wonder if …
=> Hide Document upload on Proposal/Investment

app/assets/javascripts/application.js, app/assets/javascripts/flaggable.js.coffee, app/assets/stylesheets/datepicker_overrides.scss, app/controllers/admin/poll/base_controller.rb, app/controllers/admin/poll/booth_assignments_controller.rb, app/controllers/admin/poll/booths_controller.rb, app/controllers/admin/poll/officer_assignments_controller.rb, app/controllers/admin/poll/officers_controller.rb, app/controllers/admin/poll/polls_controller.rb, app/controllers/admin/poll/questions_controller.rb, app/controllers/admin/poll/recounts_controller.rb, app/controllers/admin/poll/results_controller.rb, app/controllers/admin/poll/shifts_controller.rb, app/controllers/documents_controller.rb, app/helpers/admin_helper.rb, app/models/poll/question.rb, app/views/admin/_menu.html.erb, app/views/comments/_comment.html.erb, app/views/proposals/_flag_actions.html.erb, app/views/proposals/_refresh_flag_actions.js.erb, app/views/proposals/show.html.erb, db/dev_seeds.rb, spec/features/admin/poll/polls_spec.rb, spec/features/proposals_spec.rb, spec/models/poll/question_spec.rb, spec/shared/features/documentable.rb
Where
=====
**Related PR's:**
- Documentable Fix https://github.com/consul/consul/pull/1849
- Fix No route matches [GET] "/admin/poll"  https://github.com/consul/consul/pull/1863
- Fix datepicker arrows https://github.com/consul/consul/pull/1869
- Switch flag/unflag buttons https://github.com/consul/consul/pull/1883
- Fix and improve dev_seeds https://github.com/consul/consul/pull/1889 & https://github.com/consul/consul/pull/1878
- Fix comment reply link https://github.com/consul/consul/pull/1890
- Fix admin menu active items issues https://github.com/consul/consul/pull/1874
What
====
- Pulling latest changes from Consul on to Madrid's fork
How
===
- Merging conflicts manually
Screenshots
===========
- No need
Test
====
- There should be less flaky tests, lets hope Travis is nice this …
=> Consul pull ⬇️

app/views/layouts/_officing_booth.html.erb, app/views/layouts/admin.html.erb
What
====
~Removed alert appearing in admin section when an admin user **also poll officer** is in this section, as requested.~
Made alert for poll officers just appear in the Officing section (http://localhost:3000/officing) instead all over admin section.
Test
====
As usual.
Deployment
==========
As usual.
=> Removed officer alert in admin section

app/controllers/officing/residence_controller.rb, app/views/officing/results/new.html.erb, config/locales/en/officing.yml, config/locales/es/officing.yml
What
====
- Removed callback to avoid redirection in `Officing::ResidenceController#new`.
- Removed not necessary translations.
Test
====
As usual.
Deployment
==========
As usual.
=> Officing requested changes

app/views/polls/show.html.erb, config/locales/en/general.yml, config/locales/es/general.yml
Qué
===
- Añade un pequeño link a "Ver proyectos" en `polls/show` que hace scroll a la parte de la descripción de las respuestas para que el usuario no se pierda esa información.
Imágenes
===
=> Link a ver proyectos

app/views/pages/more_info/polls/february_2017.html.erb, app/views/pages/more_info/polls/index.html.erb, app/views/pages/more_info/polls/october_2017.html.erb, app/views/polls/index.html.erb, app/views/polls/info_2017.html.erb, config/routes.rb
Qué
====
- Arregla las rutas de las páginas de más información de votaciones:
`mas-informacion/votaciones`: información genérica (linkada desde más información).
`mas-informacion/votaciones/febrero-2017`:  información sobre la pasada votación.
`mas-informacion/votaciones/octubre-2017`: información sobre la votación en curso.
=> fixes more info polls pages routes

app/views/polls/questions/answer.js.erb
What
====
- Adds a event for Google Tag Manager (GTM) after voting a poll
How
===
- Adding the corresponding call to GMT in the rendered js partial
Test
====
- Make sure build passes
- Manually verified the call is sent using Google Chrome Inspector (Network tab)
- Marketing has approved the implemetation in the Preproduction environment
- Should manually verify event is being registered in GTM
Deployment
==========
- As usual
Warnings
========
- No tests... :( This is a fire situation, we have launch this campaign ASAP. 
Look into writting specific tests for this or next campaign.
As long as the build passes I think it's ok not to write tests for this one, now.
=> Google Tag Manager Event

lib/tasks/polls.rake
Where
=====
* **Related Issue:** https://github.com/consul/consul/issues/2072
* **Related PR's:** 
- https://github.com/consul/consul/pull/2073
- https://github.com/consul/consul/pull/2074
What
====
PR https://github.com/consul/consul/pull/2074 will remove `valid_answers` attribute for all Poll::Question, we need to migrate existing values for old Polls to new usage `Poll::Question::Answer`
How
===
Loop through existing Poll::Question without associated `Poll::Question::Answer` and create one for each `valid_answers` value.
Screenshots
===========
No need
Test
====
No need
Deployment
==========
Before  https://github.com/consul/consul/pull/2074  is merged! running `bin/rake polls:migrate_poll_question_valid_answers RAILS_ENV=ENV`
Warnings
========
None
=> Create Poll Question Answers for still existing valid_answers

app/views/admin/shared/_admin_shortcuts.html.erb, app/views/officing/dashboard/index.html.erb, app/views/shared/_admin_login_items.html.erb, config/locales/en/officing.yml, config/locales/es/officing.yml
Qué
=====
- Muestra el menú `Presidente de mesa` en vez de `Admin` a los _officers_.
- Muestra el dropdown en tamaño móvil (estaba oculto) 😬 
- Muestra los links de `settings` y `stats` solo a admins.
- Oculta el mensaje de "Hoy no tienes turnos" (los menús del sidebar no dejan entrar si no hay turnos)
=> Officer menu

app/views/legislation/processes/proposals.html.erb
Qué
====
- Muestra el partial `custom_documents` en la fase de propuestas de un proceso.
=> Legislation proposals documents

app/views/legislation/proposals/show.html.erb
What
====
- Does not allow voting in the show view of an Open Plenary proposal
Why
=====
To avoid pressure groups from sharing their proposals in social networks and skewing the process.
By allowing citizens to vote only the index view, hopefully the process will be more transparent and equitable
How
===
- Hardcoding the Open Plenary id 😱 
Warnings
========
- Left a comment in the code explaining this hotfix. Remove once the Open Plenary is over and implement a more robust solution, maybe using a boolean for this special Processes.
=> Does not allow Open Plenary votes in the show view

app/assets/stylesheets/custom/_welcome.scss, app/views/polls/_results_2018.html.erb
Qué
====
- Mueve el **título de pregunta** `<h4>` fuera de  `<table>` en la página de resultados de la votación once plazas para evitar un error de validación HTML.
- Cambia el color de fondo de la etiqueta "Fin de la votación" en la _welcome_ page para aumentar el contraste de colores (_accesibilidad_)
=> Validación HTML

app/assets/stylesheets/layout.scss, app/assets/stylesheets/participation.scss, app/controllers/admin/legislation/processes_controller.rb, app/helpers/documentables_helper.rb, app/helpers/documents_helper.rb, app/models/document.rb, app/models/legislation/process.rb, app/views/admin/legislation/processes/_form.html.erb, app/views/documents/_additional_document.html.erb, app/views/documents/_additional_documents.html.erb, app/views/documents/_documents.html.erb, app/views/legislation/draft_versions/changes.html.erb, app/views/legislation/draft_versions/show.html.erb, app/views/legislation/processes/debate.html.erb, app/views/legislation/processes/phase_empty.html.erb, app/views/legislation/processes/phase_not_open.html.erb, spec/features/legislation/processes_spec.rb
Where
=====
* **Related PR's:** https://github.com/consul/consul/pull/2084
What
====
- Adds functionality to upload documents for legislations from admin
Screenshots
===========
- In PR https://github.com/consul/consul/pull/2084
Test
====
- Manually tested in Pre
https://decidepre.madrid.es/legislation/processes/22/draft_versions/6
Deployment
==========
- As usual
Warnings
========
- There is a conflict between custom documents and standard documents that should be dealt with after November 20th https://github.com/AyuntamientoMadrid/consul/issues/1013
=> Legislation documents

lib/tasks/budgets.rake
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/consul/issues/1012
What
====
We where asked to get the list of emails for winner/selected/proposed investments on last Budget
How
===
Just adding 3 rake tasks, this could be done at Consul in a much better way, but I would do it after we finally get Notifications to be global to send the emails from the admin panel, or at least a view at the admin panel to get the 3 email lists.
Screenshots
===========
No need
Test
====
No need, manually tested rakes on local machine
```
bin/rake budgets:email:winner_investments_emails
bin/rake budgets:email:selected_investments_emails
bin/rake budgets:email:proposed_non_selected_investments_emails
```
Deployment
==========
As soon as possible to pre and pro to return an Excell to …
=> Rake tasks to print author emails for winner/selected/proposed

lib/tasks/budgets.rake
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/consul/issues/1011
What
====
Get into a excel file the BudgetPoll responses we added at https://github.com/AyuntamientoMadrid/consul/issues/993
How
===
Just a rake task that as usual composes a string in the console like:
`nombre^email^tema^colectivo^funcionario^autor^seleccionado*****marlo^brando@carlo.com^Fase de informes^Si^No^No^Si*****juan^cho@juan.com^ns/nc^Si^No^No^No*****`
We'll need to execute `bin/rake budgets:budget_polls_results RAILS_ENV=environment` obviously replacing **environment** for the correct them, then:
1. Copy and paste the full text into our editor
2. Replace `*****` for a new line on our editor
3. Save the file as a `.csv` one
4. Open it with openoffice (check that the caret character `^` is …
=> BudgetPoll responses output via rake task

app/views/pages/more_info/budgets/welcome.html.erb
Where
=====
Budget's welcome page https://decide.madrid.es/presupuestos
What
====
- Updates investment links
Why
===
These links are currently raising a 404 error
- Ver lista completa de propuestas 
- Ver lista de propuestas inviables 
- Ver lista de propuestas no seleccionadas para la votación final
How
===
- Using custom routes and parameters
Test
====
- Branch deployed and manually tested in staging environment
https://decidepre.madrid.es/presupuestos
Deployment
==========
- As usual
Warnings
========
- None
=> Fixes links to investments from budget's welcome page

app/views/proposals/_custom_documents.html.erb, app/views/proposals/show.html.erb
Qué
====
- Para algunas propuestas se necesita añadir un documento de **Informe de competencia**.
Cómo
===
- Añade el _partial_ `custom_documents` en la vista _show_ de las propuestas.
- Los documentos PDF ya están subidos al servidor.
Deploy
==========
- Una vez subido a PRO deberíamos borrar:
- El campo `external_url` de las propuestas `9, 105, 199 y 417`
- La carpeta `public/docs/informe_competencia` de este repositorio.
=> Proposals custom documents

lib/migrate_spending_proposals_to_investments.rb, lib/tasks/spending_proposals.rake, spec/lib/migrate_spending_proposals_to_investments_spec.rb
Just migrating stuff partially to get milestones working, we'll do it right at consul and completly here later on
Tested in pre! Use `bin/rake spending_proposals:migrate_to_budgets RAILS_ENV=production` when at pro
=> Spendign Proposals migrator to Budget Investment

app/controllers/budgets/investments_controller.rb, config/routes.rb, lib/migrate_spending_proposals_to_investments.rb, spec/features/admin/budget_investments_spec.rb, spec/features/ballots_spec.rb, spec/features/comments/spending_proposals_spec.rb, spec/features/official_positions_spec.rb, spec/features/spending_proposals_spec.rb, spec/features/votes_spec.rb, spec/lib/migrate_spending_proposals_to_investments_spec.rb
What
====
Spending Proposal urls are all around the internet, and as well at decide.madrid.es with multiple references. We need to keep those urls alive even if we move towards Budget Investments, but keeping in mind all Spending Proposals code will sooner or later disappear to cleanup the codebase.
How
===
Redirecting the #show action for a spending proposal custom url path (translated to spanish) to Budget investment's controller with a special action that avoids trying to load budget/investment resources (and authorization).
We then use the `unfeasibility_explanation` column of Budget Investments table to find which one corresponds with the requested Spending Proposal id and redirect to the same controller show action as usual.
As a Bonus we're removing the votes migration from …
=> Spending Proposal url redirect to Budget Investments

app/controllers/budgets/investments_controller.rb, app/views/budgets/investments/_investment_show.html.erb, db/migrate/20171219110528_add_spending_id_to_budget_invesment.rb, db/schema.rb, lib/migrate_spending_proposals_to_investments.rb, spec/features/admin/budget_investments_spec.rb, spec/lib/migrate_spending_proposals_to_investments_spec.rb
What
====
Using `original_spending_proposal_id` instead of `unfeasibility_explanation` (actually used for some proposals) to avoid messing data so much, and having a clear way to find correspondent investment given a spending id request
Also we actually need to show the original Spending ID instead of the Budget Investment ID in case the investment has been migrated from a spending proposal 
How
===
Migration, update specs and show original id if present instead of current id
Screenshots
===========
From Pre environment
Test
====
Updated and tested manually in pre
Deployment
==========
We'll need to run through console at pro:
```
Budget.where(name: '2016').first.investments.each { |i| i.update_column(:original_spending_proposal_id, i.unfeasibility_explanation) }
Budget.where(name: …
```
=> Show original Spending Proposal ID for migrated to Investment object

app/controllers/budgets/investments_controller.rb, spec/features/admin/budget_investments_spec.rb, spec/features/budgets/investments_spec.rb
What
====
We need to keep old spending proposals url's working exactly the same, even though "underneath" those will be handled by the budget investment controller and they will load the associated budget investment.
There's a catch since there could be a SpendingProposal with ID 9999  (with an associated Investment with ID 8888)... but another Budget Investment from a different Budget with the same ID 9999... and both urls need to be valid (the only difference will be the budget_id or budget_slug.
How
===
Explicitly loading the investment, first trying to figure out if there is a Budget Investment with a reference to an old Spending Proposal for the given `params['id']` value, if not just looking for the investment with that id.
Screenshots
===========
No need
Test
====
Moved to correct …
=> Investment budget spending urls

app/controllers/admin/budget_investments_controller.rb, app/views/admin/budget_investments/_investments.html.erb, spec/features/admin/budget_investments_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/consul/issues/1082
What
====
We need to both list and link budget investments generated from a migrated spending proposal with the spending proposal id
How
===
Similar to the fix done on the frontend for final user, finding first if a investment with a `original_spending_proposal_id` value exists, and falling back to a normal `.find`.
Screenshots
===========
No need.
Test
====
Added scenario to check correct listing, url link and access by original spending id and investment id
Deployment
==========
As usual
Warnings
========
None
=> Migrated Spending proposals on Admin panel

app/views/pages/more_info/budgets/_welcome_header_balloting.html.erb
What
====
- Updates budget links from welcome page
- Makes them dynamic, using the last budget
Deployment
==========
- As usual
Warnings
========
- Make sure it links correctly in Production
- Hard to test in staging environment as we have the dev seeds loaded
=> Update budget links from welcome page

CHANGELOG.md, app/controllers/admin/budgets_controller.rb, app/helpers/budgets_helper.rb, app/models/budget.rb, app/models/budget/phase.rb, app/views/admin/budgets/_form.html.erb, app/views/budgets/results/show.html.erb, app/views/budgets/stats/show.html.erb, config/locales/custom/en/budgets.yml, config/locales/custom/es/budgets.yml, config/locales/en/budgets.yml, config/locales/es/budgets.yml, db/dev_seeds.rb, db/migrate/20180112123641_create_budget_phases.rb, db/schema.rb, lib/tasks/budgets.rake, spec/factories.rb, spec/features/admin/budget_investment_milestones_spec.rb, spec/features/admin/budgets_spec.rb, spec/features/admin/poll/shifts_spec.rb, spec/features/budgets/ballots_spec.rb, spec/features/budgets/investments_spec.rb, spec/features/budgets/results_spec.rb, spec/features/officing/residence_spec.rb, spec/features/officing/results_spec.rb, spec/features/tags/budget_investments_spec.rb, spec/features/valuation/budgets_spec.rb, spec/models/budget/investment_spec.rb, spec/models/budget/phase_spec.rb, spec/models/budget_spec.rb
Create Budget::Phases backend consul/2323
⚠️ You must run `bin/rake budgets:phases:generate_missing RAILS_ENV=preproduction` task to generate Budget::Phase's for all existing Budgets and migrate values from description_* columns from budget's table to new budget_phase's description columns. This is a DEPRECATION warning... in release v0.14 those columns will be erased from database and all non-migrated data will be lost!
=> Create Budget::Phases backend

app/views/budgets/recommendations/index.html.erb, app/views/pages/landings/blas_bonilla.html.erb, app/views/pages/landings/budgets_materials_2017.html.erb, app/views/pages/landings/budgets_videos_2017.html.erb, app/views/pages/landings/first_voting.html.erb, app/views/pages/landings/geocraft.html.erb, app/views/pages/landings/plazas_abiertas.html.erb, app/views/pages/processes/once_plazas/index.html.erb, app/views/polls/info_2017.html.erb, app/views/polls/results_2017.html.erb, app/views/polls/stats_2017.html.erb, app/views/shared/_social_media_meta_tags_participatory_budget.html.erb, app/views/shared/_social_media_meta_tags_plaza_espana.html.erb
What
====
This PR removes unnecesary `/` on `og:image` and `twitter:image` meta tags.
This tags sin some pages:
```html
<meta property="og:image"  content="<%= image_url '/social_media_polls_results.png' %>" />`
<meta name="twitter:image" content="<%= image_url '/social_media_polls_results_twitter.png' %>" />`
```
Was generating a broken links:
```html
<meta property="og:image"  .../images/%2Fsocial_media_polls_results.png" />
```
```html
<meta name="twitter:image" .../images/%2Fsocial_media_polls_results_twitter.png" />
```
This PR fix that!
=> Fix social images meta tags

app/views/budgets/index.html.erb
What
====
- Fix link to 2016's Budget Results
Test
====
- This is a hotfix, tests coming soon!
Deployment
==========
- As usual
Warnings
========
- None
=> Hotfix to display correct link to 2016 Budget Results

app/models/budget/group.rb, app/models/budget/heading.rb, app/views/budgets/investments/_banners.html.erb, app/views/budgets/show.html.erb, spec/features/budgets/investments_spec.rb, spec/features/tags/budget_investments_spec.rb
What
====
"Toda la ciudad: Toda la ciudad" should be first option at heading selection on Investment form
How
===
Just order Budget Groups by name but descending, so always "Toda la ciudad" will be above "Distritos", and that will make the heading "Toda la ciudad" always be on top of any other heading.
As a bonus we're removing the Budget::Group name from the option text when it only has one heading.
Screenshots
===========
Test
====
Increased investment feature spec adding an scenario for this particular change on madrid's codebase and avoid mixing it with other scenarios that should be equal to consul's ones.
Deployment
==========
As usual
Warnings
========
None
=> Invert budget groups order at investment form

app/models/budget/phase.rb
What
====
Budget's phases changes are not reflected at /budget page a the cache keys only take into account the budget itself. We need to "touch" the budget object after updating any of its phases so caches will be cleared as expected.
How
===
Just an after_save callback that calls touch over budget.
BONUS: Making next_enabled_phase? method private, as it should be
Screenshots
===========
No need
Test
====
No need? Hard to tests cache related stuff on tests environment... will do so on preproduction server
Deployment
==========
As usual
Warnings
========
This is a candidate to be backported to consul
=> Touch budget after phase update

app/controllers/budgets/groups_controller.rb, spec/features/budgets/budgets_spec.rb
What
===
- Scope heading search by budget
Why
===
As we are searching for headings by slug and there can be multiple headings with the same slug for different budgets, we were displaying headings from a past budget
Test
====
- Make sure we see the current budget headings and not the previous budget headings [here](https://decidepre.madrid.es/presupuestos/presupuestos-cuquis-2018/distritos) ✅ 
Deployment
==========
- As usual
Warnings
========
- None
=> Scope heading search by budget

.travis.yml, spec/features/polls/voter_spec.rb, spec/lib/tasks/dev_seed_spec.rb
Included PR
=====
- Clean up Travis logs - https://github.com/consul/consul/pull/2357
What
====
- Remove asset precompilation output from travis logs
- Reduce travis' knapsack log level to info
- Fix RSpec's `should` deprecation warning
- Remove duplicate dev_seed execution
Deployment
==========
- As usual
Warnings
========
- None
=> [WIP] Clean up Travis logs

app/controllers/budgets_controller.rb, spec/features/budgets/budgets_spec.rb
Why
===
We still need to figure out how to nicely navigate between feasible, unfeasible and selected projects
Currently the budget’s show page displays a budget’s groups but in a very minimal way. The budget’s groups are also displayed in the budget’s index page in a much nicer way
What
===
Thus, we want users to navigate from the nicer budget’s index page if possible. The only case that it is not possible is if they want to filter by unfeasible or selected projects. Therefore, if the url has
filter params we display the budget’s show page, otherwise we redirect them to the budget’s index page
Screenshots
===========
- Budget's Index
- Budgets's show
Test
====
- Manually test in staging environment
Deployment
==========
- As usual
Warnings
========
- None
=> Redirect to budget's index when no filter params

app/controllers/communities_controller.rb, app/models/community.rb, spec/features/communities_spec.rb
What
====
Somehow we're seeing communities without proposals at production. We
must find why and fix it, but first we need to throw a 404 at the user
instead of a 500 internal server error
How
===
First catching the scenario of non-existent communitable at the
controller and raising a 404 error. Secondly preventing the author_id
access over a possibly nil object, this is a smell but it can't be
easily fixed right now... we need to correctly implement a relation
between Community and communitable and avoid the multiple occurences of
`community.from_proposal?` in the codebase that makes it impossible to
extend to a fourth communitable model.
Screenshots
===========
No need
Test
====
Increased to cover the bug, then covered the spec with code
Deployment
==========
Asap to PRO
Warnings …
=> Fix access to community without communitable

app/controllers/budgets_controller.rb, spec/features/budgets/budgets_spec.rb
Reverted PR
===
https://github.com/AyuntamientoMadrid/consul/pull/1144
Why
===
The reverted PR had broken many tests
It has many implications that need to be addressed calmly
We should think of a better way to navigate projects by filter (feasible, unfeasible and selected for final voting)
=> Revert redirect when no filter passed to a budget

app/views/custom/budgets/index.html.erb, spec/features/budgets/results_spec.rb
What
====
- Display links to finished budget results
Why
===
We were displaying links to all budgets, even if they were in a phase
other than finished
Test
====
- Add specs to display links to see results from budget's index
Deployment
==========
- As usual
Warnings
========
- Backport to Consul
=> Display links to finished budget results

app/views/budgets/index.html.erb, app/views/custom/budgets/index.html.erb
What
====
This PR:
- Orders budgets groups headings by name.
- Adds this new order to custom budget index.
- Removes unnecessary comments (we don't use budget/index page)
=> Budget heading order

app/views/custom/budgets/index.html.erb
What
====
This PR:
- Uncomments links on budget homepage to start to accepting investment projects 🎉 
Deployment
==========
⚠️ Once deployed don't forget to set `Setting['feature.guides'] = true` on production.
=> Budgets start

app/helpers/map_locations_helper.rb, spec/helpers/map_locations_helper_spec.rb
Included PR
===
- https://github.com/consul/consul/pull/2381
What
====
- Skips invalid map locations
Test
====
- Test manually in staging environment
Deployment
==========
- As usual
Warnings
========
- Some map locations might not be visible in the main map that displays all budget investment's locations
=> Fix map markers with asterisks

app/assets/javascripts/map.js.coffee, spec/features/budgets/budgets_spec.rb
Where
=====
* **Related Issue:** https://github.com/consul/consul/issues/2380
* **Related PR's:** https://github.com/consul/consul/pull/2381
Why
===
Sometimes the latitude or longitude it passed to the map as ********* instead of the actual latitude or longitud. The asterisks are not a string, breaking the whole array
What
===
This commits skips invalid markers and displays the rest
How
===
- Substituting the mysterious asterisks for null (cleanInvestmentCoordinates)
- Validating the coordinates are numbers before trying to paint them (validCoordinates)
- Adding a numeric function to validate the latitude and longitude (isNumeric)
Screenshots
===========
- Asterisks instead of numeric value
Test
====
- Added tests to simulate gracefully handling asterisks
Deployment
==========
- As usual …
=> Skip invalid map markers

app/views/admin/budget_phases/_form.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, config/locales/es/budgets.yml
What
====
This PR:
- Fixes textarea and label order on admin budgets phases form (it was upside down)
- Updates Spanish translations of budgets (`propuesta de inversión` to `proyecto de gasto`)
=> Fix i18n texts

app/views/admin/budget_investments/index.html.erb
Included PR
===
https://github.com/consul/consul/pull/2398
What
====
- Fix: Admin investments table not showing up properly
- Note: the original issue seems to have been solved already in merge conflict with Madrid
Deployment
==========
- As usual
Warnings
========
- None
=> Fix: Admin investments table not showing up properly

app/views/admin/budgets/_group.html.erb, app/views/admin/budgets/_heading.html.erb, spec/features/admin/budgets_spec.rb, spec/features/budgets/investments_spec.rb
Where
===
This is a PR coming from Consul consul#2370
What
====
I find hard to read currencies without format, as well as amounts without a right indentation. This table has both issues and I think fixing them makes UI better.
How
===
- Formatting heading price https://github.com/consul/consul/commit/1f85e4e65ef85a2a31ac9e345d1958253fce9312 in the same way we're doing it at the frontend https://github.com/consul/consul/blob/master/app/helpers/budgets_helper.rb#L6
Screenshots
===========
Test
====
- Updated Heading & Group management spec scenario accordingly https://github.com/consul/consul/commit/bd64c4749f8706d855ba38e781598523ea73afa8
- Boyscout-rubocop linelenght cleanup https://github.com/consul/consul/commit/2a500a14bc4bc9d776de73f200489b377bfd1030
Deployment
==========
As usual …
=> Improve budget heading style

config/secrets.yml.example, spec/features/polls/nvotes_spec.rb, spec/models/poll/nvote_spec.rb
Where
=====
* **Related Issue:** None
What
====
- As you can see in the image, the tests fails because the key attribute is null, There are two fields missing in secrets.yml, missing nvotes_shared_key and nvotes_server_url, Test enviroment gets secrets.yml from secrets.yml.example so I added the missing fields to secrets.yml.example
How
===
- Added more fields to secrets.yml.example
Screenshots
===========
Test
====
- Added one test to ensure the existence of the elements
Deployment
==========
- none
Warnings
========
- none
=> Add missing config to secrets example

spec/features/comments/budget_investments_spec.rb, spec/features/comments/debates_spec.rb, spec/features/comments/legislation_annotations_spec.rb, spec/features/comments/polls_spec.rb, spec/features/comments/topics_spec.rb
Where
=====
* **Related Issues:** #1173, #1174, #1177, #1192, #1201
What
====
* Mitigate the flaky specs that were affecting voting comments specs on certain commentable models
How
===
* The tests were failing under the `update` scenario with certain seeds (`44140` for `debates_spec`, `59824` for `investments_spec` and `19087` for `legislation_annotations_spec`)
* An `after` hook to logout was added under the `Voting comments` feature on all affected scenarios to ensure a clean state before each example
* `debates#update`, `budget_investments#update` and `legislation_annotations#update` scenarios were tested more than 30 times with the aforementioned seeds without failures. Several Travis builds have shown that the proposed changes have successfully mitigated all four (4) issues
Notes …
=> Fix for `voting comments` flaky specs

spec/features/api/csv_exporter_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/consul/issues/1181
What
====
- It repairs a flaky test on spec/features/api/csv_exporter_spec.rb 428 and 443 
How
===
- The images show the id's of the proposals when they are created and the content of the csv converted into string
As seen in the images when delegating the inclusion of the tags in the tag list and letting the test run in Travis, the action created by the taglist creates new proposals as well (as seen in the ids of the images) due to the operation of the variables created with let, the solution consists of not delegating and assigning the tags to their corresponding variable
Screenshots
===========
- List of object id's running the test locally
- List of object id's running the test on travis
Test
==== …
=> Solution for the flakies on spec/features/api/csv_exporter_spec.rb 428 and 443

spec/features/officing/residence_spec.rb
Where
=====
* **Related Issue:** #1211
What
====
- Hunt the flaky that appears in `/spec/features/officing/residence_spec.rb:70:`
- Specific error in test: 
```  5) Residence Assigned officers Error on verify
Failure/Error: click_button 'Validate document'
Capybara::ElementNotFound:
Unable to find visible button "Validate document"
```
How
===
- Explanation:
There are two buttons (one link and one button) with the same name. This only happen with the translation for the buttons match. For example in Spanish it is different translations.
- Flaky Explanation:
The fact it is a flaky test is because capybara calls them visually with `click_link` and `click_button` and both have the same name.
- Fix Explantion:
Include a `within` in each call to the button/link to specify exactly where the …
=> Flaky residence assigned officers error

spec/features/emails_spec.rb
Where
=====
* **Related Issue:** #1176
What
====
Hunt the flaky that appears in `spec/features/emails_spec.rb:509`.
How
===
In the error provided in the issue, there was a problem when creating a comment from the UI. My thoughts about this were focused in JavaScript, because the comments use it to be published, so, at first, I tried fixing that function.
But, as the guide sais:
> That means you've to think "What are we testing here?" and "Can we test the same thing in another way?" or "Are we already testing this somewhere else at least partially?".
So I changed my approach for this flaky. The test that fails is "Emails Users without email should not receive emails", so what we need is a test that doesn't send emails to users that don't have an email. Instead of using the comment_on …
=> Hunt the flaky - Emails Users without email should not receive emails

spec/features/comments/legislation_annotations_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/consul/issues/1180
What
====
- Fix a flaky error when comment isn't assigned to  the legislation proposal
How
===
- As you can see in the attached image, when a comment is NOT assigned it gives exactly the error sought. So the problem is that sometimes the comment is not assigned correctly (it has already happened in other flakies, delegate the assignment of variables to let is not 100% reliable), assigning the variables manually resolves the problem
Screenshots
===========
Test
====
- It's a fix
Deployment
==========
- none
Warnings
========
- none
=> Flaky error when comment isn't assigned to the legislation proposal

app/controllers/budgets/investments_controller.rb, spec/features/budgets/investments_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/consul/issues/1191
What
====
- It fix a flaky error, caused by a not-so-random seed
How
===
-When entering budget_investments_path the list of investments shown is generated randomly based on a random number chosen between -100 and 100 as seen in the 1st image (line 110). The problem is produced because it is relatively likely to repeat the number (each has a 0.5% chance of appearing). once fixed that random number the rest of the process is deterministic, as seen in the 2nd and 3rd images, setting the number the results are the same.
To prevent flaky error, it is enough to pass the value of random_seed by parameter, even so the probability that two people get the same list of investmens is 0.25% in production …
=> fix for the flaky error 1191, not random investments list

db/dev_seeds.rb, spec/lib/tasks/dev_seed_spec.rb
Where
=====
* **Related issue:** #1197 (This PR closes #1197 once merged)
What
====
* Added missing `require` statements needed for the spec to work properly
* Removed extra `end` that was causing the test to fail
* Mitigated scenario where the `rake db:dev_seed` task spec would fail if a randomly selected budget had no investments associated with it under the `Balloting Investments` seeding section
How
===
* The problem was that the budget selected randomly under the `Balloting Investments` section could not have investments associated with it, so when an investment of said budget was to be added to a ballot, the `Budget::Ballot::Line#check_selected` validation failed since the `selected?` method was not available to a `NilClass` element
* The proposed PR takes as inspiration the …
=> Fix `rake db:dev_seed` task flaky spec

app/assets/stylesheets/legislation.scss, app/assets/stylesheets/participation.scss, app/views/budgets/investments/_investment.html.erb, app/views/budgets/investments/_milestones.html.erb, app/views/legislation/processes/_process.html.erb, app/views/pages/custom_page.html.erb, spec/features/budgets/investments_spec.rb, spec/features/site_customization/custom_pages_spec.rb
What
====
This PR include the following design minor fixes (already merged on CONSUL https://github.com/consul/consul/pull/2465): 
- Fixes heading structure and i18n format on legislation processes: avoid jump from `<h3>` to `<h5>`, changing with a correct `<h4>` tag.
- Refactors custom page view and include specs: if the subtitle field was empty this generates an empty `<h2>` tag, now only shows this tag if have content. Also allows include links to custom page texts.
- Removes unnecessary `<p></p>` tags on investment partial: it was generating a HTML error: with double tags `<p><p><%= investment.description %></p></p>`
- Adds links to milestone description: allows include links on milestone descriptions.
- Removes old unused CSS.
- Fixes image height on items list with tags (see …
=> Design minor fixes

app/views/admin/newsletters/show.html.erb
Where
=====
* **Related PR's:** https://github.com/AyuntamientoMadrid/consul/pull/1274
What
====
The Admin Newsletter email feature is not ready for production until we solve and merge https://github.com/consul/consul/issues/2473
How
===
Using [`link_to_if`](https://apidock.com/rails/v4.2.1/ActionView/Helpers/UrlHelper/link_to_if) to integrate existing condition in a more elegant way, and add to the condition a simple `!Rails.env.production?`
Screenshots
===========
Deliver button gets disabled when condition is not met (maybe some styling would be nice here)
Test
====
No sure if this "patch" should be tested in a spec... I'd rather just check it after deploying to Production
Deployment
==========
As usual
Warnings
========
Remember this should be removed after …
=> Disable Newsletter's deliver button at production

app/controllers/admin/emails_download_controller.rb, app/controllers/admin/newsletters_controller.rb, app/helpers/user_segments_helper.rb, app/models/newsletter.rb, app/views/admin/emails_download/index.html.erb, app/views/admin/newsletters/_form.html.erb, app/views/admin/newsletters/index.html.erb, app/views/admin/newsletters/show.html.erb, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/es/activerecord.yml, config/locales/es/admin.yml, db/dev_seeds/newsletters.rb, db/migrate/20180220211105_change_newsletter_segment_recipient_to_string.rb, db/schema.rb, lib/user_segments.rb, spec/factories.rb, spec/features/admin/emails/newsletters_spec.rb, spec/lib/user_segments_spec.rb, spec/models/newsletter_spec.rb
Where
=====
* **Related Issue:** https://github.com/consul/consul/issues/2145
What
====
This is a refactor PR in preparation of the changes that will be sent to achieve issue https://github.com/consul/consul/issues/2145
How
===
- Removed `newsletter` scope from UserSegments on to correct places to avoid filtering by that scope on Admin Notification segments 42e3e2a2b401e94cff25b1272f6ce933f4c2b161
- Changed Newsletter's `segment_recipient` from integer to string to make things easier to maintain a002f1598b09d9ff79e673d3849e619614bd1d2a
If a user segment from UserSegments is removed from the code, and there are existing Newsletters on the database with that removed function name as `segment_recipient` value, those Newsletters will become unusable. Since we can't prevent code from being …
=> Admin newsletters & emails refactor

config/locales/en/admin.yml, config/locales/es/admin.yml, lib/user_segments.rb, spec/lib/user_segments_spec.rb
Where
=====
* **Related Issue:** #1291 
What
====
We need a user segment to have only administrators as recipients of both
newsletters and notifications, also one for betatesting just with our accounts
How
===
Adding a new segment functions, with its spec and name on ymls
Screenshots
===========
Test
====
Updated user segment model spec
Deployment
==========
As usual
Warnings
========
None
=> Add administrators & beta tester User Segments

config/locales/en/admin.yml, config/locales/es/admin.yml, lib/user_segments.rb, spec/lib/user_segments_spec.rb
Where
=====
* **Related Issue:** https://github.com/consul/consul/issues/2487
What
====
Added new filter to `UserSegments#feasible_and_undecided_investment_authors` to include those investments marked as unfeasible but the valuation still to be finished.
Screenshots
===========
=> Fix UserSegment feasible and undecided investment authors

app/views/custom/budgets/index.html.erb, app/views/custom/welcome/index.html.erb, app/views/welcome/_header.html.erb, config/locales/custom/en/custom.yml, config/locales/custom/es/custom.yml, spec/features/welcome_spec.rb
What
====
This PR: 
- Adds titles and descriptions for meta tags for each of budget phases (on budgets home).
- Adds titles and descriptions for meta tags for each of budget phases (on welcome home).
- Adds welcome header texts for each budget phases.
- Removes unnecessary custom keys on `config/locales/custom/es/custom.yml`.
How
==
Using the `current_budget.phase`:
On metatags (e.g.):
```
<% provide :title, t("meta_tags.budget_2018.#{current_budget.phase}.title") %>
<% provide :meta_description, t("meta_tags.budget_2018.#{current_budget.phase}.description") %>
```
On i18n keys (e.g.):
```
<%= t("welcome.header_budget.#{current_budget.phase}.title") %>
```
=> Adds titles and descriptions for all budget phases

app/assets/stylesheets/layout.scss, app/controllers/comments_controller.rb, app/controllers/notifications_controller.rb, app/controllers/proposal_notifications_controller.rb, app/models/notification.rb, app/views/custom/layouts/_header.html.erb, app/views/devise/menu/_login_items.html.erb, app/views/layouts/_admin_header.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/_notification_item.html.erb, app/views/notifications/_notification.html.erb, app/views/notifications/index.html.erb, app/views/notifications/mark_as_read.js.erb, app/views/notifications/mark_as_unread.js.erb, app/views/notifications/read.html.erb, config/i18n-tasks.yml, config/locales/en/general.yml, config/locales/es/general.yml, config/routes/notification.rb, db/dev_seeds.rb, db/dev_seeds/notifications.rb, db/migrate/20180222120017_add_read_at_to_notifications.rb, db/schema.rb, spec/factories.rb, spec/features/notifications_spec.rb, spec/models/notification_spec.rb, spec/support/common_actions.rb
Where
=====
* **Related Issue:** https://github.com/consul/consul/issues/2478
What
====
- Add links to mark notifications as read or unread
- Displays notifications in two tabs (Unread, All Notifications)
- Notifications are no longer deleted when read, instead, they are just marked as read
- Refactor notification item in header into a partial
- Refactor parameters to use objects instead of ids, a little simpler to read and same performance
- Increase test coverage for existing features
- Add notifications for all users in dev seeds 
Screenshots
===========
Deployment
==========
- As usual
Notes
========
- Existing notifications will be kept as unread
=> Extend notifications to be marked as read or unread

app/assets/javascripts/application.js, app/assets/javascripts/send_admin_notification_alert.js.coffee, app/controllers/admin/admin_notifications_controller.rb, app/controllers/notifications_controller.rb, app/models/admin_notification.rb, app/models/notification.rb, app/views/admin/_menu.html.erb, app/views/admin/admin_notifications/_form.html.erb, app/views/admin/admin_notifications/edit.html.erb, app/views/admin/admin_notifications/index.html.erb, app/views/admin/admin_notifications/new.html.erb, app/views/admin/admin_notifications/show.html.erb, app/views/notifications/_notification.html.erb, app/views/notifications/_notification_body.html.erb, app/views/notifications/index.html.erb, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/es/activerecord.yml, config/locales/es/admin.yml, config/routes/admin.rb, db/dev_seeds.rb, db/dev_seeds/admin_notifications.rb, db/migrate/20180221002503_create_admin_notifications.rb, db/schema.rb, spec/factories.rb, spec/features/admin/admin_notifications_spec.rb, spec/features/notifications_spec.rb, spec/models/admin_notification_spec.rb, spec/support/common_actions.rb
Where
=====
* **Related Issue:** https://github.com/consul/consul/issues/2145
What
====
Admins should be able to send notifications to users of a given segment, with a title, text and optional link (external or internal)
Screenshots
===========
Test
====
Increased for AdminNewsletters, as well as standard Notifications
Deployment
==========
To PRE for QA
Warnings
========
This PR needs a Backport to Consul!
=> [WIP] Admin Notifications

app/helpers/valuation_helper.rb, app/models/budget/investment.rb, app/views/admin/budget_investments/_investments.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/budget_investments_spec.rb
Where
=====
* **Related Issue:** https://github.com/consul/consul/issues/2472
What
====
- In the Budgets Investments admin section, add's the valuators group in the html table and in the csv
How
===
- Added one more column to the self.to_csv function on Budget::Investment and app/views/admin/budget_investments/_investments.html.erb
Screenshots
===========
- Html
- Csv
Test
====
- Added more conditions to the existing tests
Deployment
==========
- none
Warnings
========
- none
=> Include valuators group in Investment table & csv download

config/locales/custom/en/activemodel.yml, config/locales/custom/en/activerecord.yml, config/locales/custom/es/activemodel.yml, config/locales/custom/es/activerecord.yml, config/locales/en/activemodel.yml, config/locales/en/activerecord.yml, config/locales/es/activemodel.yml, config/locales/es/activerecord.yml
Where
=====
* **Related Issue:** #1129
What
====
* Move custom Decide Madrid I18n strings to `config/locales/custom` folder structure
* Removed duplicated keys
Notes
========
* This is the first PR in a series of reviews to keep Decide Madrid I18n files equal to CONSUL's, along with removing deprecated/duplicated keys, fixing typos, replace untranslated strings, etc —so any help is greatly appreciated!
=> Move custom I18n strings to `config/locales/custom` folder structure

app/assets/stylesheets/admin.scss, app/controllers/admin/budget_groups_controller.rb, app/helpers/admin_helper.rb, app/models/budget/group.rb, app/views/admin/budget_groups/update.js.erb, app/views/admin/budgets/_group.html.erb, app/views/admin/budgets/_group_form.html.erb, app/views/admin/budgets/_groups.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, db/schema.rb, spec/features/admin/budget_groups_spec.rb
Where
=====
* **Related Issue:** https://github.com/consul/consul/issues/2438
What
====
- Adds an inline form who changes the name of a Budget::Group if it's possible
How
===
- Added update function to admin/budget_groups_controller,  a js.erb view who handles the display of both error and correct saved object, and a new tests file. Also refactored a form, moved to partial.
Screenshots
===========
Test
====
- Added tests to check the correct behaviour of the form, working and showing errors
Deployment
==========
- none
Warnings
========
- none
=> Allow admin to change budget groups name

app/models/document.rb
Where
=====
* **Related issue:** #1280 (Closes #1280 once merged)
What
====
* Fixes incorrect URLs for attachments (documents) that caused 404 errors
How
===
* 404 errors were being returned when an user tried to download documents attached to certain Proposals (detailed on #1280)
* The errors were caused because the URL to access the documents was being generated based on the `secrets#secret_key_base` key rather than the filename of the attached documents, so when a change to this secret was made, it made the URLs invalid —the DB records and the actual files were left untouched
* To solve this issue, the `url` for the `Document` model was modified to use the `:basename` property rather than `:hash` —all broken URLs will work again (and previously working URLs are left untouched)
Test …
=> Fix incorrect URLs for attachments (documents)

app/views/custom/layouts/_header.html.erb, app/views/shared/_subnavigation.html.erb, db/dev_seeds.rb, db/dev_seeds/legislation_processes.rb, db/dev_seeds/legislation_proposals.rb, spec/features/legislation/proposals_spec.rb
Where
=====
* **Related issue:** #1198 (Closes #1198 once merged)
What
====
* Append the `active` CSS selector to only one menu element at once
How
===
* Created `Legislation::Proposal` seeds to replicate the issue locally
* Replaced `controller_name == 'proposals'` with `controller.class == ProposalsController` that was colliding with the `legislation/proposals_controller` file
* Removed unused variables when creating `Legislation::Process` seeds
Screenshots
===========
* Before: 
* After: 
Test
====
* Increased coverage to make sure only one `active` selector was available under the `navigation_bar` div
=> Only one menu element can have 'active' CSS selector at once

spec/features/officing/residence_spec.rb
Where
=====
* Related Issue: #1211 
* Related PR's: #1227 
What
====
- This is a preventive maintence for residence spec, the test has the same code in other parts, so it is better to fix the code to avoid future errors.
- The error is explanied in the related PR
How
===
- Explained in the related PR
- Also waiting for the review to do the backport. 
Screenshots
===========
Test
====
- N/A
Deployment
==========
- N/A
Warnings
========
- Explained in the related PR
=> Preventive maintenance for flaky test in resindece spec

spec/features/debates_spec.rb
Where
=====
Related Issue: #1213 (this PR closes #1213)
What
====
Fix the flaky that appears in the `spec/features/debates_spec.rb:72` spec.
How
===
This test used the function first (`first(:link, debate.title).click`), which is supposed [not to wait](http://stefan.haflidason.com/testing-with-rails-and-capybara-methods-that-wait-method-that-wont/) until some element appears on the page. If it doesn't wait, the test will look for the 'Go back' link before the page is rendered, so that it won't find it and will crash.
This changes make the test wait until a matching object appears on the screen. It is also a more specific test because of the use of the within, with encapsulates the finding to a concrete area.
As a side note, I noticed that the test was been executed as `:js` when no JS was …
=> Flaky spec: Debates Show: "Back" link directs to previous page

spec/features/admin/budget_investments_spec.rb
Where
=====
* **Related Issue:** #1194
What
====
Fix the flaky test that appeared in `spec/features/admin/budget_investments_spec.rb`, lines 998 and 960.
How
===
The problem here was related to the AJAX call that set the variable `visible_to_valuators` to true/false. When in the test the checkbox was clicked, sometimes the variable wasn't modified by the time the valuator page loaded.
My guess about it is that, in those cases, the test was faster than the AJAX call made to update the variable, so, by the time Capybara arrived to the valuators page, the investment wasn't updated yet. When the investment was updated on time, the test passed.
First, the test has been divided in two different scenarios:
1. Checks if the investments marked as `visible_to_valuators` are shown for the valuator. …
=> Flaky spec: Admin budget investment mark/unmark visible to valuators

app/views/custom/budgets/index.html.erb, spec/features/budgets/budgets_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/consul/issues/1258
What
====
We were using semi friendly urls:
`presupuestos/3/proyecto?heading_id=49`
With this PR we have nicer urls using slugs
`presupuestos/2018/distritos/arganzuela`
Deployment
==========
- As usual
Notes
========
- There is still a little redundacy depending on budget names and groups with a single heading:
decidepre.madrid.es/**presupuestos/presupuestos**-participativos-2018/**toda-la-ciudad/toda-la-ciudad**
=> Use friendly urls in budgets' index

app/controllers/budgets_controller.rb, app/views/custom/budgets/index.html.erb, spec/features/budgets/budgets_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/consul/issues/1314
What
====
This PR hides the map in the budget index page until a solution to make it load quicker in production, to avoid long page load times.
=> Hide budget index map

app/views/budgets/investments/_investment_show.html.erb, app/views/debates/show.html.erb, app/views/legislation/proposals/show.html.erb, app/views/polls/_poll_header.html.erb, app/views/proposals/share.html.erb, app/views/proposals/show.html.erb, app/views/spending_proposals/show.html.erb
Where
=====
* **Related Issue:** CONSUL https://github.com/AyuntamientoMadrid/consul/issues/1245
What
====
This PR fixes Facebook share button adding a `description`. This adds the required `data-desc` element, and Facebook will then accept the request.
More information on https://github.com/huacnlee/social-share-button/pull/160/files
=> Fixes Facebook share button

app/controllers/admin/emails_download_controller.rb, app/controllers/admin/newsletters_controller.rb, app/mailers/mailer.rb, app/models/newsletter.rb, app/views/admin/newsletters/show.html.erb, lib/user_segments.rb, spec/features/admin/emails/emails_download_spec.rb, spec/features/admin/emails/newsletters_spec.rb, spec/models/newsletter_spec.rb
Where
=====
* **Related Issue:** https://github.com/consul/consul/issues/2502
* **Related PR's:** https://github.com/consul/consul/pull/2516
What
====
Remove empty emails from Newsletters and Email Downloads
PR Already approved at consul https://github.com/consul/consul/pull/2516 (but forgot to work as a fork 🙈  🙇 )
=> Fix user segment emails

app/models/budget/investment.rb, app/views/budgets/investments/_investment_show.html.erb, spec/features/budgets/investments_spec.rb, spec/models/budget/investment_spec.rb
What
====
- Only display unfeasibility explanation of a budget investment when the investment is unfeasible, valuation has finished and the unfeasibility_explanation is not blank
How
===
- Adding a check for valuation finished, it's the only one we were missing
Deployment
==========
- As usual
Warnings
========
- None
=> Fix display of unfeasibility explanation

app/views/notifications/_notification.html.erb, spec/features/notifications_spec.rb
References
=====
* **Related Rollbar bug:** https://rollbar.com/consul/Participacion/items/1440/
Why:
===
There are Notifications with associated `notifiables` that actually are
not anymore Notifiables (the class doesn't include the Notifiable
concern). So when Notification delegates certain "notifiable" methods
to them the is an error.
Screenshots
===========
No need
Notes
========
None
=> Fix notifications with notifiable resources that are no longer notifiable

spec/features/tracks_spec.rb
Where
=====
* **Related Issue:** #1175 (this PR closes #1175)
What
====
Fix the flaky that appeared in `spec/features/tracks_spec.rb:304`.
How
===
This flaky was related to JS files that are been loaded in the page.
In my opinion, the continuous visits to different pages don't let the JavaScript files load correctly, so, sometimes, the page need some code that has not been loaded yet. That caused some different errors, not only the ones related to CKEDITOR (I really think they all have the same origin).
```
Tracking Tracking pages Codes
Failure/Error: visit "proposals"
Capybara::Poltergeist::JavascriptError:
One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist …
```
=> Hunt the flaky - Tracking Tracking pages Codes

spec/shared/features/notifiable_in_app.rb
Where
=====
* **Related Issue:** #1271
What
====
Fix the flaky spec that appears in `spec/shared/features/notifiable_in_app.rb`
How
===
As far as I was able to research, the problem with this flaky was around the `login_as author` function, where, for some reason, the `current_user` variable was not being set correctly. In the previous version of the test, after loging in as the notifiable's author, there were two `visit root_path`.
```
login_as author
visit root_path
visit root_path
find(".icon-notification").click
```
With both visits there, the test passed (always), but, when I removed one of them, the test started to fail (constantly). I realized that, after the first one, the current user was not set, so there weren't notifications available and the `.icon-notification` wasn't there …
=> Flaky spec: Polls Concerns behaves like notifiable in-app Multiple users commented on my notifiable

app/models/abilities/valuator.rb, app/views/valuation/budget_investments/edit.html.erb, spec/features/valuation/budget_investments_spec.rb, spec/models/abilities/valuator_spec.rb
References
===
Related Issue: https://github.com/consul/consul/issues/2501
This PR is based on https://github.com/AyuntamientoMadrid/consul/pull/1336 branch 
Objectives
====
We don't want valuators (that aren't admins) reopening/editing finished valuations.
Visual Changes
===========
=> Valuators cannot reopen finished valuations

spec/features/comments/budget_investments_spec.rb, spec/features/comments/debates_spec.rb, spec/features/comments/legislation_annotations_spec.rb, spec/features/comments/polls_spec.rb, spec/features/comments/topics_spec.rb, spec/features/custom/probe_option_comments_spec.rb
Where
=====
* **Related issues:** #1177, #1192
* **Related PR:** #1212
What
====
* The changes done on #1212, while they did reduce the number of times `voting comments` related tests failed, they did not mitigate entirely the flakys —the proposed changes on this PR should resolve these issues completely.
How
===
* Added an `after` hook to logout to `probe_option_comments#update` scenario, similar to the other affected examples, to ensure a clean state before each test
Test
====
* Fixed coverage
Notes
====
* Once merged, it will be ported to upstream to ensure consistency and avoid (possible) flakys
=> Fix recurrent flakys for voting comments-related specs

app/models/document.rb
Where
=====
* **Related issue:** #1280 (Closes #1280 once merged)
* **Related PRs:** #1307, #1321
What
====
* As per @voodoorai2000's request, I'm bringing back the patch presented on #1307 and reverted on #1321
* See [this comment](https://github.com/AyuntamientoMadrid/consul/issues/1280#issuecomment-368906844) in order to reproduce the issue locally
How
===
* See #1307 for more details
Test
====
* Manual testing is needed for this patch. Check out [these](https://github.com/AyuntamientoMadrid/consul/issues/1280#issuecomment-370024857) [comments](https://github.com/AyuntamientoMadrid/consul/issues/1280#issuecomment-370027623) on how to test it on a Preproduction environment before deploying
* You can use this [Rake task](https://gist.github.com/aitbw/93910b27d2a0ba0aa42db99811adda9d) to …
=> Fix incorrect URL generation for attachments (documents)

app/models/document.rb
Reverts AyuntamientoMadrid/consul#1334
Sorry @aitbw but still this is not the solution, this fixes links to Documents created previously to the problem (possible october) but breaks document urls for the ones created after the problem.
I'm taking over the associated issue
=> Revert "Fix incorrect URL generation for attachments (documents)"

app/views/ballots/_ballot.html.erb, app/views/budgets/investments/_votes.html.erb, app/views/custom/probe_options/plaza/show.html.erb, app/views/custom/probes/plaza/thanks.html.erb, app/views/legislation/proposals/_featured_votes.html.erb, app/views/legislation/proposals/_votes.html.erb, app/views/proposals/_featured_votes.html.erb, app/views/proposals/_votes.html.erb, app/views/spending_proposals/_votes.html.erb
References
==========
**Issues**:
- https://github.com/AyuntamientoMadrid/consul/issues/1338
- https://github.com/AyuntamientoMadrid/consul/issues/1245
Objectives
==========
Replaces hardcoded social share button tag with correct partial. For example, replace:
```
<%= social_share_button_tag("#{proposal.title} #{setting['twitter_hashtag']}", url: proposal_url(proposal), via: setting['twitter_handle']) %>
```
using the correct `shared/social_share` partial:
```
<%= render partial: 'shared/social_share', locals: {
title: proposal.title,
url: proposal_url(proposal),
description: proposal.summary
} %>
```
=> Fix social share buttons

app/helpers/budget_headings_helper.rb, app/models/budget/investment.rb, app/views/budgets/investments/_ballot.html.erb, app/views/budgets/investments/_header.html.erb, app/views/budgets/investments/_sidebar.html.erb, app/views/budgets/investments/_votes.html.erb, config/locales/custom/en/budgets.yml, config/locales/custom/es/budgets.yml, config/locales/en/admin.yml, config/locales/en/budgets.yml, config/locales/es/admin.yml, config/locales/es/budgets.yml, spec/features/ballots_spec.rb, spec/features/budgets/ballots_spec.rb, spec/models/budget/investment_spec.rb
Where
=====
**Related Issue:** https://github.com/consul/consul/issues/2496
What
====
This PR adds heading link on the different heading assigned message.
Screenshots
===========
**Message before (with the link only on header message)**
**Message after (with the link on the header and each item on hover)**
=> Heading link on budgets message

app/helpers/application_helper.rb, app/models/budget.rb, app/views/budgets/results/_results_table.html.erb, spec/models/budget_spec.rb
References
==========
Consul PR https://github.com/consul/consul/pull/2443
Objectives
==========
All currencies are formatted using the default locale language (I18n.default_locale) instead of the user selected language. We need to use the user language to format currencies
Check original PR 🙏 
Notes
Deploying to PRE as a feature branch to test!
=> Use user locale instead of default locale to format currencies 

app/views/budgets/investments/_banner_city.html.erb, app/views/budgets/investments/_banner_district.html.erb, app/views/budgets/investments/index.html.erb, config/locales/custom/en/custom.yml, config/locales/custom/es/custom.yml
Objectives
==========
Adds banners on budget investments index if current budget is on selecting or balloting phase. These banners allow remembering to users they can support/vote on each group.
Visual Changes
=> Budget banners

app/views/admin/users/_users.html.erb, spec/features/admin/users_spec.rb
References
==========
This closes https://github.com/AyuntamientoMadrid/consul/issues/1335
Objectives
==========
Adds a link to the username on admin users index view to their public profile. As the link goes outside of Admin Panel I have included a `target="_blank"` on it.
Visual Changes
**Now the names are links!** 🎉
Notes
Backport to CONSUL after merge
=> Admin users

app/assets/stylesheets/admin.scss, app/views/admin/budget_investments/_written_by_author.html.erb, app/views/documents/_documents.html.erb, app/views/images/_image.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/budget_investments_spec.rb
References
==========
**Related issue**: https://github.com/consul/consul/issues/2376
Objectives
==========
If the budget investments have an image or documents now appears a link to budget investment with a `#image` or `#documents` anchor on a new tab to allow admin check easily the associated images and docs of the budget investment on evaluation.
Visual Changes
Notes
Backport this to CONSUL when merged.
=> Admin budget investment info

app/controllers/valuation/budget_investments_controller.rb, config/locales/en/valuation.yml, config/locales/es/valuation.yml, db/dev_seeds/settings.rb, spec/features/admin/budget_investments_spec.rb, spec/features/comments/budget_investments_valuation_spec.rb, spec/features/emails_spec.rb, spec/features/valuation/budget_investments_spec.rb
References
==========
This is an alternative take to https://github.com/AyuntamientoMadrid/consul/pull/1341/commits
Objectives
==========
Setting['feature.budgets.valuators_allowed'] was bein used to prevent
valuators from editing and valuating investments, as a "switch".
We've budget phases now, and just by checking if current budget phase is
valuating will do the same but without having to remember changing the
setting value.
Explanatory error message appears (instead of a 404 error) when the valuator tries to access dossier edit outside valuation phase
Notes
We should remember to remove the Setting['feature.budgets.valuators_allowed'] from PRE and PRO servers manually through console (don't consider creating a rake …
=> Replace valuators_allowed setting for checking if budget is valuating

spec/features/officing/residence_spec.rb
References
==========
https://github.com/AyuntamientoMadrid/consul/issues/1209
Objectives
==========
It fixes some flakys on spec/features/officing/residence_spec.rb caused by an select wich  shuld be loaded through ajax
none
Notes
as can be seen [here](http://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FNode%2FActions%3Aselect) is suposed that select waits until the select its available, but the flaky happens when the select is no loaded, so I added some assertions which includes have_selector, and this one I am sure that waits for ajax to finish
=> added have_selector to ensure the existence of the select residence_document_type

spec/features/officing/residence_spec.rb
References
==========
* **Related Issue:** #1210
Objectives
==========
(The explanation is the same as in #1342, #1343 and #1349 PRs because the problem is exactly the same).
What happened here was that, at the moment the test tries to reach the residence verification page, the message that it's supposed to appear (announcing the booth choosen for that officer) is not there. In this case, because there is only one booth created, the test should not pass through the page to choose it (and it doesn't pass, in fact), so the booth should be choosen automatically. The problem is that the date of each officer assignment is different from Date.current, so, for the app, there aren't any booths for today and there is no message, what generates the test to fail.
I realized that the problem could be …
=> Flaky spec: Residence Verify booth Unable to find visible css "#officing-booth"

spec/features/polls/voter_spec.rb
References
==========
* **Related Issue:** #1195
Objectives
==========
Fix the flaky that appeared in `spec/features/polls/voter_spec.rb:142`.
The problems was that the test was not reaching to the residence verification page, so it couldn't find the select box for the DNI (and that's the error reported in the issue). To figure out what was going on there, I studied the flow that the test follows so that I could find the scenarios where it would crash, and, after doing it, step by step, I determined that the test will fail when:
- There are more than 1 `officer_assignments` (booths) for this user, so the page will redirect to the select booth page, instead to the residence verification page.
- There aren't any `officer_assignments`, so that the user can't even reach the target page (it …
=> Flaky spec: Voter Origin Trying to vote in booth and then in web

spec/features/officing/booth_spec.rb
References
==========
* **Related Issues:** #1202, #1203 and #1204
Objectives
==========
Fix the flaky that appeared in `spec/features/officing/booth_spec.rb:53`, `spec/features/officing/booth_spec.rb:82` and `spec/features/officing/booth_spec.rb:33`.
**(This explanation is the same as in #1342 PR because the problem is exactly the same).**
The problems was that the tests were not reaching to the residence verification page, so they failed in their assertions. To figure out what was going on there, I studied the flow the test follows so that I could find the scenarios where it would crash, and, after doing it, step by step, I determined that the test will fail when:
- There are more than 1 `officer_assignments` (booths) for this user, so the page will redirect to the select booth page.
- …
=> Flaky spec: booth_spec.rb

app/models/valuator_group.rb, spec/factories.rb, spec/models/budget/investment_spec.rb, spec/models/valuator_group_spec.rb
References
==========
In my way to achieve issue https://github.com/consul/consul/issues/2461 I've found some things that I'm trying to fix in independent PR's to avoid mixing objectives.
Objectives
==========
- ValuatorGroup#name needs to be present and unique
- Budget::Investment#by_valuator_group scope needs to be tested
None
Notes
None
=> Add Valuator Group name validation & related specs

app/controllers/valuation/budget_investments_controller.rb, app/views/valuation/budget_investments/index.html.erb, spec/features/valuation/budget_investments_spec.rb
References
==========
In my way to achieve issue https://github.com/consul/consul/issues/2461 I've found some issue in the valuation panel heading filters
Objectives
==========
Fix heading filters by correctly creating a scenario spec that covers all combinations and checks right behaviour is met.
No real visual changes, only right behaviour.
Notes
Check each commit to easily understand changes, as the second commit just encloses all the "Index related" scenarios in a:
```ruby
feature 'Index' do
...
end
```
and the indentation changes makes it look like a lot of "real" changes
=> Fix valuation heading filters

config/locales/en/admin.yml, config/locales/es/admin.yml, lib/user_segments.rb, spec/lib/user_segments_spec.rb
References
==========
Direct product request
Objectives
==========
Create a segment that returns all users that haven't supported investments on current budget
None
Notes
This PR will need a backport to Consul as its not a segment specific to madrid's needs
=> User segment for users that haven't supported in budget

app/controllers/valuation/budget_investments_controller.rb, app/controllers/valuation/budgets_controller.rb, app/models/budget/investment.rb, app/views/valuation/budget_investments/show.html.erb, app/views/valuation/budgets/index.html.erb, config/locales/en/seeds.yml, config/locales/en/valuation.yml, config/locales/es/seeds.yml, config/locales/es/valuation.yml, db/dev_seeds/budgets.rb, db/dev_seeds/users.rb, spec/features/valuation/budget_investments_spec.rb, spec/features/valuation/budgets_spec.rb, spec/models/budget/investment_spec.rb
References
==========
This PR accomplishes https://github.com/consul/consul/issues/2461 and its based on https://github.com/AyuntamientoMadrid/consul/pull/1357 & https://github.com/AyuntamientoMadrid/consul/pull/1358 refactor&fixes PRs
Objectives
==========
Valuators have a ValuatorGroup that can get investments assigned to it.    Valuators should see those investments as well as directly assigned ones
None, just increased the investments list to display
Notes
None
=> Show group assigned investments to valuators

spec/features/moderation/debates_spec.rb
References
==========
This PR fixes and closes #1222 
Objectives
==========
There was a flaky in the file `spec/features/moderation/debates_spec.rb` when hidding debates. The problem was a race condition that appeared after clicking the 'Hide' button.
This button hides a debate, and in the UI it fades using JS. If the test was fast enought and the expect assertion executes before the CSS class changes, Capybara won't find any id that matches `#debates_#{debate.id}.faded`; there is a div with id `#debate_5`, but it's not faded yet.
To make Capybara wait the stablished wait_time (capybara's `max_wait_time`, by default 2 secs), I changed the assertion. Instead of using `have_css(...)`, I used `find(...)`, that, according to [this](https://www.urbanbound.com/make/fix-flaky-feature-tests-by-usi …
=> Flaky spec: Moderate debates Hide

spec/features/officing_spec.rb
References
==========
* https://github.com/AyuntamientoMadrid/consul/issues/1200
Objectives
==========
* Fix the flaky, i seems to happen when the container of the selector for dni/passport isn't present. At first it looked like an error due the date used for the 2 poll_shift created (as it was [here](https://github.com/AyuntamientoMadrid/consul/pull/1343) ) but a quick check using different dates provoked a different error, so suspicions recalled about a race condition in the selector container. The solution that I proposes here is just  check the existence of the container using have_selector, which waits for js to be completed
* none
Notes
* none
=> Fix for flaky spec: Poll Officing Officing dashboard available for multiple sessions

spec/features/comments/topics_spec.rb
References
==========
* Related PRs: #1212, #1241
Objectives
==========
* Adds missing `logout` on `comments/topics#update` scenario (under `Commenting topics from budget investments` feature) to mitigate a possible flaky
* None
Notes
* The commit for this PR is already included in the consul/consul#2448 backport
=> Add missing `logout` on comments/topics#update scenario

spec/features/polls/polls_spec.rb
References
==========
* **Related Issue:** #1208
Objectives
==========
**(This explanation is the same as in #1342 and #1343 PRs because the problem is exactly the same).**
The problems was that the test was not reaching to the residence verification page, so it couldn't find the select box for the DNI (and that's the error reported in the issue). To figure out what was going on here, I studied the flow the test follows so that I could find the scenarios where it would crash, and, after doing it, step by step, I determined that the test will fail when:
- There are more than 1 `officer_assignments` (booths) for this user, so the page will redirect to the select booth page.
- There aren't any `officer_assignments`, so that the user can't even reach the target page (it redirects to the …
=> Flaky spec: Polls Booth & Website Already voted on booth cannot vote on website

app/assets/stylesheets/admin.scss, app/controllers/admin/budget_groups_controller.rb, app/helpers/admin_helper.rb, app/models/budget/group.rb, app/views/admin/budget_groups/update.js.erb, app/views/admin/budgets/_group.html.erb, app/views/admin/budgets/_group_form.html.erb, app/views/admin/budgets/_groups.html.erb, app/views/admin/budgets/show.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/budget_groups_spec.rb
References
==========
This is a second try to make https://github.com/AyuntamientoMadrid/consul/pull/1265 work as it had to be reverted because it crashed in preproduction server.
Objectives
==========
Adds an inline form who changes the name of a Budget::Group if it's possible
More to come when this is completed
Notes
WIP because it has to be tested again in PRE and possibly fixed
=> Budget group name edit

app/controllers/admin/budget_groups_controller.rb, app/models/budget/investment.rb, app/views/admin/budgets/_group_form.html.erb, app/views/budgets/investments/_votes.html.erb, config/i18n-tasks.yml, config/locales/custom/en/budgets.yml, config/locales/custom/es/budgets.yml, config/locales/en/admin.yml, config/locales/en/budgets.yml, config/locales/es/admin.yml, config/locales/es/budgets.yml, db/migrate/20180320104823_add_max_votable_headings_to_budget_groups.rb, db/schema.rb, spec/features/admin/budget_groups_spec.rb, spec/features/budgets/votes_spec.rb, spec/models/budget/investment_spec.rb
References
==========
**Issue**: https://github.com/consul/consul/issues/2320
Objectives
==========
Allow users to support in multiple headings of a single group by changing the maxium number of votable headings from the admin section
Visual Changes
Notes
Now that we have the option of voting in multiple headings per group, the method of voting in a `different heading assigned` has become deprecated and thus removed. 
Instead, knowing if a user can vote in a new heading, depends on the maximum votable headings per group variable. 
Also, if a user has already been granted permission to support in a heading, we assume it has permissions to support in it throughout the phase, even if the maximum number of votable headings is decreased during the …
=> Allow users to support in multiple headings per group

app/assets/javascripts/map.js.coffee, app/controllers/budgets/investments_controller.rb, app/controllers/budgets_controller.rb, app/helpers/budgets_helper.rb, app/models/abilities/everyone.rb, app/models/map_location.rb, app/views/custom/budgets/index.html.erb, config/routes/budget.rb
References
==========
Related issue: https://github.com/AyuntamientoMadrid/consul/issues/1314
Objectives
==========
There's a need to decrease the loading time of the budgets' main page. The problem is how we are getting the information needed to render the investments location map.
The changes I made to achieve it are:
- For the immediate loading of the data, we just need the investments geographical locations, so that's the only information it's realtime rendered with the rest of the page.
- To get the information showed in the popup of each marker, an ajax call is performed when the user clicks in the marker.
=> Improve budgets map performance

app/views/admin/budget_investments/show.html.erb, app/views/admin/valuators/index.html.erb, app/views/budgets/investments/_form.html.erb, app/views/budgets/investments/_investment.html.erb, app/views/budgets/investments/_milestones.html.erb, app/views/custom/polls/index.html.erb, app/views/images/_image.html.erb, app/views/legislation/processes/_debate.html.erb, app/views/legislation/processes/debate.html.erb, app/views/map_locations/_form_fields.html.erb, app/views/polls/_gallery.html.erb, app/views/polls/_poll_group.html.erb, app/views/polls/index.html.erb, app/views/polls/results.html.erb, app/views/proposals/_form.html.erb, app/views/proposals/_proposal.html.erb, config/i18n-tasks.yml, config/locales/custom/en/general.yml, config/locales/custom/es/general.yml, config/locales/en/budgets.yml, config/locales/en/general.yml, config/locales/es/admin.yml, config/locales/es/budgets.yml, config/locales/es/general.yml, spec/features/legislation/processes_spec.rb, spec/features/polls/polls_spec.rb
Objectives
==========
Minor fixes for i18n, HTML, and styles:
- Improves i18n of admin budgets.
- Adds class on backlink to admin budget investments show.
- Moves h3 tag outside of table on polls results (Fixes HTML validation error).
- Adds unicode_normalize for alt and title on image partial (Prevents HTML validation warning).
- Adds map skip checkbox i18n for budget investments.
- Adds a message on polls index if there are no open polls.
- Adds a message on custom polls index if there are no open polls.
- Fixes actions buttons on admin valuators index table.
- Shows a message only if there are questions on legislation debate.
- Updates custom meta tags for polls index.
Notes
Backport this PR to CONSUL except the custom commits:
- Adds message on custom polls index …
=> Minor fixes

app/controllers/admin/budget_investment_statuses_controller.rb, app/models/budget/investment/status.rb, app/views/admin/_menu.html.erb, app/views/admin/budget_investment_statuses/_form.html.erb, app/views/admin/budget_investment_statuses/edit.html.erb, app/views/admin/budget_investment_statuses/index.html.erb, app/views/admin/budget_investment_statuses/new.html.erb, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/en/seeds.yml, config/locales/es/activerecord.yml, config/locales/es/admin.yml, config/locales/es/seeds.yml, config/routes/admin.rb, db/dev_seeds/budgets.rb, db/migrate/20180321140337_create_budget_investment_statuses.rb, db/schema.rb, spec/factories.rb, spec/features/admin/budget_investment_statuses_spec.rb, spec/models/budget/investment/status_spec.rb
References
==========
Related issue: https://github.com/consul/consul/issues/2432
Objectives
==========
- Added `Budget::Investment::Statuses` and admin section to manage them.
- Included test statuses in dev_seeds files.
Visual Changes
=> Budget statuses

app/assets/stylesheets/admin.scss, app/assets/stylesheets/participation.scss, app/views/admin/newsletters/show.html.erb, app/views/budgets/index.html.erb, app/views/custom/budgets/index.html.erb, app/views/custom/debates/index.html.erb, app/views/custom/proposals/index.html.erb, app/views/custom/welcome/_recommended_carousel.html.erb, app/views/debates/index.html.erb, app/views/layouts/_mailer_footer.html.erb, app/views/layouts/_mailer_header.html.erb, app/views/layouts/mailer.html.erb, app/views/proposals/index.html.erb, app/views/welcome/_recommended_carousel.html.erb, config/locales/en/general.yml, config/locales/es/general.yml
Objectives
==========
- Fixes scss lint warnings.
- Fixes headings height on budgets index. _[Screenshot 1]_
- Adds view mode on proposals index page.
- Removes custom content on debates index and adds custom debates index view.
- Adds missing i18n on welcome recommendations. _[Screenshot 2]_
- Moves mailer header and footer to partials (prevent layout break).  _[Screenshot 3]_
Visual Changes
**[Screenshot 1]**
**> BEFORE**
**> AFTER**
**[Screenshot 2]**
**[Screenshot 3]**
=> UI design fixes

app/assets/stylesheets/admin.scss, app/views/admin/budget_groups/update.js.erb, app/views/admin/budgets/_group.html.erb, app/views/admin/budgets/_max_headings_label.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/budget_groups_spec.rb
References
==========
**Related issue:** #1384
Objectives
==========
Add a label to see the maxium number of headings in which a user can vote. It should update automatically (using JS) when the heading is updated.
Visual Changes
Notes
I used the commit mentioned in the issue https://github.com/consul/consul/commit/1b63ba39d299a7bdda7465a31d78a733cb1136f3 as a startpoint. Then, I modified the UI and the specs to fill the requirements.
The specs has not change too much, just remove the page refresh so that it checks the change done by AJAX.
=> Add max heading number in Budget Group list

app/assets/stylesheets/admin.scss, app/views/admin/legislation/processes/index.html.erb
References
==========
None
Objectives
==========
Fixes incorrect title positioning for Legislation Processes index view in Admin panel. This was done removing unnecessary markup in the related view as well as removing an unused CSS class.
**Before**:
**After**:
Notes
Backport pending to [CONSUL](http://github.com/consul/consul/) once merged into `master`
=> Fix title positioning for Legislation Processes in admin panel

app/views/admin/_menu.html.erb
References
==========
Closes #1408 once merged into `master`
Objectives
==========
`Participatory budgets` option in Admin menu is highlighted by default and stays highlighted even when the user clicks in other options. This PR solves this issue.
**Before**:
**After**:
Notes
None
=> Fix incorrect highlight for selected option in admin menu

app/models/budget/investment/exporter.rb, app/views/admin/budget_investments/_investments.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/budget_investments_spec.rb
References
==========
Related issue https://github.com/AyuntamientoMadrid/consul/issues/1421
Objectives
==========
Added `visible_to_valuators` value and author's username to admin budget investments CSV export.
=> Add `visible_to_valuators` and author username to admin investments CSV

app/controllers/admin/signature_sheets_controller.rb, app/views/admin/signature_sheets/index.html.erb, app/views/admin/signature_sheets/show.html.erb, spec/features/admin/signature_sheets_spec.rb
References
==========
Related issue: https://github.com/AyuntamientoMadrid/consul/issues/1427
=> Add year to Signature Sheets's dates in the admin section and order by date

config/locales/custom/en/budgets.yml, config/locales/custom/es/budgets.yml, config/locales/en/budgets.yml, config/locales/es/budgets.yml
References
==========
* **Related issue**: #1129
Objectives
==========
Move custom :gb: / :es: Budgets I18n strings to their proper files under `config/locales/custom` folder structure
None
Notes
This is an ongoing effort to move all custom I18n strings located in `config/locales` to their proper folders/files, so several PRs are needed in order to achieve this. Small PRs are being done from time to time to make the review process easier and to avoid possible conflicts
=> Move custom Budgets I18n strings to `locales/custom` folder

config/locales/custom/en/devise.yml, config/locales/custom/en/devise_views.yml, config/locales/custom/es/devise_views.yml, config/locales/en/devise.yml, config/locales/en/devise_views.yml, config/locales/es/devise_views.yml
References
==========
* Related issue: #1129 
Objectives
==========
Move all custom :gb: / :es: Devise-related I18n strings to their proper files under `config/locales/custom` folder structure
None
Notes
This is an ongoing effort to move all custom I18n strings located in `config/locales` to their proper folders/files, so several PRs are needed in order to achieve this. Small PRs are being done from time to time to make the review process easier and to avoid possible conflicts
=> Move custom Devise I18n strings to `locales/custom/` folder

app/assets/stylesheets/admin.scss, app/controllers/admin/budget_groups_controller.rb, app/models/budget/group.rb, app/views/admin/budget_groups/update.js.erb, app/views/admin/budgets/_group.html.erb, app/views/admin/budgets/_group_form.html.erb, app/views/admin/budgets/_heading_form.html.erb, app/views/admin/budgets/_max_supportable_headings_label.html.erb, app/views/admin/budgets/_max_votable_headings_label.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, db/migrate/20180418164308_add_max_supportable_headings_to_budget_groups.rb, db/schema.rb, spec/features/admin/budget_groups_spec.rb, spec/models/budget/group_spec.rb
References
==========
Related issue: https://github.com/consul/consul/issues/2498
Objectives
==========
In order to achieve the issue https://github.com/consul/consul/issues/2498, we need to set a maximum supportable headings in budget groups, as it has been implemented with the votes.
In this PR, I've added a new attribute to save the `max_supportable_headings` in Budget::Group and a select in the admin section to manage groups and headings (`admin/budgets/[:budget_id]`) to set the value.
The logic to allow/prevent users to support the amount of headings defined is not implemented, that will come in a separated PR after this one's merged.
Visual Changes 
Now the info about `max_supportable_headings` and `max_votable_headings` appears only if headings is present. …
=> Added `max_supportable_headings` to Budget::Group

app/controllers/budgets/investments_controller.rb, app/models/budget/investment.rb, spec/features/budgets/investments_spec.rb
References
==========
There where some problems around investments migrated from spending proposals:
- Milestones created on 2017 Investments that had the same ID as a migrated Spending Proposal... lead to milestone creation on the associated investment to the migrated spending proposal.
- Investments map links where incorrect, leading to 2016 proposals when another "same ID as" scenario happened https://twitter.com/sergio_gfp/status/982164154021593089
Objectives
==========
Revert the changes done to wrongly solve https://github.com/AyuntamientoMadrid/consul/issues/1163 and another scenario that was described internally: When visiting and old spending proposal url, it should redirect to the new investment url but maintaining the old spending proposal ID.... that leads to "same ID as" …
=> Fix Investments bugs from migrated Spending Proposals

app/assets/javascripts/map.js.coffee, app/models/map_location.rb
References
==========
Reported issue from https://twitter.com/sergio_gfp/status/982164154021593089
Objectives
==========
The map at https://decide.madrid.es/presupuestos its showing some Investments that have no geolocalization, or even are from 2016 Budget!
That's because right now code was returning current Budget MapLocation's IDs, and the JS is looking for Investments by those ids... sometimes finding a record with same ID but totally NOT the one associated to the MapLocation.
None
Notes
The MapLocation model really needs to get its relation with mappables transformed into a polymorphic one.
The code around showing maps needs a huge refactor to avoid mixing edit map/individual map/massive map code.
=> Fix MapLocation json_data to return mappable ids

lib/census_api.rb, lib/document_parser.rb, spec/features/admin/signature_sheets_spec.rb, spec/features/officing/letters_spec.rb, spec/lib/census_api_spec.rb, spec/lib/local_census_spec.rb
Objectives
==========
Always calculate letter for a spanish document number
Notes
Sometimes when transcribing signature sheets the letters are mistyped. For example: using 'P' instead of 'F'. This commit generates the letter every time to make sure we avoid this typos
=> Always calculate correct letter for DNI

app/views/admin/budgets/_heading_form.html.erb
References
==========
This PR fixes **Admin budgets Manage groups and headings Create heading** spec:
`rspec ./spec/features/admin/budgets_spec.rb:253`
It was failing with:
```
Admin budgets
Manage groups and headings
Create heading (FAILED - 1)
Failures:
1) Admin budgets Manage groups and headings Create heading
Failure/Error: expect(page).not_to have_content 'This group has no assigned heading.'
expected not to find text "This group has no assigned heading." in "Districts improvments Edit group Add heading This group has no assigned heading."
```
How
==========
Removes data `toggle focus` on _population info_ field. I think (after a little research) It does not work as expected because the value of the element is already updated to `''` when the focus is triggered and the heading it …
=> Budgets admin add heading

app/views/budgets/investments/_investment_show.html.erb, config/locales/en/budgets.yml, config/locales/es/budgets.yml, spec/features/budgets/investments_spec.rb
Objectives
==========
This PR adds a message to selected budget investments.
Visual Changes
Notes
=> Budget investment selected

app/views/admin/budget_investments/index.html.erb, app/views/budgets/index.html.erb, app/views/custom/admin/budget_investments/index.html.erb, app/views/custom/budgets/index.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml
Objectives
==========
Shows **See results** button _[Screenshot_1]_ only if current budget is finished. 
Also included this button on admin panel `/admin/budgets/N/budget_investments`. _[Screenshot_2]_
Visual Changes
**[Screenshot_1]**
**[Screenshot_2]**
Notes
Backport this to CONSUL repo (don't include commits of `custom` views)
=> Budgets see results

app/assets/javascripts/globalize.js.coffee, app/helpers/globalize_helper.rb, app/views/admin/budget_investment_milestones/_form.html.erb, app/views/admin/budget_investment_milestones/_globalize_locales.html.erb, spec/features/translations_spec.rb
Objectives
==========
Improves admin content translatable UI with some minor changes to maintain consistency with the Admin Panel styles.
Visual Changes
**BEFORE**
**AFTER**
Notes
=> Content translatable UI

app/models/user.rb, spec/models/user_spec.rb
References
==========
- https://github.com/AyuntamientoMadrid/consul/issues/1463
Objectives
==========
Avoid exception in home page when displaying recommendations
Notes
The problem was related to loading tags of hidden proposals, which were then used to calculate recommendations. 
With this PR we are skipping proposals that have been hidden when calculating recommended proposals
=> Deal gracefully with recommendations of hidden proposals

app/controllers/users_controller.rb, app/helpers/followables_helper.rb, spec/features/users_spec.rb
References
==========
- https://github.com/AyuntamientoMadrid/consul/issues/1462
Objectives
==========
- Avoid exception in my activity when displaying followed proposals that have been hidden
- Display correct number of followed proposals, without including proposals that have been hidden
None
=> Deal gracefully with hidden followable in my activity

app/controllers/admin/activity_controller.rb, app/controllers/admin/system_emails_controller.rb, app/models/activity.rb, app/models/proposal_notification.rb, app/views/admin/activity/show.html.erb, app/views/admin/system_emails/preview_pending/_proposal_notification_digest.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, config/routes/admin.rb, spec/features/admin/activity_spec.rb, spec/features/admin/system_emails_spec.rb, spec/features/emails_spec.rb, spec/models/proposal_notification_spec.rb
References
==========
Related issue: https://github.com/AyuntamientoMadrid/consul/issues/1468
Objectives
==========
- Add moderation abilities for Proposal Notifications.
- Add new tab "System emails" in the Moderation section `/admin/activity`.
Screen shots
==========
=> Moderate pending proposal system emails

app/models/abilities/administrator.rb, app/views/budgets/show.html.erb, spec/features/budgets/budgets_spec.rb
References
==========
Related issue: https://github.com/AyuntamientoMadrid/consul/issues/1474
Objectives
==========
Remove button 'See results' from budgets `#show` action view for all users unless the budget is finished.
=> Removes permissions for admins to access unfinished budget results

app/controllers/admin/legislation/processes_controller.rb, app/controllers/admin/poll/booth_assignments_controller.rb, app/controllers/admin/poll/questions_controller.rb, app/views/admin/budgets/_form.html.erb, app/views/admin/legislation/proposals/_form.html.erb, app/views/admin/poll/booth_assignments/manage.html.erb, app/views/admin/poll/booths/_form.html.erb, app/views/admin/poll/polls/_form.html.erb, app/views/admin/poll/questions/_form.html.erb, app/views/admin/poll/results/_show_results.html.erb, app/views/admin/poll/results/index.html.erb, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/es/activerecord.yml, config/locales/es/admin.yml, db/dev_seeds/legislation_processes.rb, spec/features/admin/poll/booths_spec.rb, spec/features/admin/poll/polls_spec.rb, spec/features/admin/poll/questions_spec.rb
References
* Related issue: #2624
Objectives
* Move 'Show stats and results' form to `Admin::Poll#results` tab (commit [`f194e66`](https://github.com/AyuntamientoMadrid/consul/commit/f194e66972c739196af96d1737732333e193e003))
* Remove `video_url` attribute from `Admin::Poll::Question` form (commit [`37c1c62`](https://github.com/AyuntamientoMadrid/consul/commit/37c1c625683ea04153fe526297721d298361a307))
* Use 'drafting' as default value when creating a new budget (commit [`c63a671`](https://github.com/AyuntamientoMadrid/consul/commit/c63a67102797e8a69814735fc0110d478a4ab2cb))
* Use dropdown when selecting booth type instead of checkbox (commit [`c987e20`](https://github.com/AyuntamientoMadrid/consul/commit/c987e203e9e32b196763454611371101c83e6b39))
* …
=> Admin form improvements

app/views/custom/shared/_top_links.html.erb, app/views/layouts/_footer.html.erb, app/views/shared/_top_links.html.erb, config/locales/custom/en/general.yml, config/locales/custom/es/general.yml, config/locales/en/general.yml, config/locales/es/general.yml
Objectives
This PR moves the following custom i18n keys to custom yml files and remove it on non custom views.
```shell
open_data_text
open_data_title
participation_text
participation_title
transparency_text
transparency_title
transparency_url
external_link_blog
external_link_opendata
external_link_opendata_url
external_link_transparency
external_link_transparency_url
forums
help_translate
help_translate_info
```
Notes
=> i18n clean

Dockerfile
References
==========
**Related issue:** https://github.com/consul/consul/issues/2612
Objectives
==========
Add imagemagick package to the Docker configuration so that it's installed along with the others when Docker is configured. It is needed to upload images in the app.
There aren't visual changes itself, but I added some GIFs to see how it works.
Notes
As a side note, I was able to make it work ONLY after deleting the Docker cache. When I first set up Docker, the ImageMagick package wasn't included (I was just trying that everything was working on muy computer) and, for some reason, when I included it and rebuild everything, it was not taking into account the changes I made in the package installation instruction, …
=> Add Imagemagick to Docker configuration

app/controllers/admin/system_emails_controller.rb, app/models/notification.rb, lib/email_digest.rb, spec/features/emails_spec.rb, spec/features/notifications_spec.rb, spec/lib/email_digests_spec.rb
References
Closes #1494 
Objectives
- Send proposal notifications in batches.
- Prevent sending the emails to invalid directions.
Thanks to @voodoorai2000 for helping me with the batches tests ✨
=> Send proposal notifications in batches

app/models/proposal_notification.rb, spec/features/admin/proposal_notifications_spec.rb
References
This is a fix for an already merged PR.
**ISSUE**: https://github.com/consul/consul/issues/2618
**Related PR**: https://github.com/AyuntamientoMadrid/consul/pull/1489
Objectives
As @voodoorai2000 pointed out, the restore feature was not working properly. When pushed, the button was removing the notification from the admin's panel, but it was not appearing in the proposal.
I added an [`after_restore` function](https://github.com/AyuntamientoMadrid/consul/compare/master...wairbut-m2c-aytomadrid:2618-fix-allow-author-notifications-to-be-moderated#diff-9c28e8cb3083639c4df1c70cfe05f838R67) (that I missed in the first PR) so that the notification is unmarked as moderated. I also included a new …
=> Fix - Allow author notifications to be moderated

config/locales/custom/en/admin.yml, config/locales/custom/es/admin.yml, config/locales/en/admin.yml, config/locales/es/admin.yml
References
==========
* Related issue: #1129
* Related PR: #1273
Objectives
==========
* Moves custom :gb: / :es: I18n strings located in `config/locales` folder structure to `config/loclales/custom`
None
Notes
This is an ongoing effort to move all custom I18n strings located in `config/locales` to their proper folders/files, so several PRs are needed in order to achieve this. Small PRs are being done from time to time to make the review process easier and to avoid possible conflicts
=> Move custom Admin I18n strings to `locales/custom` folder

app/controllers/admin/poll/questions_controller.rb, app/models/poll.rb, spec/features/budget_polls/questions_spec.rb, spec/models/poll/poll_spec.rb
References
*Issue:* https://github.com/consul/consul/issues/2639
What
Do not display polls associated to a budget in admin poll questions 
Why
The `admin/questions` section is used to select to which poll a question belongs to
Budget polls are not meant to include questions that come from Citizen
Proposals or Government Questions, thus we do not display them
Visual Changes
**Before** (displaying a poll associated to a budget)
**After** (not displaying a poll associated to a budget)
Notes
None
=> Do not display polls associated to a budget in admin poll questions

app/controllers/admin/poll/polls_controller.rb, app/controllers/polls_controller.rb, spec/features/budget_polls/polls_spec.rb
References
Related issue consul#2639
Objectives
Hide from public polls list (`/polls`) and admin (`admin/polls`) those polls associated to a budget.
=> Hide budget polls

app/views/admin/budgets/index.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/budgets_spec.rb, spec/features/budget_polls/budgets_spec.rb
References
Related issue https://github.com/consul/consul/issues/2639
Objectives
In the admin budgets index (`/admin/budgets`) added link on every budget that has a poll associated to access the poll ballots.
Visual Changes
=> Adds "Admin ballots" button in admin budgets index

app/controllers/admin/poll/polls_controller.rb, app/helpers/officers_helper.rb, app/models/poll.rb, app/views/admin/budgets/index.html.erb, app/views/admin/poll/booth_assignments/index.html.erb, app/views/admin/poll/polls/_subnav.html.erb, app/views/admin/poll/recounts/index.html.erb, app/views/officing/_menu.html.erb, spec/features/budget_polls/budgets_spec.rb
Objectives
- Hides question menu on budget poll and changes redirect when creating (redirects to booths tab).
- Hides total final and total recount cells on budget poll recounts.
- Fixes manage assignments button overlapping.
- Hides recount menu if an officer has no shift assigned.
=> UI changes budget ballots

app/views/officing/voters/new.html.erb, config/locales/en/officing.yml, config/locales/es/officing.yml
Objectives
Adds button link to officing index on `/officing/voters/new?id=N` if person decided not to vote.
Visual Changes
Notes
=> Officing not to vote

app/helpers/officers_helper.rb, app/views/officing/dashboard/index.html.erb, app/views/officing/voters/create.js.erb, app/views/officing/voters/new.html.erb, spec/features/budget_polls/officing_spec.rb, spec/features/polls/voter_spec.rb
Objectives
- Hides sidebar menu if the officer has no shifts only shows the menu of the assigned shifts (validate votes or recount & results)
- Shows message on the index if the officer has no shifts.
- Hides not to vote at this time button if already voted.
Visual Changes
Notes
=> Officing voters

app/assets/stylesheets/admin.scss, app/views/admin/shared/_admin_shortcuts.html.erb, app/views/layouts/_notification_item.html.erb
References
Related Issue: https://github.com/consul/consul/issues/2682
Objectives
Fixes admin menu toggle (the title was overlapping the toggle menu and was impossible to use).
Also hides icons on the mobile version and includes text to settings and stats links.
Visual Changes
**Desktop (same as before)**
**Mobile (fixed!)** 🎉 
Notes
=> Fixes admin menu toggle

app/views/welcome/_card.html.erb, app/views/welcome/_cards.html.erb
Objectives
Adds `data-equalizer` to fix height on homepage cards.
Visual Changes
**Without data equalizer some cards shows in a different row**
**Fix with data equalizer**
Notes
=> Homepage cards

app/assets/stylesheets/legislation_process.scss, app/views/legislation/annotations/index.html.erb, app/views/legislation/annotations/show.html.erb, app/views/legislation/draft_versions/changes.html.erb, app/views/legislation/draft_versions/show.html.erb, app/views/legislation/processes/_help_gif.html.erb, app/views/pages/processes/open_government/doc.html.erb
Objectives
Adds help gif on legislation processes with texts.
Visual Changes
Notes
We have to make this gif translatable before backport to CONSUL.
=> Legislation help gif

app/views/custom/layouts/_admin_header.html.erb, app/views/custom/shared/_admin_login_items.html.erb, spec/features/budget_polls/officing_spec.rb, spec/features/officing/results_spec.rb
References
**Issue:** https://github.com/consul/consul/issues/2639
Context
===
Sometimes officers get confused and click a link that takes them away from the voting pages
What
===
- Remove logo from the officing section
- Remove link to officing in the header
Visual Changes
Before:
After:
Notes
===
None
=> Simplify officing layout

app/views/moderation/comments/index.html.erb, app/views/moderation/debates/index.html.erb, app/views/moderation/proposal_notifications/index.html.erb, app/views/moderation/proposals/index.html.erb
References
No related issues or pull requests
Objectives
* Correct entries information and filter positioning for all `moderation#index` views, similar to what was done in #1415
* Add missing `thead` and `tbody` tags
Visual Changes
**Note**: For brevity, and since the proposed changes are all the same, only one pair of `before/after` screenshots will be included
Notes
* Backport to CONSUL once approved and merged into `master`
=> Fix moderation index views information positioning

app/views/officing/_menu.html.erb, app/views/officing/voters/create.js.erb, spec/features/budget_polls/voter_spec.rb
References
===
**Issue:** https://github.com/consul/consul/issues/2639
Context
===
We are trying to avoid Officers from forgetting to click the “Confirm vote” button, which is necessary to keep track of who has voted a Poll
What
===
- Hide the menu item 'Validate document' by default in the voting page
- Once the Officer clicks the “Confirm Vote” display it again
- If there are no votable polls, display the menu item
Visual Changes
Notes
Due to mobile version we have duplicate ids for menu items, so using classes for the menu items to hide them correctly
Maybe a custom layout for this page, without menu items, and instead buttons for the next actions, would be more appropriate, we'll explore the idea 😌
=> Display 'Validate document' menu item only when applicable

app/views/admin/budget_investments/index.html.erb, app/views/custom/admin/budget_investments/index.html.erb, spec/features/admin/budget_investments_spec.rb
References
Related issue #1541 
Objectives
- Only show button for finished budgets.
- Use visited budget to form URL instead of the `current_budget` one.
=> Show 'see results' button only for finished budgets

app/models/abilities/administrator.rb, app/models/abilities/everyone.rb, app/models/budget/stats.rb, app/views/budgets/stats/show.html.erb, config/locales/custom/en/budgets.yml, config/locales/custom/es/budgets.yml, spec/features/budgets/stats_spec.rb, spec/models/budget/stats_spec.rb
References
Related issue: #1547 
Related issue: #1548 
Objectives
This PR achieves the issues above.
- Normal users can see a budget stats in its "finished" phase, and admins in "reviewing_ballots" and "finished" phases.
- Added new stats data related to participation in the vote phase in web and booths.
=> Public budget stats permissions and new stats data

config/locales/custom/en/budgets.yml, config/locales/custom/es/budgets.yml, spec/features/admin/budget_investments_spec.rb
References
* **Related commits**: [`dc87b75`](https://github.com/AyuntamientoMadrid/consul/commit/dc87b75975cb789653149852e5ba0264ea7ca89d), [`41f66fa`](https://github.com/AyuntamientoMadrid/consul/commit/41f66fa2b608bc8f152ff9b42df6e51c70b2d382)
* **Related PR**: #1549
Objectives
* Fix Travis build by removing four (4) unused I18n keys and adding a missing factory to `admin/budget_investments:588`
Visual Changes
* None
Notes
* Backport to CONSUL if necessary
=> Fix Travis build

app/models/abilities/administrator.rb, app/models/abilities/everyone.rb, spec/features/budgets/results_spec.rb
References
Related issue https://github.com/AyuntamientoMadrid/consul/issues/1556
Objectives
Normal users can see budget results in its "finished" phase, and admins in both "reviewing_ballots" and "finished" phases.
=> Add permissions for admins and normal users to access budget results

app/models/budget/stats.rb, config/environments/preproduction.rb, config/environments/production.rb
What
Increase max cache size from 1MB to 2MB
Why
========
We have lots of votes in this edition of Participatory Budgets and the default cache size (1MB) is not enough to hold certain cache fragments
Notes
Execute `Budget::Stats.new(Budget.last).generate` in Preproduction environment, check out logs and make sure there are no messages on these lines: `Value for budgets_stats/3/voters/v8 over max size: 1048576 <= 1914924`
=> Increase max cache size to 2MB

app/models/poll.rb, spec/features/admin/poll/polls_spec.rb
References
Related issue #1559 
Objectives
Add the Sluggable concern to Poll model to generate a slug when the Poll is created or updated.
=> Adds Sluggable concern to Poll model

app/views/custom/budgets/index.html.erb, spec/features/budgets/budgets_spec.rb
What
===
Use seo-friendly url for budget results
Visual Changes
None
Notes
No backport needed yet, we are not using custom seo-friendly urls upstream yet
=> Display seo-friendly url for budget results

app/views/budgets/investments/_investment_show.html.erb, app/views/custom/budgets/investments/_investment_show.html.erb, config/locales/en/budgets.yml, config/locales/es/budgets.yml, spec/features/budgets/investments_spec.rb
Objectives
Adds message "Winning investment project" in budget investment show if the project is a winner.
Visual Changes
Notes
=> Budget investment winner project

app/controllers/debates_controller.rb, app/controllers/proposals_controller.rb, app/models/abilities/common.rb, app/models/abilities/everyone.rb, app/models/debate.rb, app/models/proposal.rb, app/views/custom/debates/index.html.erb, app/views/custom/proposals/index.html.erb, app/views/debates/index.html.erb, app/views/proposals/index.html.erb, app/views/shared/_recommended_index.html.erb, config/locales/en/general.yml, config/locales/en/settings.yml, config/locales/es/general.yml, config/routes/debate.rb, config/routes/proposal.rb, db/migrate/20180711224810_enable_recommendations_by_default.rb, db/schema.rb, lib/tasks/users.rake, spec/features/account_spec.rb, spec/features/debates_spec.rb, spec/features/proposals_spec.rb, spec/models/abilities/common_spec.rb
References
* **Related PR**: #1521
Objectives
Five (5) new changes are being introduced through this PR, which are:
* User settings for recommendations will be automatically disabled if recommendations are dismissed
on `debates#index` or `proposals#index`
* Recommendations are enabled by default for all users
* Fixed a bug where recommendations would show even if the settings were disabled
* Moved `disable_recommendations` permissions to `Abilities::Common` model
* Added rake task to enable recommendations to existing users
Visual Changes
None
Notes
* These changes will be included for the #1521 backport to CONSUL once approved and merged into `master`
Update
===
Remember to add the rake to the Notes section …
=> Adjustments for user recommendations

app/controllers/budgets/investments_controller.rb, app/models/budget.rb, spec/features/budgets/investments_spec.rb
References
Related issue #1570 
What
===========
In `/budgets/[:budget_id]/[:group_id]/[:heading_id]` show only those investments that won when the budget is finished ordered randomly.
=> Add logic to show only winner investments if budget is finished

app/models/proposal.rb, spec/features/proposals_spec.rb
References
**Issue: https://github.com/consul/consul/issues/2700**
What
===
Allow empty responsible names when skipping user verification
Why
===
We are getting a [validation error](https://github.com/consul/consul/blob/master/app/models/proposal.rb#L44) when creating proposals, which is not displayed correctly in the page, as this field is not present in the form, only in the [model](https://github.com/consul/consul/blob/master/app/models/proposal.rb#L220)
Visual Changes
None
Notes
None
=> Fix validation error when creating proposals without user verification

app/views/polls/show.html.erb, config/locales/en/general.yml, config/locales/es/general.yml, spec/features/polls/voter_spec.rb
Objectives
Hides token message temporally when a user select an answer on `polls/show`
Visual Changes
**Hides this message**
Notes
This is temporal doesn't need to backport.
=> Hides token message temporally

spec/features/budgets/investments_spec.rb, spec/features/tags/budget_investments_spec.rb
Objectives
Fixes budget investments specs:
- **Tags Categories Filter by category tags**
`spec/features/tags/budget_investments_spec.rb:306` 
- **Budget Investments Show Investment's price & cost explanation When investment with price is selected Price & explanation is shown when Budget is on published prices phase**
`/spec/features/budgets/investments_spec.rb:876`
These specs was failing in the **finished phase** because now we are only displaying winner projects in this phase. With this commits, all investments are marked as winners if budget finished so that they appear correctly.
🎉 
Notes
=> Fixes budget investments specs

app/assets/stylesheets/layout.scss
Objectives
This PR fixes word wrap on (long) document links.
Visual Changes
**BEFORE long links overlay sidebar**
**AFTER word wrap fixed for long links**
Notes
=> UI long links

app/helpers/user_segments_helper.rb, config/locales/en/admin.yml, config/locales/es/admin.yml, db/dev_seeds/newsletters.rb, lib/user_segments.rb, spec/factories.rb, spec/features/admin/admin_notifications_spec.rb, spec/features/admin/emails/newsletters_spec.rb, spec/lib/user_segments_spec.rb
Objectives
Allow sending newsletters to users of a specific geozone
Visual Changes
Added geozone segments
Notes
When backporting, think about a solution that does not require translating geozone names, as it's hard to [test](https://github.com/AyuntamientoMadrid/consul/compare/master...AyuntamientoMadrid:user_segments_for_geozones?expand=1#diff-e2806d59b4ed9091bc09a0652196a30dR163) for geozones that are not present in translations. And each fork would have to add this custom translations. It should be possible to reproduce this funcionality using the Geozones themselves instead of custom translations 😌
=> Add geozone segments for newsletters

app/views/custom/polls/_poll_group.html.erb, app/views/polls/_poll_group.html.erb, config/locales/en/general.yml, config/locales/es/general.yml, spec/features/polls/polls_spec.rb
Objectives
This PR adds a "status" icon on polls poll group to indicate to the user:
- If not logged in: "You must sign in or sign up to participate"
- If it's unverified: "You must verify your account to participate"
- If can't answer: "This poll is not available on your geozone"
- If already answer: "You already have participated in this poll"
Visual Changes
Notes
=> Icon status on polls

app/views/custom/polls/index.html.erb, config/locales/custom/en/custom.yml, config/locales/custom/es/custom.yml
Objectives
============
- Remove explicative content from the polls index page about the Muros polls.
Notes
============
There's no need to backport these changes to CONSUL.
=> Remove custom texts of Muros polls

app/assets/javascripts/globalize.js.coffee, app/controllers/admin/banners_controller.rb, app/controllers/admin/budget_investment_milestones_controller.rb, app/controllers/admin/site_customization/information_texts_controller.rb, app/controllers/concerns/translatable.rb, app/helpers/globalize_helper.rb, app/helpers/site_customization_helper.rb, app/views/admin/banners/_form.html.erb, app/views/admin/budget_investment_milestones/_form.html.erb, app/views/admin/site_customization/information_texts/_form.html.erb, spec/features/translations_spec.rb
References
- Changes initial implementation from PR https://github.com/AyuntamientoMadrid/consul/pull/1435
Objectives
2 reasons for this change:
1. Accommodate forms with nested resources. This is necessary for Collaborative Legislation (https://github.com/consul/consul/issues/2736), e.g. `/admin/legislation/processes/5/questions/1/edit`
2. Allow for a cleaner, regex-less implementation of this bug fix: https://github.com/AyuntamientoMadrid/consul/commit/25b5526e0412b63e0c46981891a66a7f1f5e89b2
I also think this represents a better separation of concerns. I see this as the client telling the server which translations the user wants to have, and the server can decide which attributes need to be updated *and* which translation records need to be …
=> Change Translatable implementation to accommodate new requirements

app/assets/javascripts/globalize.js.coffee, app/controllers/admin/banners_controller.rb, app/controllers/admin/budget_investment_milestones_controller.rb, app/controllers/admin/site_customization/information_texts_controller.rb, app/controllers/concerns/translatable.rb, app/helpers/globalize_helper.rb, app/helpers/site_customization_helper.rb, app/helpers/translatable_form_helper.rb, app/models/banner.rb, app/models/budget/investment/milestone.rb, app/views/admin/banners/_form.html.erb, app/views/admin/budget_investment_milestones/_form.html.erb, app/views/admin/shared/_globalize_locales.html.erb, app/views/admin/site_customization/information_texts/_form.html.erb, app/views/admin/site_customization/information_texts/_form_field.html.erb, app/views/admin/site_customization/information_texts/_globalize_locales.html.erb, app/views/budgets/investments/milestones/_milestone.html.erb, config/initializers/globalize.rb, db/dev_seeds/banners.rb, db/dev_seeds/budgets.rb, spec/features/translations_spec.rb
__NOTE:__ This PR includes commits from open PR https://github.com/AyuntamientoMadrid/consul/pull/1602. That PR should be merged first. See #1612 for explanation. All commits _after_ [571667c Refactor Translatable#translation_params to improve readability](https://github.com/AyuntamientoMadrid/consul/commit/571667c2d9e1f52098b00354b310d2a457ef86c8) are unique to this PR and should be reviewed.
Objectives
Includes various refactors to the code shared by all "translatable" admin-created resources. See commits:
https://github.com/AyuntamientoMadrid/consul/commit/f3e75b712fe89ecb87cce49320d0d30016f633d1 Extract translatable field logic to FormBuilder
f3e75b7 Extract translatable field logic to FormBuilder
e0cc7d8 Avoid duplicating list of locales
7d5dc4a Incorporate label …
=> Refactor code shared by admin-translatable resources

app/views/custom/legislation/processes/proposals.html.erb, app/views/custom/legislation/proposals/_form.html.erb, app/views/custom/legislation/proposals/show.html.erb, app/views/legislation/processes/_custom_results.html.erb, app/views/legislation/processes/proposals.html.erb, app/views/legislation/proposals/_form.html.erb
References
Related issue: https://github.com/AyuntamientoMadrid/consul/issues/1233
Objectives
This PR moves custom legislation processes content to the correct `custom` folders.
Also changes `@process.id` condition to `@process.title` to avoid **features/legislation/processes_spec.rb:237** failing randomly as referenced in https://github.com/AyuntamientoMadrid/consul/issues/1233.
Notes
Backport the first commit to CONSUL repo.
=> Custom legislation processes content

app/views/pages/plaza_espana/_preselection.html.erb, app/views/pages/plaza_espana/_stats.html.erb, app/views/pages/plaza_espana/_survey.html.erb, app/views/polls/stats_2018/_districts.html.erb, app/views/welcome/_cards.html.erb, db/dev_seeds/budgets.rb, db/dev_seeds/communities.rb, db/dev_seeds/legislation_processes.rb, db/dev_seeds/notifications.rb, db/dev_seeds/polls.rb, lib/tasks/budgets.rake, lib/tasks/polls.rake, lib/tasks/slugs.rake, lib/tasks/spending_proposals.rake, lib/tasks/users.rake, spec/features/admin/admin_notifications_spec.rb, spec/features/admin/emails/newsletters_spec.rb, spec/features/admin/signature_sheets_spec.rb, spec/features/admin/spending_proposals_spec.rb, spec/features/admin/stats_spec.rb
References
* None
Objectives
* As per [this section](http://guides.rubyonrails.org/v4.2/active_record_querying.html#retrieving-multiple-objects-in-batches) in the Ruby on Rails documentation, the usage of `.all.each` over an ActiveRecord model might exceed the amount of memory available if said model is associated with a table with a considerable amount of records. Thus, it has been replaced where possible with `.find_each`, which has considerable performance gains
Visual Changes
* None
Notes
* Backport to CONSUL once approved and merged into `master`
=> Replace `.all.each` with `.find_each` to reduce memory usage

lib/user_segments.rb, spec/lib/user_segments_spec.rb
References
* **Related issue**: #1479
Objectives
* Sort beta testers by their `created_at` attribute. This way emails will be sent in a predictable way, allowing easier debugging
Visual Changes
* None
Notes
* None
=> Sort beta testers by `created_at` attribute

spec/features/admin/budget_investments_spec.rb, spec/features/admin/legislation/processes_spec.rb, spec/features/comments/topics_spec.rb, spec/features/emails_spec.rb, spec/lib/census_caller_spec.rb, spec/shared/features/nested_documentable.rb, spec/shared/features/nested_imageable.rb, spec/shared/models/document_validations.rb
References
==========
* No issues or PRs related
Related links:
* [RSpec's new message expectation syntax](http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/)
* [RSpec Mocks docs](https://relishapp.com/rspec/rspec-mocks/docs/working-with-legacy-code/any-instance)
Objectives
==========
* Fixed example to properly test emails are being sent based on current user's locale
* Fixed RSpec's deprecation warnings for old `stub` syntax usage
* DRY several `features/emails` examples
* Refactored some tests to use the `.check` & `.uncheck` API to interact directly with the UI rather than with the DOM
* Fixed some `rubocop` warnings
* Disabled JS driver usage on some scenarios as they work without it
* Fixed typos
None
Notes …
=> Test suite maintenance

app/assets/javascripts/globalize.js.coffee, app/assets/javascripts/legislation_admin.js.coffee, app/assets/javascripts/markdown_editor.js.coffee, app/controllers/admin/legislation/draft_versions_controller.rb, app/controllers/admin/legislation/processes_controller.rb, app/controllers/admin/legislation/questions_controller.rb, app/controllers/concerns/translatable.rb, app/models/admin_notification.rb, app/models/legislation/draft_version.rb, app/models/legislation/process.rb, app/models/legislation/question.rb, app/models/legislation/question_option.rb, app/views/admin/legislation/draft_versions/_form.html.erb, app/views/admin/legislation/processes/_form.html.erb, app/views/admin/legislation/questions/_form.html.erb, app/views/admin/legislation/questions/_question_option_fields.html.erb, config/initializers/routes_hierarchy.rb, db/dev_seeds/legislation_processes.rb, db/migrate/20180801140800_add_collaborative_legislation_translations.rb, db/schema.rb, spec/features/admin/legislation/draft_versions_spec.rb, spec/features/admin/legislation/processes_spec.rb, spec/features/admin/legislation/questions_spec.rb, spec/models/legislation/draft_version_spec.rb, spec/shared/features/translatable.rb
**NOTE**: Continuing #1614 here since Marko isn't available anymore. Everything written here is copied from there. All credit to @mlovic.
* Implements issue: consul#2736
* Meta-issue: #1612
Allow Collaborative Legislation resources to exist in multiple languages. This applies to the following resources:
* Legislation Processes
- Questions
- Question Options
- Draft Versions
* Proposal categories aren't translated as part of this PR. There's another issue for that: consul#2874.
* As with the original Milestones PR, data migration is not implemented:
> At this moment, the migration that creates the milestones translations table is not migrating the existing data. If this is the desired behaviour, it's OK with it. If not, the migration should have the :migrate_data => true option, as seen in …
=> Make collaborative legislation translatable

app/assets/stylesheets/participation.scss, app/controllers/budgets/executions_controller.rb, app/views/budgets/index.html.erb, app/views/custom/budgets/index.html.erb, config/locales/en/budgets.yml, config/locales/es/budgets.yml, spec/features/budgets/executions_spec.rb
Objectives
Adds a link to milestones on budgets index page.
Visual Changes
Notes
Backport this PR to CONSUL repo (except custom commit) 🤓
=> Budget index milestones

app/helpers/budget_executions_helper.rb, app/views/budgets/executions/_image.html.erb, app/views/budgets/executions/_investments.html.erb, spec/features/budgets/executions_spec.rb
Objectives
Sometimes a budget investment has some milestones created on the same date and the image is not displayed correctly. Now always display the first image available for milestones.
Notes
Backport this PR to CONSUL.
=> Display first image available for milestones

app/helpers/budget_executions_helper.rb, app/models/budget/investment/milestone.rb, spec/features/budgets/executions_spec.rb
Objectives
Always display last milestones image. Also adds a second order to ensure the order to display milestones with same publication date is always the same
Notes
Backport this (with https://github.com/AyuntamientoMadrid/consul/issues/1634) to CONSUL repo.
=> Display last milestones image

app/controllers/officing/base_controller.rb, app/controllers/officing/booth_controller.rb, app/helpers/polls_helper.rb, app/models/budget/investment/milestone.rb, app/models/poll/officer.rb, spec/factories.rb, spec/features/admin/admin_notifications_spec.rb, spec/features/budget_polls/ballot_sheets_spec.rb, spec/features/budget_polls/voter_spec.rb, spec/features/legislation/processes_spec.rb, spec/features/officing/booth_spec.rb, spec/features/officing/residence_spec.rb, spec/features/officing/results_spec.rb, spec/features/officing_spec.rb, spec/features/polls/polls_spec.rb, spec/features/polls/voter_spec.rb, spec/models/budget/investment/milestone_spec.rb, spec/models/poll/officer_spec.rb, spec/spec_helper.rb
* Issue #1195
* Issue #1200
* Issue #1202
* Issue #1203
* Issue #1204
* Issue #1209
* Issue #1210
* [Travis job with ballot sheets failure](https://travis-ci.org/javierm/consul/jobs/422313699)
* [Travis job with milestones failure](https://travis-ci.org/AyuntamientoMadrid/consul/jobs/423718182)
* [Travis job before changing booth's code](https://travis-ci.org/javierm/consul/jobs/422575831) (note: the code in this build uses `Timecop` to force the date to be 01:00AM)
* [Travis job after changing booth's code](https://travis-ci.org/javierm/consul/jobs/422589692) (note: the code in this build uses `Timecop` to force the date to be 01:00AM)
* Pull Request consul#2712
We've been struggling with failing tests around midnight for a long time. Pull Request consul#2712 solved that problem for most …
=> Fix today's booths for officer (fixes time-related flaky specs)

.rubocop.yml
* Pull request #1644.
Add rules to rubocop in order to receive automatic feedback (when we start using Hound) and document code conventions so contributors can follow them.
Three rules have been added: add a newline character at the end of the file, don't add trailing whitespaces, and use `%w[]` for word arrays. We were already encouraging the first two and have recently agreed on the third one.
Backport to consul. Even if we don't use Hound there, it still can help contributors who use rubocop.
=> Update rubocop rules

app/assets/stylesheets/participation.scss
This PR improves styles to show budgets executions images.
With this changes, all images adapt better to avoid big stretch or squeeze on images. 
Yes. Backport this PR to CONSUL.
=> Budget executions images

app/controllers/admin/site_customization/pages_controller.rb, app/models/site_customization/page.rb, app/views/admin/site_customization/pages/_form.html.erb, app/views/admin/site_customization/pages/index.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, db/migrate/20180924071722_add_translate_pages.rb, db/schema.rb, spec/factories/administration.rb, spec/features/admin/site_customization/pages_spec.rb, spec/features/site_customization/custom_pages_spec.rb
* Pull Request consul#2913
* Issue consul#2741
Incorporate the upstream changes making custom pages translatable.
* <del>Depends on #1654, so merge #1654 before merging this one.</del> #1654 is already merged.
=> [Upstream] Update translatable custom pages

spec/shared/features/nested_imageable.rb
* Issue #1609
* [Travis build 10233, job 2](https://travis-ci.org/AyuntamientoMadrid/consul/jobs/421929893) reports a different failure because of the same issue
Fix the flaky specs that appeared in `spec/features/admin/feature_flags_spec.rb:60` ("Admin feature flags Enable a disabled feature") and `spec/features/tags/proposals_spec.rb:119` ("Tags Create with too many tags").
The feature flags spec fails when using the JavaScript driver, since accessing the features section requires an extra click when JavaScript is enabled (on the "features" tab).
The proposal tags spec also fails when using the JavaScript driver, since it loads CKEditor and replaces the textarea the spec searches for.
Usually these specs would use the Rack driver. However, there was a bug in another spec which caused …
=>  Fix flaky spec: Admin feature flags Enable a disabled feature 

app/assets/stylesheets/legislation_process.scss, app/views/legislation/processes/_key_dates.html.erb, app/views/legislation/processes/debate.html.erb
Fixes legislation processes key dates `is-active` class.
Before in debate or proposals phase didn't appear the active class:
Now on debate phase:
Now on proposals phase:
Yes, backport this to CONSUL repo.
=> Fixes legislation processes key dates active class

app/views/legislation/proposals/_categories.html.erb, config/locales/en/legislation.yml, config/locales/es/legislation.yml, spec/features/tags/custom/legislation/proposals_spec.rb
Related PR: https://github.com/AyuntamientoMadrid/consul/pull/1638/
After Add tag filtering for legislation proposals this PR removes unnecesary `genre:` i18n key.
Yes, backport the first commit. Also add the changes made on [`legislation/proposals/_categories.html.erb`](https://github.com/AyuntamientoMadrid/consul/commit/65341101a3bc3c4a81237223d84a02e74167bfa4#diff-2cd858e7850739b05fcfcfa44b925527R1)
=> Legislation proposals categories

app/models/image.rb
PR: https://github.com/consul/consul/pull/2966
Proper spelling for constant `TITLE_LENGTH_RANGE` to prevent misspelling if it is used in another context.
=> [Upstream] Fix TITLE_LENGTH_RANGE constant

spec/features/admin/legislation/questions_spec.rb
Fix flaky legislation question spec
* Issue #1603
Fix the flaky spec that appeared in `spec/features/admin/legislation/questions_spec.rb:86`   ("Admin legislation questions Update Valid legislation question").
As mentioned in the commit message:
> Right after clicking the "Collaborative Legislation" link, the link 'An example legislation process' is already available. So sometimes Capybara might click the links "All" and 'An example legislation process' at more or less the same time, causing the second link not to be correctly
clicked.
Making sure the "All" link doesn't exist anymore we guarantee Capybara will wait for the previous AJAX request to finish before clicking the next link.
* The test to "Create Valid legislation question" is almost identical but it doesn't fail because it …
=> Fix flaky spec: Admin legislation questions Update Valid legislation question 

app/assets/javascripts/custom/legislation_proposals.js.coffee, app/assets/stylesheets/custom.scss, app/assets/stylesheets/pages.scss, app/views/custom/legislation/proposals/_form.html.erb, app/views/legislation/proposals/_form.html.erb, app/views/legislation/proposals/_proposal.html.erb, app/views/legislation/proposals/show.html.erb, spec/features/legislation/proposals_spec.rb
Related PR https://github.com/consul/consul/pull/2922
This feature already exists on this fork, but now it's synced with changes made on CONSUL https://github.com/consul/consul/pull/2922. 
Moreover: 
- Refactors custom legislation proposals form (avoiding use js and failing spec).
- Removes duplicated custom CSS.
=> Legislation proposals imageable

db/migrate/20180323190027_add_translate_milestones.rb, db/migrate/20180718115545_create_i18n_content_translations.rb, db/migrate/20180727140800_add_banner_translations.rb, db/migrate/20180730120800_add_homepage_content_translations.rb, db/migrate/20180730213824_add_poll_translations.rb, db/migrate/20180731150800_add_admin_notification_translations.rb, db/migrate/20180731173147_add_poll_question_translations.rb, db/migrate/20180801114529_add_poll_question_answer_translations.rb, db/migrate/20180801140800_add_collaborative_legislation_translations.rb, db/migrate/20180924071722_add_translate_pages.rb, lib/tasks/globalize.rake, spec/lib/tasks/globalize_spec.rb
* Meta-issue #1612
We forgot to migrate existing data when we created the translations tables, and so when we edit translatable fields in the administration, they seem to be empty, increasing the risk of data loss.
Migrate existing data to the translation tables (unless we've already translated those records!) so contents show up when administrators edit contents.
Yes!
⚠️ **For release notes**:
In order to migrate existing data, execute:
`bin/rake globalize:migrate_data RAILS_ENV=production`
Although we believe it's completely safe to run this task, we recommend backing up the database before executing any task which modifies its data.
This task will not migrate records which contain invalid data (for example, a banner with a blank title), which might happen if the database content has …
=> Migrate translatable data

app/controllers/proposals_controller.rb, app/mailers/mailer.rb, app/models/newsletter.rb, app/views/mailer/newsletter.html.erb, config/locales/en/general.yml, config/locales/es/general.yml, config/routes/proposal.rb, db/migrate/20181022173839_add_newsletter_token_to_users.rb, db/schema.rb, lib/user_segments.rb, spec/features/vote_via_email_spec.rb, spec/models/newsletter_spec.rb
**PR**: https://github.com/AyuntamientoMadrid/consul/pull/261
- Add the top 5 proposals to the newsletter
- Add a show link to each of these proposals
- Add a vote link to each of these proposals
- Make sure to login users if they are not logged in when following these links
- This is a quick fix to send a marketing newsletter
- Do not backport to CONSUL 😌(this behaviour would be applied to all newsletters)
- Complete specs before deploying to production
- Revert PR once marketing campaign is over
=> Add voting links via get to newsletters 

config/locales/en/admin.yml, config/locales/es/admin.yml, lib/user_segments.rb, spec/lib/user_segments_spec.rb
Add a user segment with the users that did not receive the last newsletter
No backport needed, this is a hotfix
=> Adds segment for users that did not receive the last Newsletter

app/models/newsletter.rb
Newsletters emails are send in batches of 10.000 every 20.minutes
Speed up the delivery of newsletters, by increasing the number of emails send from 10.000 to 50.000
No, it's a temporary increase in speed for marketing reasons
=> Increase batch size for newsletters

lib/user_segments.rb
**PR**: https://github.com/AyuntamientoMadrid/consul/pull/1682
Optimize call to find users that have not received the newsletter
No, this is a hot fix
=> Optimize call to find pending users for newsletter

config/initializers/delayed_job_config.rb
Increase the max time an asincronous process can take from 8 hours to 25 hours
Yes, just in case other big cities run into the issue of sending huge newsletter that take many hours
=> Increase delayed jobs max run time

app/controllers/proposals_controller.rb, db/migrate/20181024160733_add_newsletter_token_used_at_to_users.rb, db/schema.rb, spec/features/vote_via_email_spec.rb
Some users are sharing in social networks the links that they have received in the newsletter
Remove the token after being used, so that other users cannot use it
No, this is only for the temporary feature in Madrid
=> Remove token after being used once

lib/user_segments.rb, spec/lib/user_segments_spec.rb
**PR**: https://github.com/AyuntamientoMadrid/consul/pull/1682
Update id of the last newsletter sent, to send a new newsletter to the pending users
Nop
=> Update id of last newsletter sent

app/views/admin/newsletters/show.html.erb, spec/features/admin/emails/newsletters_spec.rb
Add a counter to know how many newsletter emails have been sent already
Could be useful, but needs some cleaning up
=> Add counter of emails sent to newsletter preview

app/controllers/proposals_controller.rb, spec/features/vote_via_email_spec.rb, spec/support/common_actions/users.rb
- The show link with a token should not login users
- The vote link with a token should login users, vote, and logout
- Unverified users should not login with a token, as they cannot complete the vote task and then get logged out
- Remove the _delete token_ functionality as it conflicts with this new behaviour
No need
=> Update behaviour of newsletter links

spec/features/comments/legislation_questions_spec.rb, spec/features/comments/proposals_spec.rb, spec/features/comments/spending_proposals_spec.rb, spec/features/custom/probe_option_comments_spec.rb
* Issue #1605
* PR consul#2734
Fix the flaky specs that appeared in `spec/features/comments/proposals_spec.rb:463` ("Commenting proposals Voting comments Update"), `spec/features/comments/legislation_questions_spec.rb:498` and ("Commenting legislation questions Voting comments Update") and `spec/features/custom/probe_option_comments_spec.rb:466` ("Commenting Probe Options Voting comments Update").
As mentioned in consul#2734:
Here's the relevant part of the spec:
```ruby
visit debate_path(create(:debate))
find('.in-favor a').click
find('.against a').click
```
After clicking the first link, there's an AJAX request which replaces the existing .in-favor a and .against a links with new elements. So if Capybara tries to click the existing .against a link at the same moment it's being replaced, …
=> Fix flaky specs: proposals, legislation and probe options Voting comments Update

app/mailers/mailer.rb, app/models/newsletter.rb, app/views/admin/newsletters/show.html.erb, app/views/mailer/newsletter.html.erb, config/deploy.rb, config/initializers/delayed_job_config.rb, config/locales/en/admin.yml, config/locales/es/admin.yml, lib/user_segments.rb, spec/features/admin/emails/newsletters_spec.rb, spec/features/vote_via_email_spec.rb, spec/lib/user_segments_spec.rb, spec/models/newsletter_spec.rb, spec/support/common_actions/users.rb
* Pull requests #1680, #1682, #1683, #1684, #1685, #1687, #1688, #1689
* Commits b5b090e, fc726f1, cddbc86, dc1c276
In case you're wondering, 1681 isn't related, and 1686 and 1690 add code related to the proposals controller which should **not** be deleted yet.
* Remove the code used to generate a newsletter with links to vote the top proposals
* Group all changes which need backport in one pull request
Yes, but skip the first commit when doing so.
=> Remove code to generate a special newsletter

spec/features/admin/legislation/draft_versions_spec.rb
* Issue #1618
Fix the flaky specs that appeared in `spec/features/admin/draft_versions_spec:70` ("Admin legislation draft versions Update Valid legislation draft version").
Here's the relevant code:
```ruby
click_link "All"
expect(page).to have_content 'An example legislation process'
click_link 'An example legislation process'
```
These failures take place because the link to 'An example legislation process' is already present before clicking "All", and so Capybara doesn't have to wait for the "All" request to finish before clicking the link, as shown in this screenshot:
So sometimes Capybara tries to click 'An example legislation process' at the same time that link is being replaced by the new content, resulting in no request being sent to the server. Here's the screenshot when the test …
=> Fix flaky spec: Admin legislation draft versions Update Valid legislation draft version

app/views/admin/budgets/index.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/budgets_spec.rb
This PR improves message when there are no budgets adding consistency with the rest of Admin panel sections.
**BEFORE**
**AFTER**
=> Budgets admin

spec/features/admin/budget_investments_spec.rb
* Issue #1194 
* PR #1256 
* [Recent travis build with the failure](https://travis-ci.org/javierv/consul/jobs/400699160)
Fix the flaky specs that appeared in `spec/features/admin/budget_investments_spec:1200` ("Admin budget investments Mark as visible to valuators Mark as visible to valuator") and  `spec/features/admin/budget_investments_spec:1243` ("Admin budget investments Mark as visible to valuators Unmark as visible to valuator")
As mentioned in the comments in PR #1256:
> "These failures take place because the checkbox is already present before clicking in 'under valuation', and so Capybara doesn't have to wait for the 'under valuation' request to finish before clicking the checkbox."
So sometimes Capybara tries to check/uncheck the checkbox at the same time that checkbox is being …
=> Fix flaky spec: Admin budget investment mark/unmark visible to valuators

app/helpers/admin_helper.rb, app/helpers/budgets_helper.rb, spec/features/admin/homepage/homepage_spec.rb
Related Issue: https://github.com/consul/consul/issues/2997
This PR fixes admin menu link when create a new widget avoiding the 404 error when clic on admin menu from `/admin/widget/cards/new`.
Now the header link redirects correctly to `admin/homepage`.
=> Admin menu link

app/helpers/legislation_helper.rb, spec/features/legislation/processes_spec.rb
This PR fixes date format on legislation helper.
Changing `format: "%d %h %Y"` to `format: "%d %b %Y")`
Before _key dates_ were shown always on `en` format:
With this changes when the locale is `es` displays dates correctly:
Backport this changes to CONSUL repo.
On [apidock strftime docs](https://apidock.com/ruby/DateTime/strftime) it seems `%h` is equivalent to `%b` but the first option doesn't work correctly when change locale because [I18n translates %b but not %h](https://github.com/svenfuchs/i18n/blob/master/lib/i18n/backend/base.rb#L249).
=> Legislation dates

app/views/debates/new.html.erb, app/views/pages/help/how_to_use/index.html.erb, app/views/welcome/welcome.html.erb, db/dev_seeds/widgets.rb
There is some `help_path` links by default on the code. Whit this PR these links only shows if feature `:help_page` is enabled.
Also updates link url on dev seed widgets because `help_path` was generating a nonexistent  url `https://localhost:3000/help_path`.
=> Help feature

app/views/budgets/investments/_investment_show.html.erb, spec/features/budgets/investments_spec.rb
This PR:
- Removes unnecessary condition when display unselected message. 
- Adds spec when no message is displayed. Should show only "Investment project" label.
Backport to CONSUL repo.
=> Budget investment show

app/models/legislation/process.rb
Updates `max_documents_allowed` number to legislation process. 
These documents are uploaded only by admin users, and in this fork some legislation processes needs 4 documents instead of 3.
=> Legislation process documents

lib/tasks/migrate_milestones_and_statuses.rake, spec/lib/tasks/milestones_spec.rb
* Pull requext #1698
* Issue consul#2763
When we insert a record in PostgreSQL and we specify the ID, the internal ID sequence for that table isn't updated.
In order to keep the original IDs so we didn't break any foreign keys, in pull request #1698 we specified the IDs when copying the table, resulting in a table having its ID sequence with a value of an existing record. When trying to insert a new record, we got a `PG::UniqueViolation` exception.
Avoid duplicated primary key errors after migration milestones data.
Yes.
* Updating the sequence after the data migration might not be the most elegant solution, but it's easy to do and it's already been tested on a production environment.
=> Fix milestones IDs migration

app/assets/stylesheets/layout.scss, app/views/admin/shared/_common_globalize_locales.html.erb
Fixes globalize tabs when there is a lot of available locales. Now "Remove language" link is not floating preventing break the layout.
**BEFORE**
**AFTER**
Backport to CONSUL repo.
=> Globalize tabs

app/views/budgets/investments/_investment_show.html.erb, config/locales/en/budgets.yml, config/locales/es/budgets.yml
Improves social share message to budget investments.
**BEFORE**
**AFTER**
Backport to CONSUL repo.
=> Budget investments social share

app/views/admin/administrators/index.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/administrators_spec.rb
- Adds **Administrator ID** on admin administrators index page.
- Refactors admin administrators spec: this refactoring avoids "Use let instead of an instance variable" rubocop warning. 😌 
This is useful for example to identify an admin comment by their id:
=> Administrator ID

spec/lib/tasks/milestones_spec.rb
* Pull request #1698
Fix a test which was failing depending on the time zone of the machine where it was being executed.
Yes.
=> Use `Date.current` instead of `Date.today`

spec/features/home_spec.rb, spec/features/polls/nvotes_spec.rb, spec/features/polls/voter_spec.rb, spec/features/representatives_spec.rb, spec/spec_helper.rb
* Issue #1623
Fix the flaky specs that appeared in `spec/features/welcome_spec.rb:41` ("Welcome screen is not shown to organizations").
The test failed if the previous test had set `session["user_return_to"]` and hadn't deleted the cookie. In those situations, the expectation of being redirected to the `root_path` fails.
This scenario took place when the previous test was one of the represetatives tests using `page.driver.post` or `page.driver.delete`. These methods set cookies in the driver and those cookies aren't cleared by executing `Capybara.reset_sessions!`.
Resetting the driver after every feature spec solves the problem.
* Even though this specific issue doesn't affect the main CONSUL repository (no representatives spec there), I'd backport this PR anyway, since it offers a …
=> Fix flaky spec: Welcome screen is not shown to organizations 

app/models/milestone.rb, app/models/milestone/translation.rb, spec/models/milestone_spec.rb, spec/shared/features/admin_milestoneable.rb
* Pull request #1435
* Pull request #1669
We've got a validation rule which says a milestone must have either a status or a description.
After making the description translatable, the error wasn't being displayed correctly in the admin form.
Make the admin form display a validation error when both description and status are blank.
Yes.
=> Fix milestone validation

app/views/admin/legislation/milestones/_summary_form.html.erb, app/views/admin/shared/_common_globalize_locales.html.erb, app/views/admin/shared/_globalize_tabs.html.erb, spec/features/admin/legislation/processes_spec.rb
* Pull request #1717
Avoid validation errors when trying to add a new language for the milestones summary form. Languages should be added from the "infomation" form, and thie milestones summary form should be used to edit existing languages.
Yes.
=> Edit only existing languages in milestones summary

app/models/newsletter.rb, spec/models/newsletter_spec.rb
We have seen a problem if the delayed_job that is processing the newsletter stops, for some reason, and is restarted. In that case the newsletter email was being send twice to the same users.
With this PR we are checking if the user has already received the newsletter and in that case we skip the delivery.
Yes, this will be useful in CONSUL
=> Check recipient of newsletter before resending

spec/features/proposal_notifications_spec.rb
https://github.com/consul/consul/pull/3066
=> [Upstream] Add missing feature spec: Proposal Notifications In-app notifications from the proposal's author group notifications for the same proposal

app/controllers/legislation/processes_controller.rb, spec/features/custom/legislation/proposals_spec.rb, spec/features/legislation/proposals_spec.rb
* Issue #1659
* Pull request consul#3076
* Some of the refactoring done here is related to consul#2155
Fix the flaky specs that appeared in `spec/features/legislation/proposals_spec.rb:30` ("Legislation Proposals Each user as a different and consistent random proposals order").
This test could fail for at least two reasons:
1. We were using two random numbers between 1 and 100 and then we were checking they produced different results. It looks like these numbers weren't random enough and sometimes they generated the same results.
2. <del>The way we were using `setseed`, combined with the way Rails caches SQL results and maybe more unknown factors, sometimes generated different records in what seemed to be the same SQL query with the same seed.</del> UPDATE: as stated on consul#3076, it …
=> Fix flaky spec: Legislation Proposals Each user has a different and consistent random proposals order

app/controllers/admin/site_customization/documents_controller.rb, app/helpers/admin_helper.rb, app/models/document.rb, app/views/admin/_menu.html.erb, app/views/admin/site_customization/documents/index.html.erb, app/views/admin/site_customization/documents/new.html.erb, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/es/activerecord.yml, config/locales/es/admin.yml, config/routes/admin.rb, db/migrate/20181128175808_add_admin_to_documents.rb, db/schema.rb, spec/factories/files.rb, spec/features/admin/site_customization/documents_spec.rb, spec/models/document_spec.rb
References
**Issue:** https://github.com/consul/consul/issues/3009
Objectives
Allow admins to upload documents and later link them from anywhere in the site.
Visual Changes
Backport Needed
===
Yes, this will be useful in CONSUL
=> Add document uploads from admin section

app/models/budget/reclassification.rb
PR https://github.com/consul/consul/pull/3067
=> [Upstream] Fix failing spec: Budget::Investment Reclassification store_reclassified_votes stores the votes for a reclassified investment

spec/features/localization_spec.rb
* Issue #1630
Fix the flaky specs that appeared in `spec/features/localization_spec.rb:34` ("Localization Changing the locale") and `spec/features/localization_spec.rb:20` ("Localization Available locales appear in the locale switcher").
These specs fail when executed after `spec/customization_engine_spec.rb:19` and `spec/features/localization_spec.rb:44`, causing the following sequence:
1. The first test executes `I18n.reload!`, which causes `I18n.config.backend` to set `@translations = nil`.
2. The second test stubs `available_locales` to `[:en]`, causing `@translations` to get only translations for `:en`.
3. The third test doesn't find translations for Spanish because `@translations` only has the English ones, and fails.
Reloading `I18n` after the test stubbing `available_locales` …
=> Fix flaky localization specs

db/dev_seeds/widgets.rb
Objectives
Updates deprecated constants on **dev_seed/widgets**. This change avoid warning message when run `rake db:dev_seed`
```console
Creating header and cards for the homepage
/app/db/dev_seeds/widgets.rb:25: warning: constant ::TRUE is deprecated
/app/db/dev_seeds/widgets.rb:43: warning: constant ::FALSE is deprecated
/app/db/dev_seeds/widgets.rb:61: warning: constant ::FALSE is deprecated
/app/db/dev_seeds/widgets.rb:79: warning: constant ::FALSE is deprecated
```
Notes
[Ruby 2.4 has deprecated toplevel constants TRUE, FALSE and NIL](https://blog.bigbinary.com/2017/06/19/ruby-2-4-has-depecated-constants-true-false-and-nil.html)
Backport
Backport this to CONSUL.
=> Widgets dev seeds 

app/models/debate.rb, app/models/legislation/proposal.rb, app/models/proposal.rb, config/locales/en/settings.yml, config/locales/es/general.yml, config/locales/es/settings.yml, db/dev_seeds/settings.rb, db/seeds.rb, lib/score_calculator.rb, lib/tasks/settings.rake, lib/tasks/votes.rake, spec/models/debate_spec.rb, spec/models/legislation/proposal_spec.rb, spec/models/proposal_spec.rb
With the new algorithm that calculates the `hot_score` we try to prioritize the Debates/Proposals that has received more positive votes per day within the recent period. This period is configurable in settings and is set to 1 month/31 days by default.
It will also have in consideration the negative votes (if applicable), so a Debate with same positive votes and less negative votes will have higher score.
Yes
⚠️ For Release Notes:
A new Admin Setting has been added, execute the following rake task to add the Admin Setting to your existing DB. 
```
bin/rake settings:create_hot_score_period_setting RAILS_ENV=production
```
And the following rake task to recalculate the `hot_score` for all resources.
```
bin/rake votes:reset_hot_score RAILS_ENV=production
```
=> New algorithm for filter 'most active'

app/models/legislation/process.rb, spec/models/legislation/process_spec.rb
Previous PR: https://github.com/AyuntamientoMadrid/consul/pull/1741/
Hides process on index if draft dates match with date current. Before, on `scope :not_in_draft` if the `draft_start_date` or `draft_end_date` was matching with `Date.current` the process was showing on processes index page. We want to hide all processes with active draft phase.
=> Draft phase on legislation processes

app/controllers/proposals_controller.rb, app/models/abilities/common.rb, config/routes/proposal.rb, spec/features/vote_via_email_spec.rb
* Pull request #1690
After voting following a link with a token, we're signing out users in order to avoid anyone clicking the link to get control of a user's account. However, we're also signing out already signed in users.
* Don't sign out users after voting if they were already signed in
* Use different actions for `get` and `post` verbs
* Avoid issues with underaged users trying to vote a proposal
* Remove hound warnings in the specs
=> Clean up newsletter votes code

spec/features/budgets/investments_spec.rb
``` bash
bin/rspec --seed 53044
Failures:
1) Budget Investments Balloting Phase Confirm
Failure/Error: expect(page).not_to have_content "#{sp3.price}"
expected not to find text "100" in "Global Group - Global Heading You still have €999,989 to invest. Amount spent €11 Budget Investment 1006 title €10 Budget Investment 1005 title €1"
Failed examples:
rspec ./spec/features/budgets/investments_spec.rb:1419 # Budget Investments Balloting Phase Confirm
```
When we check the price not to appear we don't include the currency symbol, so if the number is anywhere else the test will fail.
We will check the number doesn't appear, but with the currency symbol.
Yes
=> Fix flaky spec checking price without currency symbol

.rubocop.yml, .rubocop_basic.yml, spec/features/admin/poll/questions/answers/images/images_spec.rb, spec/features/admin/valuator_groups_spec.rb, spec/features/budget_polls/officing_spec.rb, spec/features/budget_polls/questions_spec.rb, spec/features/budget_polls/voter_spec.rb, spec/features/budgets/budgets_spec.rb, spec/features/budgets/investments_spec.rb, spec/features/budgets/results_spec.rb, spec/features/debates_spec.rb, spec/features/legislation/processes_spec.rb, spec/features/notifications_spec.rb, spec/features/proposals_spec.rb, spec/features/users_auth_spec.rb, spec/features/vote_via_email_spec.rb, spec/lib/user_segments_spec.rb, spec/models/budget/investment_spec.rb, spec/models/notification_spec.rb, spec/models/poll/poll_spec.rb, spec/models/valuator_spec.rb, spec/support/common_actions/users.rb
**PR:** https://github.com/consul/consul/pull/3112
Change RSpec references of `to_not` for `not_to` and add the [corresponding Rubocop rule](https://www.rubydoc.info/gems/rubocop-rspec/1.5.0/RuboCop/Cop/RSpec/NotToNot).
Nop, this comes from Upstream
=> [Upstream] Add not_to Rubocop rule

.rubocop_basic.yml
Help developers who don't run the ruby syntax check locally realize they might be involuntarily assigning a value to a local variable which is never used, and so they might want to check whether they need to refactor the code a bit.
Yes.
=> Enable useless assignment rubocop rule

app/views/budgets/investments/_investment_show.html.erb, config/locales/en/budgets.yml, config/locales/es/budgets.yml, spec/features/budgets/investments_spec.rb
> Related Issues/Pull Requests/Travis Builds/Rollbar errors/etc...
If budget investment have a price explanation shows "See price explanation" link after the price with an anchor link to Price explanation section.
I used [Foundation Magellan](https://foundation.zurb.com/sites/docs/magellan.html) for an awesome smooth scroll.
Backport this to CONSUL.
=> Budget investments price explanation

app/assets/stylesheets/layout.scss, app/controllers/admin/budget_headings_controller.rb, app/controllers/budgets/investments_controller.rb, app/models/budget/heading.rb, app/views/admin/budgets/_heading_form.html.erb, app/views/budgets/index.html.erb, app/views/budgets/investments/_map.html.erb, app/views/budgets/investments/_sidebar.html.erb, config/locales/en/admin.yml, config/routes/budget.rb, db/dev_seeds/budgets.rb, db/migrate/20181109111037_add_location_to_headings.rb, db/schema.rb, lib/migrate_spending_proposals_to_investments.rb, spec/factories/budgets.rb, spec/features/admin/budgets_spec.rb, spec/features/budgets/investments_spec.rb, spec/features/tags/budget_investments_spec.rb, spec/models/budget/heading_spec.rb
PR https://github.com/consul/consul/pull/3038
Objectives
> Add a map at the sidebar, on Heading's page. In order to visualize the investiments related to a heading.
Visual Changes
> On administration section, when editing a heading, now there are two fields related to the coordinates of the heading. Coordinates indicating where the map will be centered on..
=> [Upstream] Add map to sidebar on Heading's page

app/views/admin/poll/questions/_questions.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/poll/questions_spec.rb
Adds poll name on admin poll questions index. 
=> Admin poll questions index

.rubocop_basic.yml, app/models/budget/investment.rb
* Remove a syntax mistake which made a condition always evaluate to `true`
* Enable a rubocop rule so we are warned when we accidentally introduce similar conditions
Yes.
=> Fix literal as condition

app/controllers/users/registrations_controller.rb, app/views/users/registrations/new.html.erb, spec/features/registration_form_spec.rb
Changes honeypot `:family_name` to `:address` on users sign up form. This prevent a real user fill this honeypot hidden field when use "autofill" browser feature. 
We use `HTML <input> autocomplete = "off"` in some fields in this form (honeypot included) but it seems new browsers are ignoring this value.
_The honeypot field is hidden but I change styles to show it and view the changes_
**BEFORE**
**AFTER**
Some info about HTML <input> autocomplete = "off":
[HTML <input> autocomplete Attribute](https://www.w3schools.com/tags/att_input_autocomplete.asp)
[AutoComplete=Off” not working on Google Chrome Browser](https://stackoverflow.com/questions/18306052/autocomplete-off-not-working-on-google-chrome-browser)
[Chrome ignores …
=> Honeypot on users sign up form

app/views/documents/_documents.html.erb, spec/shared/features/documentable.rb
Shows documents title only if there is any document.
**BEFORE**
**AFTER**
_With documents the title shows as before_
=> Documents title

app/controllers/management/budgets/investments_controller.rb, spec/features/management/budget_investments_spec.rb, spec/shared/features/mappable.rb
From the management console `/management/budgets/create_investments` it´s not possible to create a Budget Investment without a map location. 
Should be possible by checking the option "This investment doesn't have a concrete location or I'm not aware of it." 
Yes
=> [Bug] [Management] Cannot create Budget Investment without map location

app/controllers/admin/legislation/homepages_controller.rb, app/controllers/legislation/processes_controller.rb, app/helpers/legislation_helper.rb, app/models/legislation/process.rb, app/views/admin/legislation/homepages/_form.html.erb, app/views/admin/legislation/homepages/edit.html.erb, app/views/legislation/processes/show.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, config/routes/admin.rb, db/migrate/20181206153510_add_home_page_to_legislation_processes.rb, db/schema.rb, spec/features/legislation/processes_spec.rb
**PR:** https://github.com/consul/consul/pull/3091
Objectives
> Added new tab in admin section for legislative processes, to enable a default homepage for each process
Visual Changes
> Admin:
> Front:
No, this PR comes from Upstream
=> [Upstream] Add legislation homepage

app/controllers/valuation/budgets_controller.rb, app/views/valuation/budgets/index.html.erb, config/locales/en/valuation.yml, config/locales/es/valuation.yml, spec/features/valuation/budgets_spec.rb
* Brings pull request consul#3128 to Madrid
* The code is different because we haven't backported #1359 yet
Fix a crash in the valuation section when there are no budgets.
=> [Upstream] Fix crash in valuation when there are no budgets 

.rubocop_basic.yml
Make the `EnforncedStyle: rails` defined in `Layout/IndentationConsistency` work properly.
Yes.
=> Add rubocop rule to indent private methods

app/assets/stylesheets/legislation_process.scss, app/models/legislation/process.rb, app/views/admin/legislation/homepages/_form.html.erb, app/views/legislation/processes/_key_dates.html.erb, config/locales/en/legislation.yml, config/locales/es-AR/legislation.yml, config/locales/es-BO/legislation.yml, config/locales/es-CL/legislation.yml, config/locales/es-CO/legislation.yml, config/locales/es-CR/legislation.yml, config/locales/es-DO/legislation.yml, config/locales/es-EC/legislation.yml, config/locales/es-GT/legislation.yml, config/locales/es-HN/legislation.yml, config/locales/es-MX/legislation.yml, config/locales/es-NI/legislation.yml, config/locales/es-PA/legislation.yml, config/locales/es-PE/legislation.yml, config/locales/es-PR/legislation.yml, config/locales/es-PY/legislation.yml, config/locales/es-SV/legislation.yml, config/locales/es-UY/legislation.yml, config/locales/es-VE/legislation.yml, config/locales/es/legislation.yml, spec/factories/legislations.rb, spec/features/legislation/processes_spec.rb
Previous PR: https://github.com/AyuntamientoMadrid/consul/pull/1767
To improve UX, this PR changes styles (to tabs style) on processes key dates.
**Before** _(some users didn't understand the key dates was links)_ 
**After** _(the new style as tabs it's easier to understand)_
**Mobile version**
Backport to CONSUL repo.
=> Processes key dates

app/assets/stylesheets/legislation_process.scss
Removes arrow icon on `is-active` process phase.
**BEFORE**
**AFTER**
=> Removes arrow icon on active process phase

spec/features/custom/probe_option_comments_spec.rb
* [Travis build 10666, job 5](https://travis-ci.org/AyuntamientoMadrid/consul/jobs/469944587)
Fix a test which was using the probe id instead of the probe option id as the URL param to visit a probe option, causing the test `Commenting Probe Options Flagging turbolinks sanity check` to fail sometimes.
No, probe options don't exist in CONSUL.
=> Fix typo in probe option specs

lib/migrations/legacy_legislation/annotation.rb, lib/tasks/legacy_legislation.rake, spec/lib/migrations/legacy_legislation/annotation_spec.rb
Migrate the old annotations in `Annotation` to the new class `Legislation::Annotation`
**BEFORE**
**AFTER**
NO
To migrate the legislation processes run this rake task:
`bin/rake legacy_legislation:migrate_annotations RAILS_ENV=production`
=> LegacyLegislation processes annotations migration (second phase)

app/models/budget/investment.rb, spec/features/admin/budget_investments_spec.rb
Make the tab "without valuator" really mean "without valuator nor valuator group", just as expected by administrators.
Yes.
=> Consider having valuator group as having valuator

app/controllers/budgets/ballot/lines_controller.rb
Remove a `before_action` method not being used.
Yes
=> [Cleanup] Remove unused code

app/models/poll/stats.rb
* Commit 72b02e47, commit 57618c89 and all commits done around that time
* Remove duplication in methods in poll stats
* Expose potential bugs due to some methods being slightly different when they should probably be identical
Yes, backport alongside everything related to stats.
There seems to be a typo in the method `null_percentage_web`.
=> Refactor poll stats methods

app/helpers/admin_helper.rb, app/views/admin/_menu.html.erb, app/views/admin/budget_groups/index.html.erb, app/views/admin/budget_headings/index.html.erb, app/views/admin/site_customization/content_blocks/index.html.erb, app/views/budgets/investments/_content_blocks.html.erb, app/views/custom/layouts/_footer.html.erb, app/views/layouts/_footer.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/budget_groups_spec.rb, spec/features/admin/budget_headings_spec.rb
- Improve messages of links to go back from budget groups and headings.
- Highlight the budget section in the admin menu.
- Improve explanation texts about content blocks.
- Refactor code to make it more readable.
Yes
⚠️ From now on, content blocks are supposed to have only links. If you previously had some other HTML injected by using the content blocks feature, it might not render as it did before ☺️ . If you would like to make more specific changes to the footer or other views check out the docs on creating custom views https://consul_docs.gitbooks.io/docs/en/customization/views_and_styles.html
=> [Improvement] CRUD budgets and content blocks

.rubocop_basic.yml
Enable rubocop rule to always check for double quotes.
Yes
=> Enable double quotes rubocop rule

spec/features/admin/budget_investments_spec.rb
* Pull request consul#3151
* Commit consul@7c06320f3
* Fix a typo in a spec checking the default order for budget investments
* Keep the code in this repository as synchronized with CONSUL's repository as possible
No, the code is already in CONSUL.
=> [Upstream] Fix typo in investment default order spec

app/models/legislation/process.rb, app/views/legislation/processes/_header.html.erb, app/views/legislation/processes/_key_dates.html.erb, app/views/legislation/processes/show.html.erb, config/locales/en/legislation.yml, config/locales/es/legislation.yml, spec/features/legislation/processes_spec.rb
- Adds **homepage phase** and tab to legislation processes show.
- Moves **draft publication** and **final result publication** dates from tabs to sidebar: these dates aren't a phase, only a date that redirects to "Comments" phase.
**New homepage tab**
**Now "Draft publication" and "Final result publication" dates appear on header's sidebar**
=> Legislation process homepage phase

db/dev_seeds.rb, db/dev_seeds/milestones.rb
* Issue consul#3135
* Add progress bar dev seeds for proposals, budget investments and legislation processes
* Add milestone dev seeds for legislation processes, which were missing
* Reduce the amount of time it takes to create dev seeds for milestones and progress bars
Yes, backport alongside everything related to progress bars.
=> Add progress bar dev seeds

app/assets/javascripts/forms.js.coffee, app/assets/stylesheets/legislation_process.scss, app/assets/stylesheets/milestones.scss, app/helpers/milestones_helper.rb, app/models/concerns/milestoneable.rb, app/views/admin/shared/_common_globalize_locales.html.erb, app/views/admin/shared/_globalize_tabs.html.erb, app/views/legislation/processes/_key_dates.html.erb, app/views/milestones/_milestones_content.html.erb, app/views/milestones/_progress_bars.html.erb, config/locales/en/milestones.yml, config/locales/es/milestones.yml, spec/features/legislation/processes_spec.rb, spec/shared/features/admin_milestoneable.rb, spec/shared/features/admin_progressable.rb, spec/shared/features/milestoneable.rb, spec/shared/features/progressable.rb
* Issue consul#3135
* Display primary and secondary progress bars alongside milestones.
Yes, backport it when backporting everything related to progress bars.
=> Add progress bars to milestones public view

config/locales/en/activerecord.yml, spec/features/proposal_notifications_spec.rb, spec/models/proposal_notification_spec.rb
in `./spec/features/proposal_notifications_spec.rb` add the specs:
- Proposal Notifications Limits Cannot send more than one notification
within established interval
- Proposal Notifications Limit use time traveling to make sure notifications
can be sent after time interval
Yes
=> Add pending specs: Proposal Notifications Limits

config/application.rb, config/initializers/graphql.rb, config/initializers/graphql_api.rb, spec/lib/graphql_spec.rb
- **Pull Request**: https://github.com/consul/consul/pull/3159
Proposal, Debate and Comment "globalize_accessors" class method were
loaded before application available locales initialization because of
graphql initializer. This will cause unexpected translation errors at
any translatable classes declared at graphql api definition (api.yml).
Doing GraphQL initialization after application initialization should
solve this issue.
No, this comes from CONSUL.
Yes, tested in the staging environment for Proposals, Debates and Comments from the [GraphQL GUI](http://decidepre.madrid.es/graphiql) using a [basic call](https://github.com/consul/consul/blob/master/doc/api/api_en.md#graphql) to query for a resource of each class, for example:
```
{
proposal(id: 100) {
id,
title,
public_author {
id, …
```
=> [Upstream] Initialize graphql after application initialization

app/models/abilities/administrator.rb, app/views/admin/poll/questions/answers/documents.html.erb, spec/features/admin/poll/questions/answers/documents/documents_spec.rb
Allow admins delete poll answer documents, this PR:
- Remove documents from answers controller.
- Move admin poll questions answers documents view from `/questions/answers/documents.html.erb toi 'questions/answers/documents/index.html.erb`
- Fix admin poll question answers documents layout, _see attached images_.
- Create poll questions answers documents controller: this new controller allows include a delete button for poll questions answers documents on the view.
**BEFORE**
**AFTER**
=> Allow admins delete poll answer documents

app/helpers/budgets_helper.rb, app/views/budgets/index.html.erb, app/views/budgets/investments/index.html.erb, app/views/custom/budgets/index.html.erb, app/views/custom/budgets/investments/index.html.erb, spec/features/budgets/budgets_spec.rb, spec/features/budgets/investments_spec.rb
- Fix links on budgets index page: these links were linking to `/budgets/N/investments?filter=unfeasible` instead of `/budgets/N?filter=unfeasible`
- Hide heading links if budget is finished: now when the budget is finished the headings are no links. The users still can view the results with the "See results" button on header sidebar. _[Image 1]_
- Fix map overlapping links. _[Image 2]_
**[Image 1]**
**[Image 2]**
=> Improve UI of budgets index page

app/controllers/admin/poll/polls_controller.rb, app/views/admin/poll/polls/_poll.html.erb, app/views/admin/poll/polls/index.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/poll/polls_spec.rb
Related Issue: https://github.com/consul/consul/issues/3186
- Change admin poll list title from "List of active polls" to "List of polls"
- Order the polls list by starts_at date (from most recent to oldest).
=> Admin polls list

app/assets/stylesheets/custom.scss, app/assets/stylesheets/participation.scss, app/helpers/budgets_helper.rb, app/views/admin/budgets/_form.html.erb, app/views/budgets/groups/show.html.erb, app/views/budgets/index.html.erb, app/views/budgets/investments/_investment_show.html.erb, app/views/custom/budgets/index.html.erb, spec/features/admin/budget_investments_spec.rb, spec/features/admin/budgets_spec.rb, spec/features/budgets/investments_spec.rb
- Update calculate winners button on budgets form: now works the same way as the button on `/admin/budgets/N/budget_investments?filter=winners`. The button say "Calculate winner investments" (first time) and "Recalculate Winner Investments" the next one, and appears on ` balloting`,  `reviewing_ballots` and `finished` phases. 
- Hide hover background color on budget index if there is no heading link: now the hover effect effect appears only when the Headings are links (always except on `informing` and `finished` phases).
- Remove unused custom css.
- Show `Winning investment project` label only if budget is finished on investment show.
- Hide voted group css class if current filter is unfeasible.
- Improve space for links on budget index, added a little extra space between map and links. …
=> Budgets UI minor fixes

lib/user_segments.rb, spec/lib/user_segments_spec.rb
Issue https://github.com/AyuntamientoMadrid/consul/issues/1854
Order all newsletter emails by a user's `created_at` attribute
TODO (I'm not sure)
closes https://github.com/AyuntamientoMadrid/consul/issues/1854
=> Send newsletter emails in order

app/controllers/application_controller.rb, app/controllers/budgets/groups_controller.rb, app/controllers/budgets/investments_controller.rb, app/controllers/budgets_controller.rb, spec/features/budgets/investments_spec.rb
We want to show the list of `unfeasible` and `unselected` project although the budget is finished.
Yes
=> Show unfeasible and unselected investments for finished budgets.

Gemfile, Gemfile.lock, config/initializers/recipient_interceptor.rb, config/secrets.yml.example, spec/features/emails_spec.rb
PR https://github.com/consul/consul/pull/3251
Issue https://github.com/consul/consul/issues/2954
*Type*: Feature
To be able to configure the application to catch and forward emails to a specified email address depending on the environment.
Useful for staging environments where the data is a copy of production data.
⚠️ For Release Notes:
To enable this feature a new key `email_interceptor_recipients ` needs to be added to your `secrets.yml` file in your staging server. Check the example in `config/secrets.yml.example` and replace the `""` to the addresses or list of emails you want to forward the emails. Note that for more than one address, they need to be separated by commas (,). Eg.
```
staging:
email_interceptor_recipients: "address1@domain.com,address2@domain.com"
```
=> [Upstream] Configurable email interceptor by environment

app/controllers/spending_proposals_controller.rb
**PR: https://github.com/AyuntamientoMadrid/consul/pull/1776**
Now that we have [migrated spending proposal's votes to budget investment's votes](https://github.com/AyuntamientoMadrid/consul/pull/1828) we should use them in the public stats' view to make sure the numbers are still the same.
No, for CONSUL, and in Madrid soon, we should use the new [budget stats controller](https://github.com/AyuntamientoMadrid/consul/blob/master/app/controllers/budgets/stats_controller.rb), not this deprecated spending proposal's controller for stats.
There are no passing specs for obsolete spending proposal stats. Manual testing required in staging server.
=> Use budget investments votes in public stats

lib/migrations/spending_proposal/budget_investment.rb, lib/migrations/spending_proposal/budget_investments.rb, lib/tasks/spending_proposals.rake, spec/lib/migrations/spending_proposals/budget_investment_spec.rb, spec/lib/migrations/spending_proposals/budget_investments_spec.rb
Context
=== 
We already have budget investment for every corresponding spending proposal. 
However the `unfeasibility_explanation` attribute was [not migrated correctly](https://github.com/AyuntamientoMadrid/consul/pull/1059/files#diff-06e514cba40826339cac0ad0b9fba6ffR36). This raises a validation error when trying to update any other attribute in these budget investments.
Objectives
===
Migrate this attribute for all relevant budget investments to make them valid so that we can continue working on migrating supports and ballots.
Yes, this will be important for the final migration
Adding some [debug information](https://github.com/AyuntamientoMadrid/consul/compare/spending_proposals...AyuntamientoMadrid:spending_proposals_to_budget_investments?expand=1#diff-14fcc12aeb8116f3dbb72e855b0db07b …
=> Migrate unfeasibility explanation

lib/migrations/spending_proposal/vote.rb, lib/tasks/spending_proposals.rake, spec/lib/migrations/spending_proposals/vote_spec.rb
**PR: https://github.com/AyuntamientoMadrid/consul/pull/1776**
We already have budget investments for every spending proposal since the [partial migration](https://github.com/AyuntamientoMadrid/consul/pull/1059). But the votes where not included in this migration.
Create budget investment's votes for all corresponding spending proposal's votes.
Yes, forks that still have spending proposals in their code base should run this migration.
⚠️Run rake task:
`bin/rake spending_proposals:migrate_delegated_votes`
There is an upcoming PR deleting the obsolete spending proposal votes.
Yes, comparison with the current stats page should be done in the staging server before merging, to make sure supports are still the same.
=> Create budget investment's votes

lib/migrations/spending_proposal/budget_investment.rb, spec/lib/migrations/spending_proposals/budget_investment_spec.rb
**PR:** https://github.com/AyuntamientoMadrid/consul/pull/1776
`SpendingProposals` used a string for internal comments, whilst `Budget::Investments` use a `Comment` object instead.
Migrates `Spending Proposals`' internal comments to `Budget::Investment`'s valuation comments.
Yes 😌
=> Migrate spending proposal internal comments

app/helpers/legislation_helper.rb, app/models/legislation/process.rb, app/models/site_customization/page.rb, app/models/widget/card.rb, app/views/admin/legislation/processes/_form.html.erb, app/views/legislation/processes/_header.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/legislation/processes_spec.rb, spec/helpers/legislation_helper_spec.rb, spec/models/legislation/process_spec.rb
Previous PRs: https://github.com/AyuntamientoMadrid/consul/pull/1845 and https://github.com/AyuntamientoMadrid/consul/pull/1846
Upstream from https://github.com/consul/consul/pull/3249
- Fix hound warnings.
- Create helper for legislation process header with custom colors.
- Improve layout of admin legislation process form. 
- Refactor hexadecimal color validation.
- Refactor header process colors specs.
**Admin legislation process form BEFORE**
**Admin legislation process form AFTER**
=> [Upstream] Refactor processes header colors and custom pages

lib/migrations/spending_proposal/ballot.rb, lib/migrations/spending_proposal/ballots.rb, lib/tasks/spending_proposals.rake, spec/lib/migrations/spending_proposals/ballot_spec.rb, spec/lib/migrations/spending_proposals/ballots_spec.rb, spec/support/common_actions/budgets.rb
Migrate spending proposal ballots to budget investment ballots
Yes 😌
To migrate spending proposal ballots run this rake task:
```
bin/rake spending_proposals:migrate_ballots
```
=> Migrate spending proposal ballots

app/assets/stylesheets/layout.scss, app/controllers/admin/widget/cards_controller.rb, app/views/admin/site_customization/cards/index.html.erb, app/views/admin/widget/cards/_form.html.erb, app/views/pages/_card.html.erb, app/views/pages/_cards.html.erb, app/views/welcome/_card.html.erb, app/views/welcome/index.html.erb, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/es/activerecord.yml, config/locales/es/admin.yml, db/migrate/20190131122858_add_columns_to_widget_cards.rb, db/schema.rb, spec/features/admin/widgets/cards_spec.rb
Upstream from https://github.com/consul/consul/pull/3252
Admins can create cards for homepage on `/admin/widget/cards/new` and  since #3149 also for custom pages on `/admin/widget/cards/new?page_id=N`.
- Add **columns** to widget cards: this add a select on each card new form to select the number of columns for their width (for a better UX on mobile screens it's always 100%)
- Improve notice message for pages cards.
- Improve CSS layout.
- Show card label only if it is present: until now was showing an empty span.
- Remove unnecessary title on page cards: on custom pages a "Featured title" is not necessary.
- Add columns on welcome card view: I include this _feature_ for the cards created for the homepage.
- Fix hound warnings. Clean code! ✊🤓 
For cards you can use **from 1 to 12 …
=> [Upstream] Custom pages cards

app/assets/javascripts/forms.js.coffee, app/views/admin/legislation/processes/_form.html.erb, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/es/activerecord.yml, config/locales/es/admin.yml
Upstream from https://github.com/consul/consul/pull/3277/
https://github.com/consul/consul/pull/3152 added the possibility to change background and font colours for legislation processes header.
Synchronise color inputs make much easier to users.
**Add placeholder with default values and a little help text**
**Now the inputs are synchronised**
**You can update it using input color field**
**Or you can introduce a hexadecimal value manually**
Native html `<input type="color">` it's [not compatible with IE or Safari](https://caniuse.com/#search=color) but you can introduce value manually.
=> [Upstream] Improve color picker on admin legislation process

app/models/budget/heading.rb, spec/features/budgets/budgets_spec.rb
Show all the groups and headings in the Participatory Budgets landing page when translations for groups are missing
Yes
=> Show headings in budgets landing page when translations are missing

app/models/budget/heading.rb, spec/features/budgets/budgets_spec.rb
Reverts AyuntamientoMadrid/consul#1872
=> Revert "Show headings in budgets landing page when translations are missing"

app/models/debate.rb, app/models/legislation/proposal.rb, app/views/admin/legislation/proposals/_proposals.html.erb, app/views/debates/_votes.html.erb, app/views/legislation/proposals/_votes.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, db/migrate/20190118115237_add_cached_votes_score_to_legislation_proposals.rb, db/schema.rb, spec/features/admin/legislation/proposals_spec.rb, spec/features/debates_spec.rb, spec/features/legislation/proposals_spec.rb, spec/features/votes_spec.rb
Use *votes_score* instead of *total_votes* on **debates** and **legislation proposals**. 
The main change it's now the votes number is the result of `cached_votes_up` minus `cached_votes_down`.
**BEFORE**
```
1 cached_votes_up + 0 cached_votes_down = 1 vote
1 cached_votes_up + 1 cached_votes_down = 2 votes
0 cached_votes_up + 1 cached_votes_down = 1 vote
```
**NOW**
```
1 cached_votes_up + 0 cached_votes_down = 1 vote
1 cached_votes_up + 1 cached_votes_down = No votes
0 cached_votes_up + 1 cached_votes_down = -1 vote
```
So this PR:
- Replace total votes to cached_votes_score on debates: this show votes_score as result of votes_up minus votes_down.
- Add cached_votes_score to legislation proposals.
- Replace total votes to cached_votes_score on legislation proposals: this show votes_score …
=> Use votes score instead of total votes on debates and legislation proposals

app/controllers/admin/poll/shifts_controller.rb, app/models/poll/booth_assignment.rb, app/models/poll/shift.rb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/poll/shifts_spec.rb
Show an alert message when trying to delete a Poll Booth Shift that has associated data like `partial_results` or `recounts`.
YES
=> Delete Booth Shifts with associated data

app/helpers/budget_headings_helper.rb, app/models/budget/heading.rb, app/views/budgets/groups/show.html.erb, app/views/budgets/index.html.erb, app/views/custom/budgets/index.html.erb, spec/features/budgets/budgets_spec.rb, spec/features/budgets/groups_spec.rb, spec/models/budget/heading_spec.rb
- Show all headings if the group translations are missing.
- Correctly sort headings by name.
Yes, together with this PR https://github.com/AyuntamientoMadrid/consul/pull/1842
=> Budgets landing page

lib/migrations/spending_proposal/ballot.rb, lib/migrations/spending_proposal/delegated_ballot.rb, lib/migrations/spending_proposal/delegated_ballots.rb, lib/tasks/spending_proposals.rake, spec/lib/migrations/spending_proposals/delegated_ballot_spec.rb, spec/lib/migrations/spending_proposals/delegated_ballots_spec.rb
**PR**: Migrate spending proposal ballots https://github.com/AyuntamientoMadrid/consul/pull/1868
A Delegated Ballot is Ballot created by a Forum.
A Forum has many Represented Users.
Create a Budget Investment Ballot from the Spending Proposal Ballot of a Forum, for each Represented User.
No, delegation is not in CONSUL.
⚠️ To migrate delegated spending proposal ballots run the following migration:
```
bin/rake spending_proposals:migrate_delegated_ballots
```
=> Migrate spending proposal delegated ballots

app/models/comment.rb, spec/lib/migrations/spending_proposals/budget_investment_spec.rb
**PR** Migrate spending proposal internal comments https://github.com/AyuntamientoMadrid/consul/pull/1865
Some internal valuation comments exceed the [maximum length of 1000 characters](https://github.com/AyuntamientoMadrid/consul/blob/master/db/seeds.rb#L26) in the [Comments validations](https://github.com/AyuntamientoMadrid/consul/blob/master/app/models/comment.rb#L23).
This comments were not being migrated properly from Spending Proposals to Budget::Investments.
With this PR we are allowing valuation comments to be created even if they exceed the limit of 1000 characters.
Yes, internal comments should be migrated in CONSUL too.
=> Migrate internal comments with a large body

lib/migrations/spending_proposal/ballot.rb
**PR**: Migrate spending proposal ballots https://github.com/AyuntamientoMadrid/consul/pull/1868
Even though the specs run fine, when [running the rake task to migrate spending proposal ballots](https://github.com/AyuntamientoMadrid/consul/pull/1868) we are getting an exception, as Rails is not finding the correct `Budget` and `Budget::Ballot` classes.
Explicitly load the required dependencies so that the rake task can run successfully.
Yes, this is part of a migration that should be included in CONSUL.
=> Require dependencies for Budget and Budget::Ballot classes

lib/migrations/log.rb, lib/migrations/spending_proposal/ballot.rb, lib/migrations/spending_proposal/budget_investment.rb
**PR**: Migrate spending proposal ballots https://github.com/AyuntamientoMadrid/consul/pull/1868
We are seeing some unnecessary logs in Travis and locally when running these specs.
Only displaying these debugging logs when running the rake task in an environment other than _test_.
Yes, these specs are going to be executed in CONSUL too 😌
=> Do not display logs in test environment

config/initializers/i18n_pluralize.rb, config/initializers/inflections.rb, spec/i18n_spec.rb
If a translation was missing returning a `Fixnum` could cause to raise an exception "undefined method X for Fixnum".
For instance, we were getting the Exception "ActionView::Template::Error: undefined method 'pluralize' for 1:Fixnum" when calling `model_name.human` (used by the gem `kaminari` in the helper method `page_entries_info`).
Yes
=> Return a String in I18n method 'pluralize'

app/controllers/budgets/investments_controller.rb, app/controllers/concerns/random_seed.rb, app/controllers/custom/probes_controller.rb, app/controllers/human_rights_controller.rb, app/controllers/legislation/processes_controller.rb, app/models/budget/investment.rb, app/models/concerns/randomizable.rb, app/models/custom/probe_option.rb, app/models/debate.rb, app/models/legislation/proposal.rb, app/models/proposal.rb, spec/features/budgets/investments_spec.rb
* Issue #1196 
* Issue #1659 
* Issue #1191
* Issue consul#2155
* Pull request #1660 
* Pull request consul#3076
* Consistently maintain the random legislation proposals order for the same user session
* Use the same code to set and order by a random seed in all affected controllers
* Fix the flaky specs that appeared in `spec/features/legislation/proposals_spec.rb:34` ("Legislation Proposals Each user as a different and consistent random proposals order"), `spec/features/legislation/proposals_spec.rb:60` ("Legislation Proposals Random order maintained with pagination"), and `spec/features/budgets/investments_spec.rb:611` ("Budget Investments Orders Each user has a different and consistent random budget investment order when random_seed is disctint")
Quoting from the commit message:
> …
=> Fix random proposals order in the same session

app/assets/stylesheets/admin.scss, app/controllers/admin/system_emails_controller.rb, app/mailers/mailer.rb, app/views/admin/system_emails/index.html.erb, app/views/admin/system_emails/view.html.erb, app/views/mailer/reply.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, lib/reply_email.rb, spec/features/admin/system_emails_spec.rb
Issue https://github.com/consul/consul/issues/3179
Show all system emails on `/admin/system_emails`
Yes
=> Show all system emails in Admin section

app/controllers/admin/legislation/processes_controller.rb, app/controllers/admin/milestones_controller.rb, app/controllers/admin/poll/polls_controller.rb, app/controllers/admin/widget/cards_controller.rb, app/controllers/budgets/investments_controller.rb, app/controllers/concerns/image_attributes.rb, app/controllers/legislation/proposals_controller.rb, app/controllers/proposals_controller.rb, app/helpers/images_helper.rb
* Pull request consul#3170
* Issue consul#3153
Define image attributes in only one place and share them among all controllers using them.
Yes, backport only the last commit; the rest of the code is already there.
=> [Upstream] Refactor images attributes

app/assets/stylesheets/admin.scss, app/controllers/admin/budget_investments_controller.rb, app/helpers/budget_investments_helper.rb, app/models/budget/investment.rb, app/views/admin/budget_investments/_investments.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/budget_investments_spec.rb, spec/helpers/budget_investments_helper_spec.rb
* Pull request consul#3148
* Issue consul#2931
Use links in table headers to sort records instead of using a `select` field.
This pull request only implements sorting by the columns we could already sort by.
**Arrows icons indicate the sortable columns**
**Active desc order**
**Active asc order**
Backport the last two commits.
=> [Upstream] Add sorting links to investments admin table

app/controllers/admin/legislation/processes_controller.rb, app/helpers/legislation_helper.rb, app/models/legislation/process.rb, app/views/admin/legislation/processes/_form.html.erb, app/views/admin/legislation/processes/index.html.erb, app/views/welcome/_card.html.erb, app/views/welcome/_feeds.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/legislation/processes_spec.rb
This PR fix some UI details for a better UX and design. 👨‍🎨 
- Improve help text for legislation processes proposals categories indicating to admin users they can use 160 characters by category. _[Image 1]_
- Align proposal feed description without image on welcome page: when enable only proposals feed from admin, the proposals without an image appear unaligned. _[Image 2]_
- Show card label only if it is present on welcome page: this was added on cards of custom pages, now on welcome page too avoiding to show an empty span. _[Image 3]_
- Replace open to active filter on admin legislation processes index: now on active filter show open processes and the "next" ones, processes with a start date greater than current date. _[Image 4]_
- Replace created at date to start and end date on admin …
=> Fix UI details for a better UX and design

app/controllers/admin/budget_investments_controller.rb, app/models/budget/investment.rb, app/views/admin/budget_investments/edit.html.erb, spec/features/admin/budget_investments_spec.rb, spec/models/budget/investment_spec.rb
Fix a bug which removed an investment's valuation tags when marking it as visible to valuators.
As explained in the commit message:
> When params[:budget_investment][:valuation_tag_list] was not present, which is the case when updating an investment using the "mark as visible to valuators" checkbox, we were removing all valuation tags.
>
> Using a virtual attribute to assign the tags only if the parameter is present simplifies the code in the controller and avoids the issue.
Yes.
=> Fix valuation tags being overwritten

app/views/admin/_menu.html.erb, app/views/admin/budgets/index.html.erb, app/views/admin/poll/polls/booth_assignments.html.erb, app/views/custom/pages/accessibility.html.erb, config/locales/custom/en/legislation.yml, config/locales/en/admin.yml, config/locales/en/general.yml, config/locales/en/legislation.yml, config/locales/es/general.yml, config/locales/es/legislation.yml, config/locales/es/pages.yml, db/dev_seeds/legislation_processes.rb, spec/features/admin/legislation/processes_spec.rb, spec/features/admin/legislation/proposals_spec.rb, spec/features/admin/poll/booth_assigments_spec.rb, spec/features/custom/admin/legislation/film_library_process_spec.rb
Improve UX on admin section with the following changes:
- Replace poll name link in admin polls booth assignments: before link to poll and was a little confusing, now links to manage  admin poll booth assignments.
- Remove budget name link on admin budgets index: so the admin can use the actions on the table. 
- Reorder admin menu links with the same order of the front views.
- Replace legislation processes text to collaborative legislation to add consistency across all the app.
=> Improve UX on admin section

lib/migrations/spending_proposal/budget_investment.rb, lib/migrations/spending_proposal/vote.rb, lib/tasks/spending_proposals.rake
- Add a rake task to migrate all necessary data from spending proposals to budget investments.
- Make rake task logs more accurate
Yes, a final rake task should be included in the backport to CONSUL. However not all task should be included, as for example, delegation is not present in CONSUL.
To run this migration execute the following command:
`bin/rake spending_proposals:migrate`
=> Use a single rake task to migrate spending proposals

app/controllers/spending_proposals_controller.rb, spec/features/budgets/executions_spec.rb, spec/features/spending_proposals_spec.rb
Update the spending proposals stats and results view to use budget investment data
No, these views will be deleted and substituted by the standard budget investment views for [stats](https://github.com/AyuntamientoMadrid/consul/blob/master/app/controllers/budgets/stats_controller.rb) and [results](https://github.com/AyuntamientoMadrid/consul/blob/master/app/controllers/budgets/results_controller.rb).
This is a pre step before using the budget investments views, to make sure the migration has been done correctly and the values match the spending proposal stats and results.
=> Update spending proposals views

app/views/budgets/investments/_investment_show.html.erb, spec/features/budgets/investments_spec.rb
Show unfeasible budget investment messages only when valuation finished.
Now the message `This investment project has been marked as not feasible and will not go to balloting phase` only appears when valuation is marked as finished.
=> Show unfeasible budget investment messages only when valuation finished

app/views/admin/poll/results/index.html.erb, spec/factories/polls.rb, spec/features/admin/poll/polls_spec.rb
This is an upstream of https://github.com/consul/consul/pull/3155 & https://github.com/consul/consul/pull/3341
The options to display stats and results are now showing even when there are only web voters in a poll. They'll be shown independently from the partial results in the admin results page. 
Only the last commit ☺️
=> [Upstream] Show results checkbox for voted polls

app/controllers/budgets/results_controller.rb, app/views/custom/budgets/index.html.erb, spec/features/budgets/results_spec.rb
- Remove custom link to 2016's results
- Use city heading as the default heading for results
Maybe, but the city heading is something quite specific for Madrid's fork.
At least part of this PR should be backported to reduce differences with Upstream.
=> Update spending proposals results url

app/models/budget/stats.rb
Expire budget's stats cache
Maybe. Consider expiring the budget's stats cache in the migration rake task instead.
=> Expire budget investments' stats cache

app/models/budget/ballot/line.rb, lib/migrations/spending_proposal/ballot.rb, lib/migrations/spending_proposal/vote.rb, spec/lib/migrations/spending_proposals/ballot_spec.rb, spec/lib/migrations/spending_proposals/delegated_ballot_spec.rb, spec/lib/migrations/spending_proposals/vote_spec.rb, spec/models/budget/ballot/line_spec.rb
- Display more accurate debugging logs
- Migrate supports for hidden users
- Migrate votes for hidden users
- Migrate votes for users with delegation and empty ballots
- Migrate votes for reclassified investments
Yes, except the delegation parts.
=> Migrate special supports and votes

app/controllers/budgets/results_controller.rb, app/controllers/budgets/stats_controller.rb, app/views/budgets/results/show.html.erb, app/views/budgets/stats/show.html.erb, spec/features/budgets/results_spec.rb, spec/features/budgets/stats_spec.rb
Display headings in stats and results ordered by heading name and group
Yes, more robust ordering would be good for CONSUL too.
=> Order headings by name and group

lib/migrations/spending_proposal/budget.rb, lib/tasks/spending_proposals.rake, spec/lib/migrations/spending_proposals/budget_spec.rb
Add the required actions to be executed before and after the migration.
Before:
- Update heading prices
- Update heading populations
- Update selected investments
After:
- Remove forum votes
- Remove forum ballots
- Update investment cached votes
- Update investment cached ballots
- Calculate winners
Yes, but it's going to be tricky. This is very specific for Madrid's fork.
=> Spending proposals pre and post migration actions

config/locales/custom/en/admin.yml, config/locales/custom/es/admin.yml, config/locales/en/admin.yml, config/locales/es/admin.yml
* Pull request consul#3342
Move translations used in CONSUL from the `custom` folder to the main files.
=> [Upstream] Move recounts index translations to main files

app/views/admin/legislation/processes/_form.html.erb, config/locales/custom/en/legislation.yml, config/locales/custom/es/legislation.yml, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/en/budgets.yml, config/locales/en/legislation.yml, config/locales/en/settings.yml, config/locales/es/activerecord.yml, config/locales/es/admin.yml, config/locales/es/budgets.yml, config/locales/es/legislation.yml, config/locales/es/settings.yml, spec/models/legislation/process_spec.rb
Upstream from https://github.com/consul/consul/pull/3337
This PR **generalizes some i18n keys**, moves customised ones to custom files. Also replaces translations on admin legislation processes to use _activerecord_ translations.
No, this code it's already on CONSUL. 😌
=> [Upstream] Generalize i18n texts 

app/controllers/officing/voters_controller.rb, app/models/poll.rb, app/views/officing/voters/_already_voted.html.erb, app/views/officing/voters/_cannot_vote.html.erb, app/views/officing/voters/new.html.erb, config/locales/en/officing.yml, config/locales/es/officing.yml, spec/features/officing/voters_spec.rb
Polls that were not votable by a user were not being displayed in the officing interface. Creating a confusing situation for officers.
Polls that are not votable by a user should be displayed and a corresponding message displayed explaining that a poll can only be voted by residents of a certain geozone.
Yes, officers should see polls that are not votable by a user in CONSUL too.
=> Display all polls for current booth

.erb-lint.yml, .hound.yml, Gemfile, Gemfile.lock
Automatically detect syntax not following our code conventions in ERB files.
Yes.
The rubocop linter cannot use the `rubocop_config` option because it's not compatible with Ruby 2.3. So we're setting the rubocop rules manually.
=> Add ERB Lint configuration file

.rubocop_basic.yml
Follow Ruby code conventions in all files having ruby code.
Yes.
We were unintentionally ignoring them while trying to ignore just the schema file, migration files, and initializers generated with `rails generate`
=> Enable rubocop rules in config and seed files

app/models/budget/stats.rb
1 of the 3 servers has not picked up the new cache keys for budget investment stats.
Expire cache of all production servers.
Sure, to maintain consistent cache versions.
=> Expire stats cache

app/controllers/welcome_controller.rb, spec/features/welcome_spec.rb
- Do not raise an exception if a not logged in user navigates to `/welcome`
- Tell the user you need to be logged in with a flash message.
Yes
=> Require logged in user if navigate to /welcome

lib/tasks/proposals.rake, spec/lib/tasks/proposals_spec.rb
Related issue: https://github.com/consul/consul/issues/3182
This rake move the content of `external_url` to `description` for **Proposals** and **Legislation proposals**.
**BEFORE**
**AFTER**
⚠️ Run `bin/rake proposals:move_external_url_to_description RAILS_ENV=production` to move the content of external_url to description for Proposals and Legislation proposals.
=> Add rake to move external_url to description

app/controllers/legislation/proposals_controller.rb, app/controllers/management/proposals_controller.rb, app/controllers/proposals_controller.rb, app/models/legislation/proposal.rb, app/models/proposal.rb, app/views/admin/hidden_proposals/index.html.erb, app/views/custom/legislation/proposals/show.html.erb, app/views/documents/_additional_documents.html.erb, app/views/legislation/proposals/show.html.erb, app/views/proposals/_form.html.erb, app/views/proposals/_info.html.erb, config/api.yml, config/locales/en/documents.yml, config/locales/en/general.yml, config/locales/es/documents.yml, config/locales/es/general.yml, db/dev_seeds/legislation_proposals.rb, db/dev_seeds/proposals.rb, db/migrate/20190307165132_remove_question_and_external_url_from_proposals.rb, db/migrate/20190307165337_remove_question_and_external_url_from_legislation_proposals.rb, db/schema.rb, spec/factories/proposals.rb, spec/features/admin/hidden_proposals_spec.rb, spec/features/api/csv_exporter_spec.rb, spec/features/management/proposals_spec.rb, spec/features/proposals_spec.rb, spec/features/tags/proposals_spec.rb, spec/models/proposal_spec.rb, spec/support/common_actions.rb, spec/support/common_actions/proposals.rb
Related issue: https://github.com/consul/consul/issues/3182
- Remove `question` and `external_url` fields from **proposals**.
- Remove `question` and `external_url` fields from **legislation proposals**.
=> Remove question and external_url fields from proposals and legislation proposals 

app/controllers/proposals_controller.rb, app/helpers/verification_helper.rb, app/models/user.rb, app/models/verification/residence.rb, app/views/admin/stats/show.html.erb, app/views/custom/proposals/_kit_decide.html.erb, app/views/proposals/share.html.erb, app/views/verification/residence/new.html.erb, config/locales/custom/en/general.yml, config/locales/custom/es/general.yml, config/locales/en/general.yml, config/locales/en/settings.yml, config/locales/es/general.yml, config/locales/es/settings.yml, db/dev_seeds/settings.rb, db/seeds.rb, lib/tasks/settings.rake, spec/features/proposals_spec.rb, spec/features/verification/residence_spec.rb
Remove "deprecated" settings: `Setting["proposal_improvement_path"]` and `Setting["analytics_url"]`. These settings was only use once and doesn't make sense still being settings.
Also, remove "duplicated" `Setting['min_age_to_verify']`, already exists the setting `Setting["min_age_to_participate"]` with the same behaviour.
Only backport the last commit to use `min age to participate` setting on verification residence form. The rest of settings doesn't exists on CONSUL.
=> Remove deprecated settings

app/models/widget/feed.rb
* Pull request consul#3400
Make the legislation process shown on a feed consistent.
As mentioned in the commit message, we need to add an ORDER BY clause; not doing so was causing different processes to show up sometimes. Quoting the PostgreSQL manual:
> Because the order of the rows in the database table is unpredictable, when you use the LIMIT clause, you should always use the ORDER BY clause to control the order of rows. If you don’t do so, you will get an unpredictable result set.
=> Fix legislation process feed order

app/controllers/budgets/stats_controller.rb, app/controllers/polls_controller.rb, app/models/budget/stats.rb, app/models/concerns/statisticable.rb, app/models/poll/stats.rb, app/views/budgets/stats/show.html.erb, app/views/polls/stats.html.erb, app/views/shared/stats/_age.html.erb, app/views/shared/stats/_gender.html.erb, app/views/shared/stats/_geozone.html.erb, app/views/shared/stats/_links.html.erb, app/views/shared/stats/_participation.html.erb, config/locales/en/stats.yml, config/locales/es/stats.yml, spec/models/budget/stats_spec.rb, spec/models/poll/stats_spec.rb, spec/models/statisticable_spec.rb
* Depends on pull request #1933
* Display only stats which are relevant to the budget or poll being shown. So if there's no gender, age, geozone or channel information, those stats are not displayed.
Before these changes:
After these changes:
Yes, backport when backporting everything related to stats.
* The mehtods `gender?`, `age?` and `geozone?` might need to be changed because I haven't spent much time thinking about all possible scenarios.
=> Show only existing stats

app/models/concerns/randomizable.rb
* Issue #1659
* Issue consul#3075
* Issue consul#3368
* Pull request #1757
* Consistently maintain the random legislation proposals and budget investments order for the same user session
* Fix the flaky specs that appeared in `spec/features/legislation/proposals_spec.rb:34` ("Legislation Proposals Each user as a different and consistent random proposals order"), `spec/features/legislation/proposals_spec.rb:60` ("Legislation Proposals Random order maintained with pagination"), and `spec/features/budgets/investments_spec.rb:611` ("Budget Investments Orders Each user has a different and consistent random budget investment order when random_seed is disctint")
Yes.
* The order of the array before being shuffled needs to be the same if we want to have the same array after being shuffled with a …
=> Fix sort by random inconsistencies

app/models/concerns/statisticable.rb, app/views/budgets/stats/show.html.erb, app/views/polls/stats.html.erb, app/views/shared/stats/_geozone.html.erb, config/locales/en/stats.yml, config/locales/es/stats.yml, lib/geozone_stats.rb, lib/percentage_calculator.rb, spec/lib/geozone_stats_spec.rb, spec/models/budget/stats_spec.rb, spec/models/poll/stats_spec.rb, spec/models/statisticable_spec.rb
* Pull request #1789 
Fix geozone population stats. Currently we calculate the participation percentage related to the registered users from a geozone. However, we need to compare against the geozone population.
Currently, geozones don't store population information. So for polls we won't display this percentage, and for budgets we'll use the information stored in the headings.
Yes, backport when we backport everything related to stats.
=> Fix geozone population stats

spec/features/budgets/investments_spec.rb
* Pull request consul#3405
* Fix tests which were accidentally passing because of typos
* Generate the right amount or records we need to test budget investment pagination
=> Fix investment pagination tests

app/models/budget/stats.rb, app/models/concerns/statisticable.rb, app/models/poll/stats.rb, spec/models/budget/stats_spec.rb, spec/models/poll/stats_spec.rb
* Pull request #1834
Include hidden users in stats. Sometimes users participate in a process and a while after that they are hidden. We were modifying the stats when that happened, not counting the users who were hidden anymore.
Yes, backport when we backport everything related to stats.
=> Include hidden users in stats

lib/migrations/spending_proposal/budget_investments.rb, lib/tasks/spending_proposals.rake, spec/lib/migrations/spending_proposals/budget_investments_spec.rb
There are some polymorphic tables that still hold records associated to spending proposals. So far we have migrated, copied or dismissed all of these records and associated them to their corresponding budget investments. Now it is time to complete delete any associated records to spending proposals.
Destroy all records associated to spending proposals:
- Supports
- Taggings
Destroy all records associated to spending proposals run this rake task:
```
bin/rake spending_proposals:destroy_associated RAILS_ENV=production
```
=> Add rake task to destroy all associated records

app/controllers/users/confirmations_controller.rb, spec/controllers/users/confirmations_controller_spec.rb
* Pull request consul#3432
Don't show a 500 Internal Server Error message when trying to confirm a user with a token which doesn't exist.
=> Fix exception when confirming an invalid token

.gitignore
**PR**: https://github.com/consul/consul/pull/3430
Some developers use the [Intellij IDE](https://www.jetbrains.com/idea/) to work with Rails.
Adding the `/.idea` folder where project settings are stored, so that these files do not have to be skipped manually when sending a PR upstream.
No, this PR comes from Upstream.
=> Add Intellij IDE project settings to gitignore

app/models/poll/stats.rb
* Pull request #1951
Use SQL's `select` instead of Ruby's  `pluck` to calculate unique voters faster.
* With this change, performance increases dramatically when there are thousands of records. For a poll with 200000 voters, calculating stats used to take more than 7 minutes on our preproduction server, and now it takes less than 2 minutes.
Yes, backport alongside everything related to stats.
=> Increase poll stats performance

app/models/concerns/statisticable.rb, app/models/poll/stats.rb, spec/models/poll/stats_spec.rb
* Pull request #1951
Include users who voted via booths as users with no demographic data when we couldn't introduce their data in our database.
Yes, backport alongside everything related to stats.
=> Fix booth recounts poll stats discrepancies

lib/tasks/spending_proposals.rake
- [Migrate spending proposals to budget investments](https://github.com/AyuntamientoMadrid/consul/pull/1776)
- [Delete spending proposals](https://github.com/AyuntamientoMadrid/consul/pull/1937)
Add a rake task to be executed in the production environment with instrucction on how to migrate from `spending proposals` to `budget investments`
Yes, the first CONSUL forks might have spending proposals in the production environment.
The id of the PR in the warning message will probably change when backporting to CONSUL.
To run the the check for spending proposals run this rake task:
`bin/rake spending_proposals:check RAILS_ENV=production`
=> Add rake task to check for spending proposals

app/helpers/application_helper.rb, app/views/budgets/investments/_investment.html.erb, spec/features/management/budget_investments_spec.rb, spec/support/common_actions/users.rb
When visiting `/management/budgets/:id/investments/print`
If budget is in balloting phase and there are voted investments, it was not possible to print budgets investments because the ballot was never being loaded in the controller and therefore an error was raised when rendering the view.
```
Failure/Error: <% if ballot.has_investment?(investment) %>
ActionView::Template::Error:
undefined method `has_investment?' for nil:NilClass
app/views/budgets/investments/_ballot.html.erb:3
app/views/budgets/investments/_investment.html.erb:88
app/views/custom/management/budgets/investments/print.html.erb:26
```
Yes 😄
=> Fix bug moderator can't print voted investments in balloting phase

app/views/admin/budgets/_form.html.erb, app/views/budgets/executions/show.html.erb, app/views/budgets/results/show.html.erb, app/views/budgets/show.html.erb, app/views/budgets/stats/show.html.erb, app/views/custom/admin/budget_investments/index.html.erb, app/views/custom/budgets/index.html.erb, app/views/custom/pages/help/budgets/_welcome_header_finished.html.erb, app/views/custom/pages/help/budgets/_welcome_header_reviewing.html.erb, config/routes/custom.rb, spec/features/budgets/executions_spec.rb, spec/features/budgets/results_spec.rb, spec/routing/custom/routing_spec.rb
Reduce differences between CONSUL and Madrid's repositories by using route helpers like `budget_stats_path` instead of `custom_budget_stats_path`.
No, it only affects custom code.
=> Simplify custom budget routes usage

spec/factories/custom.rb, spec/factories/polls.rb
* Pull request consul#2857
* Pull request consul#2858
* Move code which used to be custom and is now present in CONSUL to the main folder files.
* Reduce differences between CONSUL's and Madrid's codebases.
=> Move poll ballot factories to main files

app/controllers/admin/poll/polls_controller.rb, app/models/stats_version.rb, db/migrate/20190311215516_destroy_spending_proposals.rb, db/migrate/20190311220350_destroy_spending_proposal_ballots.rb, db/migrate/20190311220600_destroy_spending_proposal_delegation.rb, db/migrate/20190311220711_destroy_spending_proposal_valuations.rb, db/migrate/20190326210351_destroy_spending_proposal_supports.rb, db/migrate/20190326211832_destroy_spending_proposal_associations.rb, db/migrate/20190408133956_create_stats_versions.rb
* Pull request #1947
* Pull request #1937
* Pull request #1951
Upgrade migration and model files in order to follow Rails 5 inheritance conventions. These migrations and models were created shortly before updating to Rails 5, and so the migrations didn't have the version number and the models inherited from `ActiveRecord::Base` instead of `ApplicationRecord`.
Yes, backport when backporting the pull requests which generated these migrations.
=> Update recent model and migration files

app/controllers/budgets/recommendations_controller.rb, spec/factories/budgets.rb, spec/features/budgets/recommendation_spec.rb
Fix an exception taking place when accessing budget recommendations without signing in and without providing a user id.
No, unless we decide to backport #702
=> Fix accessing recommendations without signing in 

app/controllers/application_controller.rb, app/controllers/concerns/access_denied_handler.rb, app/controllers/management/sessions_controller.rb, spec/controllers/management/sessions_controller_spec.rb
Don't generate a 500 Internal Server Error when trying to access the management sign in page without proper authorization.
Yes.
I've chosen to do the same thing we do in the ApplicationController. There are other options to handle this request, like redirecting to the login page or returning a 401 Unauthorized HTTP status.
=> Handle AccessDenied in management sessions

spec/features/budgets/results_spec.rb, spec/features/budgets/stats_spec.rb
* Commit 597542ad
* Commit 1a3dd780
* [Travis build 11450, job 7](https://travis-ci.org/AyuntamientoMadrid/consul/jobs/524019245)
Stub the `city_heading?` method in tests which are testing for city heading, so these tests don't return results order alphabetically and so they don't fail sometimes depending on the ID of the created budget groups.
No, there's no "city heading" code there.
=> Stub city heading in specs

spec/features/budgets/ballots_spec.rb
* Issue consul#3451
* [Travis build 11448, job 9](https://travis-ci.org/AyuntamientoMadrid/consul/jobs/523947084)
* [Recent change in the test environment](https://github.com/AyuntamientoMadrid/consul/pull/1947/files#diff-639e7393aa097999e816b53faa94bab4L18)
Check page after an AJAX call so the test doesn't fail sometimes due to two requests being processed simultaneosly.
Yes.
* This test started to fail after upgrading to Rails 5, since we removed the change done in commit eda47eff which set `config.allow_concurrency` to `false` in the test environment.
* This test failed with two possible errors: "undefined method `heading' for nil:NilClass" and "stale element reference: element is not attached to the page document". This change fixes the second error; it might fix the first error as …
=> Fix flaky spec: Ballots Groups Change my heading

db/schema.rb
* Pull request #1945 
Use Rails 5 conventions in the schema file, which had been generated in the dashboard branch using Rails 4.
Yes, include it when merging the dashboard in CONSUL.
=> Regenerate schema file

app/assets/stylesheets/dashboard.scss, app/controllers/admin/dashboard/actions_controller.rb, app/helpers/admin/proposal_dashboard_actions_helper.rb, app/helpers/proposals_dashboard_helper.rb, app/views/admin/dashboard/actions/_form.html.erb, app/views/communities/_poll.html.erb, app/views/communities/show.html.erb, app/views/custom/proposals/show.html.erb, app/views/dashboard/_goal.html.erb, app/views/dashboard/_resource.html.erb, app/views/proposals/created.html.erb, app/views/proposals/share.html.erb, app/views/users/_proposal.html.erb, config/locales/en/general.yml, config/locales/es/general.yml, lib/tasks/proposal_actions.rake
Add proposal's dashboard  https://github.com/AyuntamientoMadrid/consul/pull/1945.
- Change i18n to resources on next goal: this resources always are locked when are shown on next goal section.
- Dont use faker gem on simulate successful proposal rake.
- Fix typo.
- Always show dashboard buttons.
- Use proposal_poll_path on communities poll links.
- Fix styles of dashboard poster.
- Fix request_to_administrators checkbox on admin dashboard actions.
Yes,  backport to CONSUL. 🙏 😌
=> Dashboard UI improvements

app/views/dashboard/_form.html.erb, config/locales/en/general.yml, config/locales/es/general.yml, spec/features/dashboard/dashboard_spec.rb
Add message on dashboard request to archived proposals. Show this message instead of "Request" button.
=> Add message on dashboard request to archived proposals

app/views/admin/poll/questions/_successful_proposals.html.erb, spec/features/admin/poll/questions_spec.rb
* Pull request #1913
Fix a crash visting the admin questions index when there are questions from successful proposals.
Yes, backport when backporting #1913
=> Fix obsolete reference to proposal question

app/assets/stylesheets/participation.scss, app/views/budgets/ballot/_ballot.html.erb, app/views/budgets/investments/_sidebar.html.erb, config/locales/en/budgets.yml, config/locales/es/budgets.yml, spec/features/budgets/ballots_spec.rb, spec/features/budgets/investments_spec.rb
Upstream from https://github.com/consul/consul/pull/3407
Update texts on check my ballot links to clarify to users that their ballot (votes) are confirmed.
=> Update texts on check my ballot links

app/views/admin/newsletters/show.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, lib/user_segments.rb, spec/lib/user_segments_spec.rb
- Add new user segment `all_proposals_authors`:   this segment include all proposals authors even if the proposals are **archived** or **retired**.
- Also fix html on admin newsletters show to prevent send button renders outside of the layout.
=> Proposals authors user segment

app/models/budget/investment.rb, spec/models/budget/investment_spec.rb
The admin interface was displaying investments in an incorrect order because it did not take into account physical votes when ordering by supports.
Take into account physical votes when ordering investments in the admin interface.
Maybe, `physical_votes` is a deprecated attribute but it could still be in use in CONSUL.
=> Sort investments by cached votes plus physical votes

config/initializers/devise.rb, spec/features/users_auth_spec.rb
This change don't let the user know if the email address exists when asking to **resend confirmation** or **password reset** instructions.
Yes, Backport to CONSUL.
=> Change devise configuration

app/models/budget/investment.rb
**PR**: https://github.com/AyuntamientoMadrid/consul/pull/1991
Bringing back a secondary investment order by `id`, for the cases when two investments have the same number of votes, to [fix the build](https://travis-ci.org/AyuntamientoMadrid/consul/jobs/528819257#L1262).
Maybe. Depends on whether we also backport the [initial PR that introduced this issue](https://github.com/AyuntamientoMadrid/consul/pull/1991/files#diff-8e806f1abf6a06e54748ebcb2ce63d3aL156).
=> Fix investment order spec

app/models/concerns/notifiable.rb, app/models/notification.rb, app/views/notifications/_notification.html.erb, db/migrate/20190221154819_remove_deprecated_translatable_fields_from_banners.rb, db/migrate/20190221162450_remove_deprecated_translatable_fields_from_polls.rb, db/migrate/20190221162858_remove_deprecated_translatable_fields_from_poll_questions.rb, db/migrate/20190221163818_remove_deprecated_translatable_fields_from_admin_notifications.rb, db/migrate/20190221164056_remove_deprecated_translatable_fields_from_milestones.rb, db/migrate/20190221164559_remove_deprecated_translatable_fields_from_legislation_draft_versions.rb, db/migrate/20190221164928_remove_deprecated_translatable_fields_from_legislation_processes.rb, db/migrate/20190221165347_remove_deprecated_translatable_fields_from_legislation_questions.rb, db/migrate/20190221171155_remove_deprecated_translatable_fields_from_legislation_question_options.rb, db/migrate/20190221171859_remove_deprecated_translatable_fields_from_site_customization_pages.rb, db/migrate/20190221172209_remove_deprecated_translatable_fields_from_widget_cards.rb, db/migrate/20190325184500_remove_deprecated_translatable_fields_from_budgets.rb, db/migrate/20190325185046_remove_deprecated_translatable_fields_from_budget_groups.rb, db/migrate/20190325185405_remove_deprecated_translatable_fields_from_budget_headings.rb, db/migrate/20190325185550_remove_deprecated_translatable_fields_from_budget_phases.rb, db/schema.rb
* Pull request consul#3327
* Remove obsolete columns which might still accidentally be used by active record scopes
* Fix incompatibilities between Globalize and Rails 5
Yes. Although the code is already in the `translations` branch, the code on this pull request updates the migrations so they're compatible with Rails 5.
=> Remove deprecated translations code

db/migrate/20190221163117_remove_deprecated_translatable_fields_from_poll_question_answers.rb, db/schema.rb
* This commit was missing from pull request #1985
* Remove obsolete columns which might still accidentally be used by active record scopes
* Fix incompatibilities between Globalize and Rails 5
Yes, backport when backporting #1985
=> Remove deprecated attributes from Poll::Question::Answer

app/controllers/dashboard/polls_controller.rb, spec/features/dashboard/polls_spec.rb
* Commit e182f792
* Replace the method `respond_with_bip`, which belonged to a gem we removed
* Add tests checking the application behaves properly updating polls with AJAX requests
Yes.
=> Fix obsolete `respond_with_bip` usage

app/views/budgets/groups/show.html.erb, app/views/legislation/proposals/_geozones.html.erb, app/views/shared/_map.html.erb, config/locales/custom/en/custom.yml, config/locales/custom/es/custom.yml, spec/features/admin/site_customization/images_spec.rb
Upstream from https://github.com/consul/consul/pull/3472.
Admin users can change map image on `/admin/site_customization/images`.
This custom image is not rendering in all pages with the map. With this PR we always render custom map image from admin site customization images if it's present.
No, this code it's already on CONSUL.
=> Always use map image from admin site customization images

app/controllers/polls_controller.rb
* Pull request #1985
Fix a crash accessing old polls happening because we were using the original (already removed) "name" column in the polls table, instead of using the one in the translations table.
No, the code is only present in Madrid's fork.
=> Fix wrong column usage in 2017 poll stats

spec/features/budgets/executions_spec.rb
* Failure in [Travis build 11517, job 4](https://travis-ci.org/AyuntamientoMadrid/consul/jobs/530443103)
Fix a typo which made a test check the opposite of what we intended.
Yes.
The test passed (most of the time) because before clicking the "Milestones" link the content was not present, and we checked the page content before the AJAX request generated by clicking the link had finished.
=> Fix typo in budget executions spec

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/login_form.js.coffee, app/assets/stylesheets/layout.scss, app/controllers/users/sessions_controller.rb, app/models/user.rb, app/views/devise/sessions/new.html.erb, config/i18n-tasks.yml, config/initializers/devise.rb, config/initializers/recaptcha.rb, config/locales/en/devise.yml, config/locales/en/settings.yml, config/locales/es/devise.yml, config/locales/es/settings.yml, config/routes/devise.rb, config/secrets.yml.example, db/dev_seeds/settings.rb, db/migrate/20190507102732_add_failed_attempts_to_users.rb, db/schema.rb, db/seeds.rb, lib/tasks/settings.rake, spec/features/users_auth_spec.rb, spec/models/user_spec.rb
After a certain number of failed login attempts, a reCAPTCHA will show in the login form to prevent brute force attacks.
This feature is disabled by default, but it can be enabled/disabled from the admin panel -> Settings section -> Features (check gif below)
The number of failed login attempts is set to 5 by default, but it also can be changed from the admin panel -> Settings section -> Configuration settings (check gif below)
❓(unknown)  
- If you would like to enable this feature you must get your reCAPTCHA keys from [Google reCAPTCHA admin panel](https://www.google.com/recaptcha/admin) and you need to update your file `config/secrets.yml` accordingly. You must add the keys `recaptcha_site_key` and `recaptcha_secret_key`. You can see an example under the file …
=> Show reCAPTCHA after consecutive failed attempts

app/controllers/admin/budgets_controller.rb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/budgets_spec.rb
Fix an exception happening when trying to delete a budget which has a poll associated. 
Yes.
=> Don't destroy budgets with an associated poll

app/assets/javascripts/foundation_extras.js.coffee, app/assets/stylesheets/layout.scss, app/assets/stylesheets/participation.scss, app/views/custom/proposals/show.html.erb, app/views/proposals/show.html.erb, spec/features/proposals_spec.rb
Uses [Foundation sticky](https://foundation.zurb.com/sites/docs/sticky.html) on proposals supports button to show on mobile version.
Before, on proposals it was necessary a large amount of scroll to reach the support button (CTA) 😅 
Now the button appears sticky to bottom until the user scroll to comments 🎉 
=> Proposals support on mobile

.rubocop_basic.yml
Update Rubocop rule to allow lines up to 110 characters long.
Yes 😄
=> Allow lines to be 110 characters long by Rubocop

spec/controllers/users/confirmations_controller_spec.rb
Remove this deprecation warning appearing when running the test suite.
```
DEPRECATION WARNING: Using positional arguments in functional tests
has been deprecated, in favor of keyword arguments, and will be
removed in Rails 5.1.
Deprecated style:
get :show, { id: 1 }, nil, { notice: "Flash message" }
New keyword style:
get :show, params: { id: 1 }, flash: { notice: "Flash message" }
```
Yes 😄
=> Remove Rspec deprecation warning

spec/features/proposals_spec.rb
* Pull request #1745
Use the same window size for Capybara in every test.
Yes.
=> Resize Capybara window back to its original size

app/helpers/polls_helper.rb, app/views/polls/_poll_subnav.html.erb, spec/features/polls/polls_spec.rb
* Commits 5ca528d2 and e461c8d0
* Correctly generate links for polls without slugs
* Correctly use the slug in the link to a poll with no results nor stats
=> Generate navigation links for polls without a slug

app/controllers/legislation/annotations_controller.rb, lib/comment_tree.rb, lib/merged_comment_tree.rb, spec/features/comments/legislation_annotations_spec.rb
* Issue #1180
* [Comment in consul#2129](https://github.com/consul/consul/issues/2129#issuecomment-344741720) mentioning related flakies
* [Comment in consul#2455](https://github.com/consul/consul/pull/2455#issuecomment-401971618) showing the specs still fail sometimes
* [Travis build 24494, job 1](https://travis-ci.org/consul/consul/jobs/436433654) and [Travis build 11237, job 6](https://travis-ci.org/AyuntamientoMadrid/consul/jobs/508062387)
Fix the flaky specs that appeared in `spec/features/admin/feature_flags_spec.rb:8` ("Commenting legislation questions Index"), `spec/features/comments/legislation_annotations_spec.rb:143` ("Commenting legislation questions Turns links into html links") and `spec/features/comments/legislation_annotations_spec.rb:159` ("Commenting legislation …
=> Fix flaky annotation comments specs

app/controllers/admin/poll/polls_controller.rb, app/models/poll.rb, spec/features/admin/poll/polls_spec.rb
Hide polls created by users from proposals dashboard on `/admin/polls`
Remove polls created by users from proposals dashboard from list:
=> Hide polls created by users from proposals dashboard on admin poll index

app/controllers/admin/poll/polls_controller.rb, app/controllers/dashboard/polls_controller.rb, app/models/poll.rb, app/models/poll/question.rb, app/views/dashboard/polls/_form.html.erb, app/views/dashboard/polls/_poll.html.erb, config/locales/en/general.yml, config/locales/es/general.yml, config/routes/proposal.rb, spec/features/admin/poll/polls_spec.rb, spec/features/dashboard/polls_spec.rb
Include the changes made on https://github.com/consul/consul/pull/3476/.
- Replace "Name" label on dashboard polls form to "Survey title"
- Allow users delete dashboard polls (if doesn't have responses)
Yes, backport to CONSUL (the first commit its already on CONSUL).
=> Allow users to delete dashboard polls

app/models/setting.rb, config/deploy.rb, lib/tasks/settings.rake, spec/models/setting_spec.rb
* Continues PR #1746
* Remove the need to manually run rake tasks when we add a new setting
Yes.
=> Add new settings automatically on every deployment

spec/features/proposals_spec.rb
Update link to selected proposals on proposals spec.
No, this change its already made on https://github.com/consul/consul/pull/3567.
=> Update link to selected proposals on proposals spec

app/controllers/polls_controller.rb, app/controllers/valuation/budget_investments_controller.rb, app/models/budget/group.rb, app/models/budget/heading.rb, app/models/poll.rb, app/models/poll/booth.rb, app/models/user.rb, app/views/budgets/investments/_votes.html.erb, spec/models/budget/group_spec.rb, spec/models/budget/heading_spec.rb, spec/models/poll/booth_spec.rb, spec/models/poll/poll_spec.rb, spec/models/user_spec.rb
Using `joins` in a `has_many` association returns as many records as the associated table has. So if there are 2 budgets and 4 groups per budget, `Budget.joins(:groups)` will return 8 budgets.
In the case of translations, we need to order using a field in the translations table. So we need to join the table when ordering with SQL. However, we don't know which record to use in the translations table, since we need to consider globalize fallbacks.
Avoid duplicate records when using translations
Before these changes:
After these changes:
Yes.
=> Avoid duplicate records using translations

app/models/poll/officer.rb, config/locales/en/general.yml, config/locales/es/general.yml, spec/models/poll/officer_spec.rb
Avoid to raise an exception `Module::DelegationError` when trying to show the name and/or email of a poll officer whose user account has been deleted.
We'll show a message "User deleted" and "Email deleted" instead.
Yes
=> Show name and email for deleted poll officer's user account

app/views/proposals/_support_status.html.erb
Fix proposal variable on `views/proposals/_support_status.html.erb` partial.
No, this change it's already on CONSUL.
=> Fix proposal variable on support status partial

config/application.rb, config/locales/bs-BA/i18n.yml, config/locales/da-DK/i18n.yml, config/locales/hr-HR/i18n.yml, config/locales/it/i18n.yml
**PR:** https://github.com/consul/consul/pull/3571/
- Add Arabic, Bosnian, Croatian, Czech, Danish, Greek, and Turkish as available locales.
- Update locale names for Italian, Polish and Albanian.
No, this PR comes from upstream.
This PR contains a commit from a [Prerequisite PR](https://github.com/AyuntamientoMadrid/consul/pull/2030)
=> Add Arabic, Bosnian, Croatian, Czech, Danish, Greek, and Turkish to locales

app/models/budget/investment.rb, db/migrate/20190531173316_add_original_heading_id_to_investments.rb, db/schema.rb, lib/tasks/budgets.rake, spec/lib/tasks/budgets_spec.rb, spec/models/budget/investment_spec.rb
Investments can be reclassified to a different heading during the participatory budget process.
Whilst we are recording this change of heading in the `previous_heading_id` attribute, we are only keeping the _last_ heading. If there are multiple reclassifications we lose this chain of reclassifications.
Keep a record of the heading id in which an investment was created, just in case it gets reclassified multiple times.
Yes, this would be useful for other forks too 😌
To update attribute `original_heading_id` of existing investments run:
`bin/rake budgets:set_original_heading_id RAILS_ENV=production`
=> Add original heading id to investments

app/controllers/admin/stats_controller.rb, app/models/abilities/administrator.rb, app/views/admin/stats/budgets.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/stats_spec.rb
When accessing the URL `/admin/stats/budget_balloting?budget_id=X` for a budget in a phase prior to the balloting phase, the following error was raised due to the stats were not calculated yet. Instead, we'll now show a flash message.
```
NoMethodError:
undefined method `[]' for nil:NilClass
./app/controllers/admin/stats_controller.rb:82
```
Yes 😄
=> Avoid error when accessing final voting stats before the balloting phase

app/models/poll.rb, app/views/admin/poll/booth_assignments/show.html.erb, app/views/admin/poll/recounts/index.html.erb, spec/factories/polls.rb, spec/features/admin/poll/booth_assigments_spec.rb, spec/features/admin/poll/polls_spec.rb, spec/models/poll/poll_spec.rb
In the past, we had two numbers to track the total numbers of votes in a booth; what we called "final" recounts and "system" recounts. However, sytem recounts are not relevant anymore.
* Remove system recounts in the admin section, so administrators are not confused when they see two numbers for the same result.
Before these changes:
After these changes:
Yes.
=> Remove system recounts in the admin section

app/assets/stylesheets/participation.scss, app/views/custom/proposals/index.html.erb, app/views/custom/proposals/show.html.erb, app/views/proposals/_info.html.erb, app/views/proposals/index.html.erb, app/views/proposals/show.html.erb, spec/features/proposals_spec.rb
To simplify UI on selected proposals:
- Hide view mode on selected proposals index list.
- Hide on proposal show view:
- Proposal code.
- Related content section.
- Comments count.
**Index**
**Show**
=> Hide information on selected proposals

app/assets/stylesheets/dashboard.scss, app/controllers/dashboard_controller.rb, app/helpers/proposals_dashboard_helper.rb, app/views/dashboard/_menu.html.erb, app/views/dashboard/related_content.html.erb, config/locales/en/general.yml, config/locales/es/general.yml, config/routes/proposal.rb, spec/features/dashboard/dashboard_spec.rb
Add related content section on proposal dashboard.
=> Add related content section on proposal dashboard

app/models/poll/question.rb, spec/features/polls/results_spec.rb
When a poll is created, and any of the questions for that poll doesn't have any answer created, the following exception was raised when trying to see the results:
```
Failure/Error: question_answers.max_by {|answer| answer.total_votes }.id
ActionView::Template::Error:
undefined method `id' for nil:NilClass
./app/models/poll/question.rb:66:in `most_voted_answer_id'
```
Yes 😃
=> Avoid error for polls results

spec/spec_helper.rb
* Pull request consul#3601
When any helper, lib, mailer, model or view spec is executed after a feature, controller or request spec Globalize.fallbacks returns nil and this can cause some flaky specs. With this patch we are ensuring to initialize Globalize fallbacks between specs.
* Reset globalize fallbacks before every test, so previous tests don't affect the result of the current test
=> Reset globalize fallbacks before every test

app/controllers/admin/poll/polls_controller.rb, spec/features/admin/poll/booth_assigments_spec.rb
Hide polls created by users on admin poll booth assigments `/admin/polls/booth_assignments`.
=> Hide polls created by users on admin poll booth assigments

config/application.rb, spec/customization_engine_spec.rb
Related PR: [Load custom locales after everything is loaded #3663](https://github.com/consul/consul/pull/3663) 
Fix specs related with custom locales.
The line:
```
config.i18n.load_path += Dir[Rails.root.join("config", "locales", "**", "*.{rb,yml}")]
```
Was adding every locale under the `config/locales` folder, including the
ones inside `config/locales/custom/`. The files were loaded in the same
order as listed using `ls -f`.
So if the custom locales were loaded before the folder
`config/locales/#{I18n.locale}`, the default locales would override the
custom ones, and we want the custom locales to override the default
ones so CONSUL is easier to customize.
=> Load custom locales after everything is loaded

app/models/abilities/everyone.rb, app/models/report.rb, app/views/admin/shared/_show_results_fields.html.erb, app/views/budgets/_finished.html.erb, config/locales/en/activerecord.yml, config/locales/es/activerecord.yml, db/migrate/20190722133302_add_executions_to_reports.rb, db/schema.rb, spec/features/budgets/executions_spec.rb, spec/lib/migrations/reports_spec.rb, spec/models/abilities/everyone_spec.rb, spec/models/concerns/reportable.rb
An administrator can manage to show or hide information related to the tracking of participatory budgets (executions) from Backend (budget#edit).
Related content that we will display or hide:
- Executions tab on Budget#show Results/Stats page ()
- Finished participatory budgets section on Budget#index
- Backend(budget#edit)
- Budget#show
- Budget#index
Yes
=> Executions tab management

Gemfile.lock, app/assets/javascripts/legislation_annotatable.js.coffee, app/assets/javascripts/map.js.coffee, app/assets/javascripts/polls.js.coffee, app/assets/javascripts/stats.js.coffee, app/assets/stylesheets/admin.scss, app/helpers/map_locations_helper.rb, app/models/proposal.rb, app/views/custom/proposals/show.html.erb, config/locales/en/general.yml, config/locales/es/general.yml, spec/features/proposals_spec.rb, spec/helpers/map_locations_helper_spec.rb
- For geolocated proposals, display other similar proposals on the same map. When a proposal is not geolocated, neither the map nor the related proposals will be shown.
- We show proposals that have any of the tags of the original proposal.
- All the similar proposals are shown without being within a radius of the original proposal.
- The centre of the map and zoom level are maintained.
- There will be cases in which similar proposals will not be displayed on the map, they will be displayed if the user reduces the zoom level.
- A smaller icon is used than the original proposal, with a different colour, gradient or similar. Clicking on the map icon of a related proposal will display the title of the proposal and the link to allow navigation to all related proposals.
- This module only …
=> Add related proposal markers to proposal map

Gemfile.lock
The mimemagic gem has yanked version 0.3.5 (among others) due to license issues. 
More information about this topic: rails/rails#41750
Update the mimemagic dependency so the application is able to build.
=> Bump mimemagic to version 0.3.10 
