lib/tasks/proposals.rake
Adds rake tasks to add spaces to proposal titles and questions that are too short.
=> Adds rake task to make proposals valid

app/controllers/admin/stats_controller.rb, app/views/admin/stats/show.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, spec/factories.rb, spec/features/stats_spec.rb
- Adds stats for surveys completed and open question votes
=> Survey stats

app/models/redeemable_code.rb, db/migrate/20160202115644_create_redeemable_codes.rb, db/schema.rb, lib/tasks/codes.rake, spec/models/redeemable_code_spec.rb
Model and Rake task for automated generation of codes
=> Redeemable Codes Generation

app/assets/stylesheets/layout.scss, app/views/pages/help_translate.html.erb, app/views/shared/_locale_switcher.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/pages.en.yml, config/locales/pages.es.yml
=> Adds option to help translate on locale switcher

app/controllers/verification/letter_controller.rb, app/models/redeemable_code.rb, app/models/verification/letter.rb, spec/factories.rb, spec/features/verification/letter_spec.rb, spec/models/redeemable_code_spec.rb
Make verification/letter accept both letter codes & redeemable codes (https://github.com/consul/consul/issues/905)
=> Redeemable code check

lib/sms_api.rb
=> fixes exception thrown when sms api returns an invalid response

app/controllers/representatives_controller.rb, app/helpers/representatives_helper.rb, app/models/forum.rb, app/views/account/show.html.erb, app/views/representatives/new.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/responders.en.yml, config/locales/responders.es.yml, config/routes.rb, db/dev_seeds.rb, db/migrate/20160330142507_create_forums.rb, db/migrate/20160330143851_add_representative_id_to_users.rb, db/schema.rb, spec/factories.rb, spec/representatives_spec.rb
Adds basic delegation of a user to a Forum
[Pending design almost done]
=> Forum delegation

app/controllers/spending_proposals_controller.rb, app/helpers/spending_proposals_helper.rb, app/models/user.rb, app/views/spending_proposals/_counters.html.erb, app/views/spending_proposals/index.html.erb
This makes the District counter work. It also displays the "All city" and the district name in the counters.
=> Design 11 votes

app/views/spending_proposals/_sidebar.html.erb, config/locales/en.yml, config/locales/es.yml, spec/features/spending_proposals_spec.rb
If user can vote sidebar shows only the counters
If user can not vote (is only viewing) sidebar shows links to districts
=> show counters only to users that can vote sps

app/models/spending_proposal.rb, app/views/spending_proposals/show.html.erb, config/locales/en.yml, config/locales/es.yml, db/migrate/20160331151753_add_comments_count_to_spending_proposals.rb, db/schema.rb, spec/features/spending_proposals_spec.rb, spec/models/spending_proposal_spec.rb
Adds information to unfeasible spending proposals
=> Unfeasibles

app/models/abilities/administrator.rb, app/models/abilities/moderator.rb, spec/features/comments/spending_proposals_spec.rb, spec/models/abilities/administrator_spec.rb, spec/models/abilities/moderator_spec.rb
adds permissions to comment as moderator and admin in spending proposals
adds model and integration specs for spending proposal comments
=> Spending proposal comment specs

app/helpers/mailer_helper.rb
A fix for https://rollbar.com/voodoorai2000/Participacion/items/405/
=> adds mailer url for spending proposals

Gemfile, Gemfile.lock, app/assets/stylesheets/participation.scss, app/controllers/admin/api/stats_controller.rb, app/controllers/admin/stats_controller.rb, app/helpers/stats_helper.rb, app/views/admin/stats/show.html.erb, app/views/spending_proposals/show.html.erb, config/locales/activerecord.es.yml, config/locales/admin.en.yml, config/locales/admin.es.yml, config/locales/en.yml, config/locales/es.yml
Añade la PR de Boni para estadísticas de proyectos de inversión
Y hace un merge con upstream
=> Spending proposal monitoring

app/models/abilities/common.rb, app/models/spending_proposal.rb, app/models/user.rb, db/dev_seeds.rb, spec/features/votes_spec.rb, spec/models/abilities/common_spec.rb
- Allows Forums to vote investment projects
Closes #141
=> Forum votes

app/assets/stylesheets/custom.scss, app/controllers/forums_controller.rb, app/controllers/representatives_controller.rb, app/controllers/spending_proposals_controller.rb, app/helpers/forums_helper.rb, app/helpers/spending_proposals_helper.rb, app/models/forum.rb, app/models/user.rb, app/views/account/show.html.erb, app/views/forums/_votes.html.erb, app/views/forums/index.html.erb, app/views/forums/show.html.erb, app/views/representatives/_new.html.erb, app/views/spending_proposals/vote.js.erb, config/initializers/vote_extensions.rb, config/locales/en.yml, config/locales/es.yml, config/locales/responders.en.yml, config/locales/responders.es.yml, config/routes.rb, db/migrate/20160408130128_add_accepted_delegation_alert_to_users.rb, db/schema.rb, spec/features/forum_spec.rb, spec/features/votes_spec.rb, spec/helpers/comments_helper_spec.rb, spec/helpers/settings_helper_spec.rb, spec/helpers/spending_proposals_helper_spec.rb, spec/representatives_spec.rb
- Displays each Forum's votes
- Allows user to delete their representative
- Displays alert when voting if you have a representative
- Allows all users to see the delegation section
=> Forum supports

app/views/valuation/spending_proposals/edit.html.erb, app/views/valuation/spending_proposals/show.html.erb, config/locales/valuation.en.yml, config/locales/valuation.es.yml, spec/features/valuation/spending_proposals_spec.rb
- Adds vote count to spending proposals (valuation view)
=> Valuator votes

app/models/forum.rb, app/models/spending_proposal.rb, app/models/user.rb, config/initializers/vote_extensions.rb, spec/features/votes_spec.rb, spec/models/spending_proposal_spec.rb
- Takes into account delegated votes
- Does not take into account forum votes
=> Delegation count

app/assets/stylesheets/custom.scss, app/models/proposal.rb, app/views/proposals/_votes.html.erb, spec/features/open_plenary_spec.rb, spec/models/proposal_spec.rb
- Takes away the progress bar for open plenary proposals
- Takes away the number of needed supports for open plenary proposals
=> does not display supports for open plenary proposals

app/controllers/proposals_controller.rb, app/views/pages/processes_open_plenary.html.erb, db/dev_seeds.rb, spec/features/open_plenary_spec.rb
- hides advanced search
- makes search link host independent
- updates dev seeds
=> Open Plenary polish

Gemfile, Gemfile.lock, app/assets/stylesheets/custom.scss, app/views/admin/spending_proposals/show.html.erb, app/views/pages/_open_plenary_active.html.erb, app/views/pages/_open_plenary_closed.html.erb, app/views/pages/processes.html.erb, app/views/pages/processes_open_plenary.html.erb, config/locales/pages.en.yml, config/locales/pages.es.yml, spec/features/open_plenary_spec.rb
- Displays new information after official plenary closing time
=> Close plenary

app/controllers/admin/spending_proposals_controller.rb, app/models/abilities/administrator.rb, app/models/spending_proposal.rb, app/views/admin/spending_proposals/index.html.erb, app/views/admin/spending_proposals/priority.html.erb, config/routes.rb, spec/features/admin/spending_proposals_spec.rb, spec/models/spending_proposal_spec.rb
- Adds an admin summary of proposals that valuators should evaluate
=> displays priority proposals by valuator

db/dev_seeds.rb
- creates new users for forums
=> updates seeds

app/assets/stylesheets/layout.scss, app/controllers/users_controller.rb, app/views/users/_activity_page.html.erb, app/views/users/_ballot.html.erb, config/locales/en.yml, config/locales/es.yml, spec/features/users_spec.rb
Adds link to ballot to 'My activity' page
(only for author and if phase3 is active)
(last checkbox in 'Revisar mis votos' section of #182)
=> Link to ballot in 'My activity' page

app/controllers/ballots_controller.rb, app/models/ballot.rb, app/views/spending_proposals/_progress_bar.html.erb, spec/models/ballot_spec.rb, spec/models/spending_proposal_spec.rb
Adds `add` and `remove` methods to Ballot, with validation checks and geozone setting/resetting
=> Refactor and validation checks

app/assets/stylesheets/custom.scss, app/controllers/ballots_controller.rb, app/models/ballot.rb, app/views/ballots/show.html.erb, app/views/spending_proposals/_header.html.erb, app/views/spending_proposals/_progress_bar.html.erb, app/views/users/_ballot.html.erb, config/locales/en.yml, config/locales/es.yml, spec/features/ballots_spec.rb, spec/models/ballot_spec.rb, spec/models/spending_proposal_spec.rb
=> adds progress bar for district proposals

app/controllers/spending_proposals_controller.rb, app/helpers/spending_proposals_helper.rb, app/models/spending_proposal.rb, app/views/spending_proposals/_ballot.html.erb, config/locales/en.yml, config/locales/es.yml, spec/models/spending_proposal_spec.rb
adds hover message when proposal is more expensive than available money
=> Message when no money available

app/assets/stylesheets/custom.scss, app/controllers/spending_proposals_controller.rb, app/helpers/ballots_helper.rb, app/helpers/spending_proposals_helper.rb, app/models/ballot.rb, app/models/spending_proposal.rb, app/views/admin/spending_proposals/summary.html.erb, app/views/ballots/_add.html.erb, app/views/ballots/_ballot.html.erb, app/views/ballots/_remove.html.erb, app/views/ballots/_spending_proposal.html.erb, app/views/ballots/_spending_proposal_for_sidebar.html.erb, app/views/ballots/add.js.erb, app/views/ballots/remove.js.erb, app/views/spending_proposals/_progress_bar.html.erb, app/views/spending_proposals/_sidebar.html.erb, app/views/spending_proposals/show.html.erb, app/views/users/_ballot.html.erb, config/locales/en.yml, config/locales/es.yml, spec/factories.rb, spec/features/ballots_spec.rb, spec/features/spending_proposals_spec.rb, spec/models/ballot_spec.rb
Adds and removes balloted proposals from sidebar
=> balloted proposals in sidebar

app/models/ballot.rb, app/views/spending_proposals/_progress_bar.html.erb, spec/features/ballots_spec.rb, spec/features/spending_proposals_spec.rb, spec/models/ballot_line_spec.rb, spec/models/ballot_spec.rb, spec/models/spending_proposal_spec.rb
Madrid's district numbers added to Ballot & Progress bar
=> District budgets

app/models/ballot_line.rb, spec/models/ballot_line_spec.rb
Fixes bug where, if you had insufficient funds for your District, you could not vote in City proposals.
=> validates money available for current proposal

app/controllers/spending_proposals_controller.rb, app/models/spending_proposal.rb, app/views/spending_proposals/index.html.erb, config/locales/en.yml, config/locales/es.yml, spec/features/spending_proposals_spec.rb
Adds order by price desc for phase3 spending proposals
=> Order by price

app/models/ballot.rb
ballot lines should be deleted on ballot.destroy
=> ballot lines dependent on ballot

app/views/forums/show.html.erb, spec/features/forum_spec.rb
Forums has not decided yet on final votes.
This PR temporarily deactivates previous supports list in forum page
It will be reactivated later with phase3 votes
=> Empty Forum pages

app/controllers/admin/stats_controller.rb, app/views/admin/stats/show.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, spec/features/admin/stats_spec.rb
Añade a las estadísticas:
Número de usuarios que han votado algún proyecto de inversión.
Número de votos totales en proyectos de inversión.
=> adds stats for investment projects

app/views/spending_proposals/_header.html.erb, spec/models/abilities/common_spec.rb
Remove "Check my votes" if user is not level 2 or 3
=> Show button only if can vote

app/controllers/admin/api/stats_controller.rb, app/controllers/admin/stats_controller.rb, app/helpers/stats_helper.rb, app/views/admin/stats/_graph.html.erb, app/views/admin/stats/graph.html.erb, app/views/admin/stats/show.html.erb, config/initializers/ahoy.rb, config/locales/admin.en.yml, config/locales/admin.es.yml, config/routes.rb, spec/controllers/admin/api/stats_controller_spec.rb, spec/features/admin/stats_spec.rb, spec/features/campaigns_spec.rb
- Substitutes graphs for links to individual pages with the corresponding graph.
=> Improves performance of stats dashboard

app/models/abilities/administrator.rb, spec/models/abilities/administrator_spec.rb
- Allows admins to see spending proposal's evaluations.
=> admins should be able to view spending proposal's evaluations

app/models/abilities/common.rb, app/models/forum.rb, app/views/forums/_ballot.html.erb, app/views/forums/show.html.erb, config/locales/en.yml, db/dev_seeds.rb, spec/features/forum_spec.rb, spec/features/representatives_spec.rb, spec/models/abilities/common_spec.rb
- Allows forums to ballot proposals
- Displays a forum's balloted proposals
=> Forum permissions

app/views/spending_proposals/show.html.erb, config/locales/en.yml, config/locales/es.yml, spec/features/spending_proposals_spec.rb
adds price explanation to feasible spending proposals show page
=> adds price explanation to feasible sps

app/controllers/admin/stats_controller.rb, app/views/admin/stats/spending_proposals.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, spec/features/admin/stats_spec.rb
stats for participatory budgets with data of city/district wide voters
=> adds budget stats on city/district voters

app/assets/stylesheets/admin.scss, app/controllers/admin/spending_proposals_controller.rb, app/models/abilities/administrator.rb, app/models/ballot.rb, app/models/ballot_line.rb, app/models/spending_proposal.rb, app/views/admin/spending_proposals/index.html.erb, app/views/admin/spending_proposals/results.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, config/routes.rb, db/migrate/20160615074547_add_ballot_lines_counter_cache_to_spending_proposals.rb, db/schema.rb, lib/tasks/spending_proposals.rake, spec/factories.rb, spec/features/admin/spending_proposals_spec.rb
Implements results page in Admin for participaroty budget final voting
=> Participatory budget final voting: admin results page

doc/locales/fr.yaml, doc/locales/pt-br.yaml
=> adds doc/locales folder with contributed locales

app/models/forum.rb, app/views/forums/show.html.erb, config/locales/admin.es.yml, config/locales/en.yml, config/locales/es.yml, spec/features/forum_spec.rb
Muestra un mensaje cuando un foro no ha votado propuestas de ciudad ó propuestas de distrito.
Closes #268
=> Votos de un Foro

app/assets/javascripts/application.js, app/assets/javascripts/countdown.js.coffee, app/assets/stylesheets/custom.scss, app/helpers/spending_proposals_helper.rb, app/views/debates/index.html.erb, app/views/proposals/index.html.erb, app/views/shared/_budget_counter.html.erb, app/views/shared/_budget_counter_banner.html.erb, app/views/spending_proposals/welcome.html.erb, app/views/welcome/index.html.erb, config/locales/en.yml, config/locales/es.yml
Pending review and add some tests 😄
=> sps countdown

app/controllers/admin/stats_controller.rb, app/controllers/application_controller.rb, app/controllers/users/registrations_controller.rb, app/views/admin/stats/show.html.erb, app/views/admin/stats/user_invites.html.erb, app/views/mailer/user_invite.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, config/routes.rb, spec/features/user_invites_spec.rb, spec/support/common_actions.rb
Adds stats for users that have:
- Clicked the signup link in the invitation email
- Clicked the signup button after clicking the signup link in the invitation email
=> Tracks signup from invitation emails

app/assets/stylesheets/custom.scss, app/controllers/ballot_lines_controller.rb, app/controllers/representatives_controller.rb, app/helpers/spending_proposals_helper.rb, app/models/abilities/common.rb, app/views/ballots/_ballot.html.erb, app/views/forums/index.html.erb, app/views/forums/show.html.erb, app/views/spending_proposals/_sidebar.html.erb, app/views/spending_proposals/index.html.erb, app/views/spending_proposals/show.html.erb, app/views/spending_proposals/welcome.html.erb, app/views/welcome/_featured_welcome.html.erb, app/views/welcome/index.html.erb, config/locales/en.yml, config/locales/es.yml, config/routes.rb, spec/features/ballots_spec.rb, spec/features/representatives_spec.rb, spec/features/spending_proposals_spec.rb, spec/models/abilities/common_spec.rb
Para que este PR funcione correctamente hay que:
1) Dejar activada la fase 3
2) Desactivar las votaciones finales
Esto debe mergearse para cerrar las votaciones
=> Close sps ballots

app/controllers/admin/spending_proposals_controller.rb, app/models/spending_proposal.rb, db/migrate/20160703190103_add_compatible_to_spending_proposals.rb, db/schema.rb, spec/features/admin/spending_proposals_spec.rb, spec/models/spending_proposal_spec.rb
Displays only compatible spending proposals in results
=> Compatible spending proposals

app/assets/stylesheets/custom.scss, app/controllers/admin/spending_proposals_controller.rb, app/models/abilities/administrator.rb, app/models/spending_proposal.rb, app/views/admin/spending_proposals/edit.html.erb, app/views/admin/spending_proposals/results.html.erb, app/views/admin/spending_proposals/show.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, spec/features/admin/spending_proposals_spec.rb, spec/models/abilities/administrator_spec.rb, spec/models/spending_proposal_spec.rb
- Displays incompatible proposals in results page
- Adds checkbox to mark spending proposals as incompatible
=> Admin compatible sps

app/models/user.rb, app/views/admin/spending_proposals/results.html.erb, app/views/admin/users/show.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml
Mejora la información de contacto de las propuestas ganadoras
=> Información de contacto

app/controllers/admin/api/stats_controller.rb, app/views/admin/stats/show.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, spec/features/admin/stats_spec.rb
Añade un gráfico con los registros por día de usuarios no verificados
=> Stats user level1

app/controllers/benches_controller.rb, app/models/user.rb
renaming method, `voted_for?` was colliding with acts_as_votable
=> Fixes weird delegated votes spec 

app/views/admin/stats/proposal_notifications.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, spec/features/admin/stats_spec.rb
Adds checks for deleted proposals and displays corresponding message.
=> Proposal notification stats

app/views/mailer/comment.html.erb, app/views/mailer/proposal_notification_digest.html.erb, app/views/mailer/reply.html.erb, app/views/proposal_notifications/show.html.erb, app/views/proposals/_notifications.html.erb
adds simple format and autolinking to notifications body
=> Format to proposal notifications

app/mailers/mailer.rb, lib/email_digest.rb, spec/features/emails_spec.rb
Sends only notifications for the top proposal
=> Proposals notifications

db/schema.rb
budget tables should not be here
=> removes unused budget feature info from schema.rb

app/views/custom/probes/plaza/selecting.html.erb, config/routes.rb, spec/features/custom/probes_spec.rb
- Adds links from title, image and comments to show
=> adds links to show from index

spec/models/proposal_spec.rb
=> uses let instead of @s

lib/tasks/probe_plaza.rake
Plaza: migrates comments from debate to probe_option and destroys debate
=> adds rake task to migrate probe options comments

app/helpers/users_helper.rb, app/models/custom/probe_option.rb
- Fixes exception in user activity where probe needed a paranoia method implementation and the use of commentable_title for a probe
=> Probe user activity

app/controllers/welcome_controller.rb, spec/features/admin/stats_spec.rb, spec/features/admin_spec.rb, spec/features/custom/probe_option_comments_spec.rb, spec/features/custom/probe_options_spec.rb, spec/features/custom/probes_spec.rb, spec/features/debates_spec.rb, spec/features/home_spec.rb, spec/features/moderation_spec.rb, spec/features/proposal_notifications_spec.rb, spec/features/proposals_spec.rb, spec/features/valuation_spec.rb, spec/features/welcome_spec.rb, spec/models/debate_spec.rb, spec/spec_helper.rb, spec/support/common_actions.rb
Makes Plaza España probe the root path for logged in users
=> Home Plaza España

app/assets/javascripts/annotatable.js.coffee, app/views/pages/carta-servicios-ayuda-a-domicilio.html.erb, app/views/pages/carta-servicios-centro-prevencion-deterioro-cognitivo.html.erb, app/views/pages/carta-servicios-centros-de-dia.html.erb, app/views/pages/carta-servicios-centros-de-mayores.html.erb, app/views/pages/carta-servicios-teleasistencia.html.erb, app/views/pages/processes.html.erb, app/views/pages/processes/human_rights.html.erb, app/views/pages/processes/human_rights_plan.html.erb, config/locales/pages.en.yml, config/locales/pages.es.yml, db/dev_seeds.rb, spec/features/human_rights_spec.rb
✋   Wait until November 5 to merge 🕐
=> [WIP] Read only annotations

app/assets/javascripts/tracks.js.coffee, app/controllers/concerns/analytics.rb, app/controllers/proposals_controller.rb, app/views/comments/new.js.erb, spec/features/tracks_spec.rb
- does not send empty data hash
- sends ranking value instead of placeholder string
- does not resend event on form error
=> Analytics polish

app/views/pages/processes.html.erb, app/views/pages/processes/subvention_ordinance.html.erb, app/views/welcome/_cards.html.erb, config/locales/custom.en.yml, config/locales/custom.es.yml, config/locales/pages.en.yml, config/locales/pages.es.yml
✋  Don't merge until 22/11 (00.00h)
=> [WIP] closes subvention ordinance process

app/controllers/custom/budget_polls_controller.rb, app/views/custom/budget_polls/new.html.erb, config/locales/activerecord.en.yml, config/locales/activerecord.es.yml, db/migrate/20161123141045_add_help_to_budget_polls.rb, db/schema.rb
=> Budget polls polish

app/assets/stylesheets/custom.scss, app/views/pages/processes.html.erb, app/views/pages/processes/vallecas/index.html.erb, app/views/welcome/_cards.html.erb, config/locales/custom.en.yml, config/locales/custom.es.yml, config/locales/pages.en.yml, config/locales/pages.es.yml, config/routes.rb
✋  **Pending to add** debates related with this process.
=> [WIP] Process Vallecas

app/views/budgets/investments/_sidebar.html.erb, app/views/budgets/show.html.erb, spec/features/tags/budget_investments_spec.rb
Loads investment form with turbolinks to make js tag selection work
=> Budgets tags

app/views/welcome/index.html.erb
Removes "Register/Login" links in welcome page when user is signed-in
=> Welcome: no register link for already registered users

app/models/poll/question.rb, app/views/polls/questions/show.html.erb, lib/tasks/polls.rake
Adds a `rake polls:import_2017` task (needs the Madrid Geozones to exist, for example after a `rake db:dev_seeds`)
"Global" polls (Plaza España,  Castellana) and proposal-derived polls are not included here.
=> Polls import from districts

app/controllers/officing/nvotes_controller.rb, app/controllers/officing/voters_controller.rb, lib/tasks/polls.rake, spec/features/officing/nvotes_spec.rb, spec/features/officing/voters_spec.rb
- Displays real polls in officing section
- Adds rake task to set temporary nvotes id for all polls
=> Vote upcoming polls

app/controllers/application_controller.rb, app/controllers/officing/nvotes_controller.rb, app/controllers/polls/nvotes_controller.rb, app/models/poll/nvote.rb, config/routes.rb, spec/features/polls/nvotes_spec.rb, spec/models/poll/nvote_spec.rb
- Parses callback from Nvotes once a user has voted
- Stores a Poll::Voter if the callback is valid
=> Nvotes callback

lib/tasks/polls.rake
- adds a line before @options
- adds column header for options
- nvotes' question ids should start with 0
- displays new lines in descriptions
=> Polish Nvotes tsv

lib/tasks/polls.rake
- updates nvotes poll ids
- creates convenience task (rake polls:setup) to run all associated tasks
=> Polish poll's rake taks

lib/tasks/polls.rake
- Removes description from Citizen Proposals and Plaza España
- Simplifies title of main poll
- Updates nvote's poll ids
- Removes obsolete voters and votes
=> Removes poll descriptions from rake task

app/controllers/budgets/investments_controller.rb, app/controllers/custom/probes_controller.rb, app/controllers/human_rights_controller.rb, app/controllers/spending_proposals_controller.rb
rescues random_seed to avoid error 500
=> Avoid error 500

app/views/pages/processes.html.erb, app/views/pages/processes/linea_madrid/index.html.erb, app/views/welcome/_cards.html.erb, config/locales/custom.en.yml, config/locales/custom.es.yml, config/locales/pages.en.yml, config/locales/pages.es.yml, config/routes.rb
✋  **Don't merge**
- Pending to create associated debates.
=> [WIP] Proceso Linea madrid

app/controllers/officing/voters_controller.rb, app/models/poll.rb, app/models/poll/nvote.rb, app/models/poll/officer_assignment.rb, app/models/poll/voter.rb, app/models/user.rb, db/migrate/20170208175122_add_traceability_fields_to_nvotes.rb, db/schema.rb, spec/factories.rb, spec/features/officing/nvotes_spec.rb, spec/features/polls/nvotes_spec.rb, spec/models/poll/nvote_spec.rb
Stores the officing assignment and the booth assignment on each nvote and voter, when they are available
=> Voter traceability

app/controllers/polls/nvotes_controller.rb, app/models/poll.rb, app/models/poll/nvote.rb, app/views/polls/nvotes/_iframe.html.erb, app/views/polls/nvotes/new.html.erb, spec/features/officing/nvotes_spec.rb, spec/features/polls/nvotes_spec.rb, spec/models/poll/nvote_spec.rb, spec/support/common_actions.rb
- Validates that the callback after a successful vote comes from Nvotes
=> Validates Nvotes callback

app/controllers/admin/poll/booths_controller.rb, app/controllers/officing/voters_controller.rb, app/views/admin/poll/booths/_form.html.erb, app/views/officing/voters/new.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, db/migrate/20170211192737_add_physical_to_poll_booths.rb, db/schema.rb, spec/features/admin/poll/booths_spec.rb, spec/features/officing/nvotes_spec.rb, spec/features/officing/voters_spec.rb, spec/support/common_actions.rb
- Adds option to set booth as being physical or digital
- Displays vote with tablet or vote in physical booth correspondingly
=> Booth types

config/sitemap.rb
proposal_ballots is deprecated
added budgets & polls indexes paths
=> updates sitemap

app/controllers/admin/stats_controller.rb, app/controllers/officing/voters_controller.rb, app/models/poll/answer.rb, app/models/poll/nvote.rb, app/models/poll/voter.rb, app/views/admin/stats/polls.html.erb, app/views/admin/stats/show.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, config/routes.rb, db/migrate/20170212130926_add_origin_to_poll_voters.rb, db/schema.rb, spec/factories.rb, spec/features/admin/stats_spec.rb, spec/features/polls/voter_spec.rb, spec/models/poll/voter_spec.rb, spec/support/common_actions.rb
- Adds origin to poll voter (web or booth)
- Adds stats for total voters via web and booths
- Adds stats for total voters by poll
=> Polls stats

app/models/officing/residence.rb, lib/census_api.rb, lib/tasks/users.rake, spec/features/officing/residence_spec.rb, spec/lib/census_api_spec.rb, spec/models/officing/residence_spec.rb
* Uses the document_number returned by census
* Adds a rake task to update existing users with that number
=> Officing response document_number update

app/controllers/officing/base_controller.rb, app/controllers/officing/booth_controller.rb, app/views/layouts/_officing_booth.html.erb, app/views/layouts/admin.html.erb, app/views/officing/booth/new.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, config/locales/officing.en.yml, config/locales/officing.es.yml, db/dev_seeds.rb, spec/features/officing/booth_spec.rb, spec/features/officing/residence_spec.rb
- Choose booth location instead of booth name
- Displays single booth in select for any number of polls
- Always displays officing booth in layout
=> Officer booth polish

app/views/admin/poll/booth_assignments/show.html.erb, app/views/layouts/admin.html.erb, app/views/officing/final_recounts/new.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, config/locales/officing.en.yml, config/locales/officing.es.yml, spec/features/admin/poll/booth_assigments_spec.rb, spec/features/officing/final_recount_spec.rb
Final recounts are not daily now. Only one final recount is created (assigned internally to poll's last voting day).
Total counts added to admin.
=> Final recounting changes

app/views/officing/voters/new.html.erb, spec/features/officing/voters_spec.rb
fixes exception for votes in tablet where user has already voted on all polls
=> Voting in tablet

app/assets/stylesheets/custom.scss, app/controllers/officing/letters_controller.rb, app/models/poll/letter_officer_log.rb, app/views/officing/letters/new.html.erb, app/views/officing/letters/show.html.erb, config/routes.rb, db/migrate/20170219213227_add_postal_code_to_poll_letter_officing_log.rb, db/schema.rb, spec/features/officing/letters_spec.rb
- Displays letter message in separate page
=> Letter messages

app/assets/stylesheets/custom.scss, app/controllers/officing/letters_controller.rb, app/models/officing/residence.rb, app/models/poll/letter_officer_log.rb, app/views/officing/letters/show.html.erb, app/views/officing/letters/verify_name.html.erb, config/routes.rb, db/migrate/20170221184626_add_census_name_and_census_postal_code_to_letter_officer_log.rb, db/schema.rb, spec/features/officing/letters_spec.rb
- Allows validation of name when postal code is blank
=> Letter postal code

app/controllers/polls_controller.rb, app/models/stat.rb, app/views/polls/stats_2017.html.erb, app/views/polls/stats_2017/_age.html.erb, app/views/polls/stats_2017/_gender.html.erb, db/migrate/20170225091223_create_stats.rb, db/schema.rb, lib/tasks/stats.rake, spec/models/stat_spec.rb
Model Stat.
For cases when numbers are not gonna change often, we can now store namespaced arbitrary integers in db and re/generate them via rake tasks.
=> Stats redux

app/views/polls/stats_2017.html.erb, lib/tasks/stats.rake
Automagically updated every time the rake task runs
=> Cache to polls 2017 stats page

app/views/polls/results_2017.html.erb
same cache as stats - expired automagically everytime stats are
recalculated via rake task
=> adds cache to results page

app/models/abilities/administrator.rb, app/models/abilities/everyone.rb, config/routes.rb
✋  Don't merge until polls results published
=> [WIP] Landing vota

config/locales/mailers.es.yml, lib/tasks/budgets.rake
- Temporarily updates unfeasible email subject
=> adds rake task to resend unfeasible emails

app/assets/stylesheets/custom.scss, app/helpers/budgets_helper.rb, app/views/budgets/investments/_investment_show.html.erb, app/views/budgets/investments/_votes.html.erb, app/views/mailer/budget_investment_unfeasible.html.erb, app/views/pages/budgets/welcome.html.erb, app/views/welcome/_budgets_module.html.erb, app/views/welcome/index.html.erb, config/locales/mailers.en.yml, config/locales/mailers.es.yml, spec/features/budgets/investments_spec.rb
References https://github.com/AyuntamientoMadrid/consul/issues/506
=> Budget polish support phase

app/views/pages/processes.html.erb, app/views/pages/processes/linea_madrid/index.html.erb, app/views/welcome/_cards.html.erb, app/views/welcome/index.html.erb, config/locales/custom.en.yml, config/locales/custom.es.yml
✋  Don't merge until 11/03 at 00.00h
=> Closes processes

app/controllers/budgets/investments_controller.rb, app/controllers/custom/probes_controller.rb
fixes issue in pro where votes are not shown in random order list
=> Randomize investments

app/views/pages/processes.html.erb, app/views/pages/processes/movilidad/index.html.erb, app/views/welcome/_cards.html.erb, app/views/welcome/index.html.erb, config/locales/custom.en.yml, config/locales/custom.es.yml
✋  Don't merge until 00.00h 15/03
=> closes movilidad process

Gemfile.lock
sec alert: https://gemnasium.com/github.com/AyuntamientoMadrid/consul/alerts
=> updates rubyzip

app/controllers/admin/budget_investments_controller.rb, app/views/admin/budget_investments/edit.html.erb, app/views/admin/budget_investments/show.html.erb, app/views/budgets/investments/_investment.html.erb, app/views/budgets/investments/_investment_show.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, db/migrate/20170314180135_add_label_to_budget_investments.rb, db/schema.rb, spec/features/admin/budget_investments_spec.rb
Adds public label field to investments and edit capabilities to admins
=> Labeling of budget investments

app/models/budget/investment.rb, spec/models/budget/investment_spec.rb
- allows voting in any investment due to a reclasification
=> Reclasification

app/models/budget/investment.rb, spec/models/budget/investment_spec.rb
fixes calculation of reclasifications
=> Reclasifications

app/controllers/valuation/budget_investments_controller.rb, app/views/shared/_admin_login_items.html.erb, app/views/valuation/budget_investments/index.html.erb, config/locales/valuation.en.yml, config/locales/valuation.es.yml, db/dev_seeds.rb, spec/features/valuation/budget_investments_spec.rb
- displays link to valuation section
- displays only the top 5 investments to evaluators
- updates dev seeds for valuators
=> Budget evaluation

app/views/pages/processes.html.erb, app/views/pages/processes/publicity/index.html.erb, app/views/welcome/_cards.html.erb, app/views/welcome/index.html.erb, config/locales/custom.en.yml, config/locales/custom.es.yml, config/locales/pages.en.yml, config/locales/pages.es.yml, config/routes.rb
✋  Don't merge until 27/03 at 00.00h
=> adds publicity process

app/controllers/valuation/budget_investments_controller.rb, spec/features/valuation/budget_investments_spec.rb
=> increase investments listed in valuators interface

app/views/pages/processes.html.erb, app/views/pages/processes/buildings/index.html.erb, app/views/welcome/_cards.html.erb, app/views/welcome/index.html.erb, config/locales/custom.en.yml, config/locales/custom.es.yml
✋  Don't merge until 05/04 at 00.00h
=> close buildings process

app/mailers/mailer.rb
=> cuts comments emails in production

spec/features/polls/nvotes_spec.rb, spec/features/polls/voter_spec.rb, spec/spec_helper.rb
Resets driver after manually setting headers
=> Fixes flaky missing template spec

app/views/pages/processes/index.html.erb, app/views/pages/processes/vicalvaro/index.html.erb, app/views/pages/processes/villaverde/index.html.erb, app/views/welcome/_cards.html.erb, app/views/welcome/index.html.erb, config/locales/custom.en.yml, config/locales/custom.es.yml
✋  Don't merge yet! waiting for confirmation.
=> Close processes

app/views/pages/processes/index.html.erb, app/views/pages/processes/publicity/index.html.erb, app/views/welcome/index.html.erb
✋  Don't merge until 26/04 at 00.00h
=> close publicity process

app/controllers/budgets/ballot/lines_controller.rb, app/controllers/budgets/investments_controller.rb
Fixes:
"In investment's index, after adding and removing investments, refresh the other voting buttons"
=> Budgets button hover

app/controllers/admin/stats_controller.rb, app/models/budget.rb, app/views/admin/stats/budget_balloting.html.erb, app/views/admin/stats/budget_supporting.html.erb, app/views/admin/stats/budgets.html.erb, app/views/admin/stats/show.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, config/routes.rb, spec/features/admin/stats_spec.rb
Adds final voting stats for budgets to admin.
Cleans up a little previous support-phase stats.
=> Admin budgets stats

app/helpers/users_helper.rb, app/views/users/_interests.html.erb, app/views/users/show.html.erb, config/locales/en/general.yml, config/locales/es/general.yml, spec/features/users_spec.rb
Pull master branch from consul and manually merge conflicts
Add empty interests list message.  https://github.com/consul/consul/pull/1769
Manually merging conflicts
No need
Lets see if no issues :)
To pre and test there
None
=> Consul pull

app/views/pages/processes/once_plazas/index.html.erb
What
====
- Updates text on once plazas process page.
=> Once plazas page

app/assets/stylesheets/custom/_landings.scss, app/assets/stylesheets/custom/_vota.scss, app/views/polls/info_2017.html.erb
What
====
- Improve color contrast for accessibility on "polls info" and "haz madrid" landings.
=> Color contrast

app/views/polls/_poll_group.html.erb
What
====
Removed questions anchor from "participate in poll" button in polls list.
Test
====
As usual.
Deployment
==========
As usual.
=> Removed anchor from participate in poll button

app/views/admin/poll/questions/answers/images/index.html.erb, app/views/polls/_gallery.html.erb
What
====
Ordered images in a more natural order.
Test
====
As usual.
Deployment
==========
As usual.
=> Fixed answer gallery order

app/views/admin/poll/questions/show.html.erb, app/views/polls/questions/_answers.html.erb, app/views/polls/show.html.erb
Hot Fix reversing answer order
=> Hot Fix 🔥👨‍🚒  reverse Poll Question Answer order 

app/assets/stylesheets/custom/_welcome.scss, app/views/pages/more_info/index_october_2017.html.erb, app/views/welcome/_header.html.erb, config/locales/custom/en/custom.yml, config/locales/custom/es/custom.yml
Qué
====
- Cambia el header de la página welcome para promocionar las nuevas votaciones.
⚠️🦄 **PENDIENTE de aprobación antes de mergear** ⚠️
=> Welcome page

app/views/pages/more_info/index.html.erb
What
====
- Fixes minor html markup error on more info page 🙈
=> More info page

app/controllers/polls/questions_controller.rb, app/helpers/tracks_helper.rb, app/views/polls/questions/answer.js.erb, config/locales/tracking.en.yml, config/locales/tracking.es.yml, spec/features/tracks_spec.rb
What
====
- Adds analytics for voting in a poll
- Fixes gender attribute sent in analytics
How
===
- Adding call to log event after voting a poll
- Downcasing gender value used in translations and fixing false positive in spec
Test
====
- Check in Piwik once it's deployed to Pro (we don't have analytics in Pre yet)
Deployment
==========
- As usual
Warnings
========
- None
=> Polls analytics

app/assets/stylesheets/participation.scss
Bring Poll Comment email notification fix https://github.com/consul/consul/pull/2039
=> Consul Pull ⬇️

app/assets/stylesheets/custom.scss, app/models/poll.rb, app/views/legislation/processes/debate.html.erb, app/views/legislation/processes/phase_empty.html.erb, app/views/legislation/processes/phase_not_open.html.erb, app/views/pages/more_info/polls/february_2017.html.erb, app/views/pages/more_info/polls/index.html.erb, app/views/pages/more_info/polls/october_2017.html.erb, app/views/polls/index.html.erb, app/views/polls/info_2017.html.erb, config/routes.rb, spec/features/emails_spec.rb
https://github.com/AyuntamientoMadrid/consul/pull/933
https://github.com/AyuntamientoMadrid/consul/pull/932
Bring Poll Comment email notification fix consul#2039
Manually uploaded file `system/legislations/processes/25/resumen_plan_estrategico_zonas_verdes.pdf`
=> Deploy to Pro 🚀

app/views/pages/more_info/polls/october_2017.html.erb
What
====
- Adds link on polls more info page.
=> Polls more info page

app/assets/javascripts/polls.js.coffee, app/controllers/polls/questions_controller.rb, app/controllers/polls_controller.rb, app/models/poll/answer.rb, app/models/poll/voter.rb, app/views/polls/_show.html.erb, app/views/polls/questions/_answers.html.erb, app/views/polls/questions/_error.html.erb, app/views/polls/questions/answer.js.erb, app/views/polls/questions/error.js.erb, app/views/polls/show.html.erb, config/locales/en/general.yml, config/locales/es/general.yml, db/schema.rb, spec/features/officing_spec.rb, spec/features/polls/polls_spec.rb, spec/features/polls/voter_spec.rb, spec/models/poll/answer_spec.rb, spec/models/poll/voter_spec.rb, spec/support/common_actions.rb
What
====
Added message in case vote token is not properly received.
Screenshots
===========
Test
====
As usual.
Deployment
==========
As usual.
=> Token error

app/views/custom/layouts/_header.html.erb, app/views/polls/_show.html.erb, app/views/shared/_admin_login_items.html.erb
What
====
- Shows correctly admin menu, and officers menu on header.
- Adds missing id for see projects link on polls show.
=> Polls fixes

app/views/welcome/_header.html.erb, config/locales/custom/en/custom.yml, config/locales/custom/es/custom.yml
What
====
- Changes texts on welcome page header.
=> Welcome page header

app/controllers/admin/stats_controller.rb
What
====
- Display stats for main square polls
=> Displays stats for polls ended in the last week

app/controllers/admin/poll/shifts_controller.rb, app/helpers/shifts_helper.rb, app/models/poll/booth.rb, app/views/admin/poll/shifts/_form.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml
Includes changes that allow recounting polls to get shifts creating on their associated booths
=> Deploy to PRO

app/assets/stylesheets/custom/_polls_results_stats.scss, app/models/poll/stats.rb, app/views/polls/_poll_group.html.erb, app/views/polls/_poll_subnav.html.erb, app/views/polls/_results_2018.html.erb, app/views/polls/_stats_2018.html.erb, app/views/polls/results_2018.html.erb, app/views/polls/stats_2018.html.erb, app/views/welcome/_header.html.erb, lib/tasks/polls_stats_2018.rake
This will make welcome home display the results page to the 11 polls .
Before deploying (or just seconds after) run in console:
```
polls = Poll.where(starts_at: Time.parse('08-10-2017'), ends_at: Time.parse('22-10-2017'))
polls.each do |poll|
poll.update_attribute(:results_enabled, true)
poll.update_attribute(:stats_enabled, true)
end
```
=> DEPLOY TO PRO  11 Polls

app/controllers/notifications_controller.rb
What
====
- Fixes notification link for comments on legislation proposals
Test
====
- Pending, coming soon, first let's get this exception fixed!
- Trying manually in Preproduction environment
=> Hotfix - Legislation proposal notifications

app/models/legislation/proposal.rb, app/views/legislation/proposals/_form.html.erb, spec/models/legislation/proposal_spec.rb
What
====
- Increases a legislations proposal's question max length to 500 characters
Test
====
- Manually test it in staging environment
=> Legislation proposal question's length

app/views/legislation/proposals/show.html.erb
What
====
- Fixes legislation process social urls 😄
=> Legislation process urls

config/routes.rb
What
====
- Adds a friendly url for Open Plenary 2017
=> Adds open plenary's named url

app/views/legislation/processes/_custom_documents.html.erb, app/views/legislation/processes/_documents_process_28.html.erb, app/views/legislation/processes/_documents_process_29.html.erb, app/views/legislation/processes/_documents_process_30.html.erb
What
====
- Adds custom documents for processes 28, 29 and 30.
=> Legislation processes custom documents 

app/views/pages/more_info/budgets/_welcome_header_finished.html.erb
What
====
- Replaces budgets welcome page document (the file it's already upload to server) 📝 
Deployment
==========
⚠️  DON'T merge and deploy until November 11th ⚠️
=> Budgets welcome document

app/models/direct_message.rb, spec/models/direct_message_spec.rb
Reverts AyuntamientoMadrid/consul#1018
=> Revert "Consul Pull"

app/assets/stylesheets/custom.scss, app/views/legislation/processes/_custom_results.html.erb, app/views/legislation/processes/_results_process_24.html.erb, app/views/legislation/processes/debate.html.erb, app/views/legislation/processes/phase_empty.html.erb, app/views/legislation/processes/phase_not_open.html.erb, app/views/legislation/processes/proposals.html.erb
Qué
====
- Añade las preguntas y propuestas más votadas en el proceso de Pleno Abierto.
=> Resultados Pleno Abierto

app/views/pages/landings/sitesientesgato.html.erb
What
====
- Removes old links on `sitesientesgato landing page`.
=> Si te sientes gato 😺

app/assets/stylesheets/custom/_polls_results_stats.scss, app/views/debates/_popular.html.erb, app/views/legislation/proposals/_categories.html.erb, app/views/polls/_results_2018.html.erb, app/views/polls/index.html.erb, app/views/polls/results_2017.html.erb, app/views/polls/results_2018.html.erb, app/views/spending_proposals/results.html.erb
Qué
====
Añade mejoras de accesibilidad y que arreglan la validación del HTML: 
- Evita `id` duplicados en la página de resultados de las votaciones.
- Elimina etiquetas `ogimage` duplicadas.
- Añade una etiqueta `</div>`que faltaba.
- Elimina un `<h2>` vacío.
- Arregla la _url_ a la búsqueda `#TúPreguntas` en debates. 
- Arregla la jerarquía de _headigns_.
=> Accesibilidad

app/views/custom/welcome/index.html.erb, app/views/polls/show.html.erb, spec/features/officing/letters_spec.rb, spec/features/polls/nvotes_spec.rb, spec/features/polls/polls_spec.rb, spec/features/social_media_meta_tags_spec.rb, spec/models/poll/poll_spec.rb, spec/support/common_actions.rb
What
====
Fixed tests broken in master.
Test
====
All tests should work now.
Deployment
==========
⚠️  When deploy to production fill `setting['meta_title']` and `setting['meta_description']` with generic content.
=> Tests fixes

CHANGELOG.md, app/assets/stylesheets/layout.scss, app/assets/stylesheets/participation.scss, app/models/budget/investment/milestone.rb, app/views/account/show.html.erb, app/views/admin/budget_investment_milestones/_form.html.erb, app/views/admin/budget_investments/_milestones.html.erb, app/views/admin/budget_investments/show.html.erb, app/views/admin/poll/polls/_form.html.erb, app/views/budgets/investments/_milestones.html.erb, app/views/images/_admin_image.html.erb, app/views/images/_image_fields.html.erb, app/views/relationable/_related_content.html.erb, app/views/welcome/_recommended_carousel.html.erb, config/locales/en/admin.yml, config/locales/en/general.yml, config/locales/en/images.yml, config/locales/es/admin.yml, config/locales/es/general.yml, config/locales/es/images.yml, spec/features/admin/budget_investment_milestones_spec.rb, spec/features/budgets/investments_spec.rb, spec/features/proposals_spec.rb, spec/models/budget/investment/milestone_spec.rb
Included PRs
=====
- Added check for related_contents https://github.com/consul/consul/pull/2196
- Make Milestones description required, hide title usage https://github.com/consul/consul/pull/2195
- Design https://github.com/consul/consul/pull/2198
Test
====
As usual.
=> Upstream => master

app/assets/stylesheets/custom.scss, app/views/budgets/investments/show.html.erb, app/views/proposals/show.html.erb
Qué
====
Añade algunos estilos _custom_ para destacar la navegación de comentarios, notificaciones y documentos en la vista _show_ de una **propuesta** y de un **proyecto de inversión**.
Imágenes
===========
=> Show views

app/assets/javascripts/map.js.coffee, app/controllers/budgets/investments_controller.rb, app/controllers/proposals_controller.rb, app/models/concerns/mappable.rb, app/views/map_locations/_form_fields.html.erb, config/locales/en/activerecord.yml, config/locales/en/general.yml, config/locales/es/activerecord.yml, config/locales/es/general.yml, db/migrate/20171219202827_recreated_column_related_contents_flags_count.rb, db/schema.rb, spec/factories.rb, spec/models/proposal_spec.rb, spec/shared/features/mappable.rb, spec/shared/models/map_validations.rb
Include PR
=====
Map Validations https://github.com/consul/consul/pull/2207
=> Map validations

app/views/custom/welcome/_recommended_carousel.html.erb
Qué
====
Activa el _auto play_ para la lista de recomendaciones de la página _welcome_.
=> Recommendations auto play

app/models/map_location.rb, spec/shared/models/map_validations.rb
Included commit
===
- Fix map location on update - 4689a42ad0a24df2dcb12ffd0bf23b6f7616e639
Test
====
- Manually test in staging environment
=> Fix map location on update

config/sitemap.rb
Qué
=====
- Añade al _sitemap_ la url de cada proyecto de presupuestos participativos creados por los usuarios: `/presupuestos/presupuestos-participativos-2017/proyecto/N`
=> Sitemap budgets investments

CHANGELOG.md, app/assets/stylesheets/participation.scss, app/views/admin/budget_investments/_investments.html.erb, app/views/admin/budgets/_group.html.erb, app/views/admin/budgets/_groups.html.erb, app/views/admin/budgets/_heading_form.html.erb, app/views/admin/budgets/edit.html.erb, app/views/admin/officials/index.html.erb, app/views/budgets/ballot/_progress_bar.html.erb, app/views/budgets/investments/_header.html.erb, app/views/budgets/investments/_investment.html.erb, app/views/budgets/investments/_investment_show.html.erb, config/locales/en/admin.yml, config/locales/en/budgets.yml, config/locales/en/general.yml, config/locales/es/admin.yml, config/locales/es/budgets.yml, config/locales/es/general.yml, spec/features/budgets/recommendation_spec.rb, spec/features/budgets/votes_spec.rb, spec/features/management/budget_investments_spec.rb
What
====
This PR improves UI with minor changes (translations, vertical align, font sizes and weights...) 
🙏  See https://github.com/consul/consul/issues/2216 with the list of all changes.
=> Budgets UI

CHANGELOG.md, app/assets/javascripts/map.js.coffee, app/assets/stylesheets/layout.scss, app/assets/stylesheets/participation.scss, app/helpers/map_locations_helper.rb, config/locales/en/activerecord.yml, config/locales/en/budgets.yml, config/locales/es/activerecord.yml, config/locales/es/budgets.yml, config/locales/es/general.yml, config/secrets.yml.example
https://github.com/consul/consul/pull/2327
=> Design UI improvements

app/assets/stylesheets/admin.scss, app/controllers/admin/budget_phases_controller.rb, app/models/budget/phase.rb, app/views/admin/budget_phases/_form.html.erb, app/views/admin/budget_phases/edit.html.erb, app/views/admin/budgets/_form.html.erb, app/views/admin/budgets/edit.html.erb, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/es/admin.yml, config/routes/admin.rb, spec/features/admin/budget_phases_spec.rb, spec/features/admin/budgets_spec.rb
Consul PR: https://github.com/consul/consul/pull/2353
=> Admin budget phases

app/assets/stylesheets/custom.scss, app/views/custom/budgets/index.html.erb
What
====
This PR hides temporally links on budgets homepage.
=> Budgets homepage with no links

app/views/custom/budgets/index.html.erb
What
====
- Use pretty urls for budget headings
Test
====
- Manually test in staging environment
Deployment
==========
- As usual
Warnings
========
- None
=> Use pretty urls for budget headings

app/views/budgets/index.html.erb, app/views/custom/budgets/index.html.erb
Just hiding temporarily links until show logic is specified
=> Hide investments links temporaliy

config/locales/es/activerecord.yml, config/locales/es/admin.yml, config/locales/es/budgets.yml, config/locales/es/community.yml, config/locales/es/general.yml, config/locales/es/mailers.yml, config/locales/es/management.yml, config/locales/es/responders.yml, config/locales/es/settings.yml, config/locales/es/valuation.yml
What
====
Fixes Spanish budgets texts using `Proyecto de gasto` instead of `Propuesta de inversión`
=> Fixes budgets text

app/views/comments/_form.html.erb
=> Add valuation flag to comment form cache key

Gemfile.lock
Included PR
=====
https://github.com/consul/consul/pull/2413
What
====
- Security update for Nokogiri gem
Deployment
==========
- As usual
Warnings
========
- None
=> Update nokogiri to version 1.8.2

app/controllers/admin/poll/questions/answers/images_controller.rb, config/locales/en/admin.yml, config/locales/en/responders.yml, config/locales/es/admin.yml, config/locales/es/responders.yml, config/locales/fr/responders.yml
Where
====
* Related PR: https://github.com/consul/consul/pull/2279
What
====
* Adds missing I18n translations
* Fix typos
=> Adds missing i18n keys

config/routes/custom.rb
What
====
Adds custom redirect to custom budget campaign
=> Adds custom redirect to custom budget campaign

app/views/welcome/_header.html.erb, config/locales/custom/en/custom.yml, config/locales/custom/es/custom.yml, spec/features/welcome_spec.rb
What
====
This PR changes welcome page header button depending budgets phase:
- Accepting: `Send your project`
- Reviewing: `See projects`
=> Changes welcome page header button depending budget phase

app/controllers/admin/newsletters_controller.rb, app/mailers/mailer.rb, spec/features/emails_spec.rb
Where
=====
* **Related PR's:** https://github.com/AyuntamientoMadrid/consul/pull/1274
What
====
Fixed ability to send the same newsletter to a group of users.
=> Changed how newsletters controller and mailer handle recipients

app/assets/stylesheets/custom.scss, app/assets/stylesheets/layout.scss, app/assets/stylesheets/participation.scss, app/views/budgets/investments/_filter_subnav.html.erb, app/views/budgets/investments/_investment_show.html.erb, app/views/budgets/investments/show.html.erb, app/views/documents/_document.html.erb, app/views/documents/_documents.html.erb, app/views/legislation/proposals/_filter_subnav.html.erb, app/views/legislation/proposals/show.html.erb, app/views/proposals/_filter_subnav.html.erb, app/views/proposals/show.html.erb, config/locales/en/documents.yml, config/locales/es/documents.yml, spec/shared/features/documentable.rb, spec/shared/features/nested_documentable.rb
What
====
This PR closes https://github.com/consul/consul/issues/2335
Notes
====
⚠️ **Once merged don't forget backport this commits to CONSUL repo.**
Screenshots
===========
=> Documents list

app/views/custom/pages/help/budgets/guide_2018.html.erb, config/routes/custom.rb
What
====
This PR adds a custom page with a guide about how to create an investment project.
=> Budgets guide page

app/models/document.rb
Reverts AyuntamientoMadrid/consul#1307
=> Revert "Fix incorrect URLs for attachments (documents)"

app/controllers/users/registrations_controller.rb, spec/features/account_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/consul/issues/1320
What
====
- Fix account page to be able to update your email address
=> Fix change email address

db/dev_seeds/settings.rb, spec/features/valuation/budget_investments_spec.rb
References
====
This is a refactor PR that precedes [the PR](https://github.com/AyuntamientoMadrid/consul/pull/1337) that tackles https://github.com/consul/consul/issues/2501
What
====
Just some boyscout cleanup of the feature spec file that next PR will modify it (https://github.com/AyuntamientoMadrid/consul/pull/1337)
=> Refactor valuator feature spec

app/views/budgets/investments/_votes.html.erb
Objectives
==========
Adds correct url on budget investment twitter share 😌
=> Fixes budget investment twitter share

spec/features/budgets/investments_spec.rb
References
==========
https://github.com/AyuntamientoMadrid/consul/issues/1191
https://github.com/AyuntamientoMadrid/consul/pull/1231
Objectives
==========
Update for the original PR, using the new rand function
None
Notes
None
=> Update for the PR 1231, fix for the flaky error 1191, not random investments list 

.travis.yml, Gemfile, Gemfile_custom, README_ES.md, app/assets/stylesheets/participation.scss, app/controllers/budgets/investments_controller.rb, spec/features/admin/budgets_spec.rb, spec/features/admin/users_spec.rb, spec/features/budgets/ballots_spec.rb, spec/features/budgets/votes_spec.rb, spec/features/comments/debates_spec.rb, spec/features/comments/legislation_annotations_spec.rb, spec/features/comments/legislation_questions_spec.rb, spec/features/management/budget_investments_spec.rb, spec/features/management/proposals_spec.rb, spec/features/moderation/proposals_spec.rb, spec/features/polls/voter_spec.rb, spec/lib/graphql_spec.rb, spec/lib/user_segments_spec.rb, spec/shared/features/nested_documentable.rb, spec/shared/features/nested_imageable.rb
Objectives
==========
Fix conflicts with upstream
Notes
None
=> Fix conflicts with upstream

app/assets/stylesheets/custom.scss, app/assets/stylesheets/participation.scss, app/controllers/admin/budget_investment_milestones_controller.rb, app/models/budget/investment/milestone.rb, app/views/admin/budget_investment_milestones/_form.html.erb, app/views/admin/budget_investments/_milestones.html.erb, app/views/budgets/investments/_milestones.html.erb, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/en/budgets.yml, config/locales/es/activerecord.yml, config/locales/es/admin.yml, config/locales/es/budgets.yml, db/migrate/20180321180149_add_status_to_milestones.rb, db/schema.rb, spec/factories.rb, spec/features/admin/budget_investment_milestones_spec.rb, spec/features/budgets/investments_spec.rb, spec/models/budget/investment/milestone_spec.rb
References
==========
Related issue https://github.com/consul/consul/issues/2432
Objectives
==========
Add project status value to budget investment's milestones.
Visual Changes
=> Investment milestone's project status

app/models/officing/residence.rb, app/models/verification/residence.rb, spec/controllers/admin/api/stats_controller_spec.rb, spec/factories.rb, spec/models/ahoy/data_source_spec.rb
References
==========
Pulling changes from Consul to get https://github.com/consul/consul/pull/2559 
Objectives
==========
Check referenced PR
None
Notes
None
=> Fix date parsing to take the TimeZone in account

app/controllers/admin/budget_investments_controller.rb, app/models/budget/investment.rb, app/models/budget/investment/exporter.rb, spec/features/admin/budget_investments_spec.rb
References
==========
We added the Invesment Export to CSV at https://github.com/consul/consul/pull/2147 leaving a lot of technical debt behind, the time has come to pay it.
Objectives
==========
Refactor this so additional changes can be applied to values & columns exported without investing so much time in understanding what's going on.
None
Notes
Some changes have an opinion attached, totally open to discussion 👍
=> Refactor Investment CSV Exporter

app/models/signature.rb, lib/census_api.rb, lib/document_parser.rb, lib/local_census.rb, spec/lib/census_api_spec.rb, spec/lib/local_census_spec.rb, spec/models/signature_spec.rb
Objectives
==========
- Increase pattern matching for user document numbers
None
Notes
None
=> Improve user pattern matching for document numbers

app/controllers/admin/signature_sheets_controller.rb, app/views/admin/signature_sheets/show.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/features/admin/signature_sheets_spec.rb
References
==========
None
Objectives
==========
Show the number of votes created from the verified signatures to the admin after creating a signatures sheet
Notes
None
=> Show votes associated to verified signatures

app/controllers/application_controller.rb, spec/features/budgets/budgets_spec.rb, spec/features/budgets/investments_spec.rb
Added filter in budgets `publishing_prices` phase for only selected investments.
=> Add condition to show only selected investments in publishing_prices phase

app/controllers/admin/newsletters_controller.rb, app/models/newsletter.rb, spec/models/newsletter_spec.rb
References
==========
- https://github.com/consul/consul/issues/2623
Objectives
==========
Send notifications in batches
Notes
We are using Madrid’s forks as reference which has 400.000 users and sending emails in batches of 10.000 users every 20 minutes
Tested in staging environment with beta testers
=> Notification batches

app/views/admin/activity/show.html.erb
References
==========
Related issue https://github.com/AyuntamientoMadrid/consul/issues/1480
=> Adds logic to handle activity actionable attributes

app/helpers/polls_helper.rb, app/views/custom/polls/_poll_group.html.erb, app/views/pages/conditions.html.erb, app/views/pages/privacy.html.erb
Objectives
This PR:
- Updates privacy text.
- Adds a link to the first voting path on old polls (without slug).
- Updates conditions page text.
=> Privacy text and results of old polls

app/assets/stylesheets/custom/_landings.scss, app/views/pages/landings/budgets_materials_2018.html.erb
Objectives
This PR adds new content to budgets materials 2018 page.
=> Budgets materials page

app/views/pages/landings/budgets_materials_2018.html.erb, app/views/pages/privacy.html.erb, spec/features/welcome_spec.rb
Objectives
This PR:
- Updates text for welcome spec.
- Adds new content to budgets 2018 materials page.
- Updates privacy page text.
=> Custom pages

app/controllers/admin/system_emails_controller.rb, lib/email_digest.rb, spec/features/notifications_spec.rb, spec/lib/email_digests_spec.rb
References
https://github.com/AyuntamientoMadrid/consul/pull/1497
Objectives
EmailDigest#valid_email? Should return a true/false value instead of
MatchData/nil/false
Visual Changes
None
Notes
None
=> Improve EmailDigest#valid_email? return values

app/views/custom/verification/letter/new.html.erb, config/locales/custom/en/verification.yml
Objectives
Adds custom message on verification if there is a current budget.
Visual Changes
**BEFORE**
**IF THERE IS A CURRENT BUDGET**
=> Verification message

app/controllers/admin/poll/polls_controller.rb, app/helpers/budgets_helper.rb, app/views/admin/budgets/index.html.erb, spec/features/budget_polls/budgets_spec.rb, spec/features/budget_polls/polls_spec.rb
References
**Issue:** https://github.com/consul/consul/issues/2639
**PR:** https://github.com/AyuntamientoMadrid/consul/pull/1507
Objectives
Create a poll for the budget if it does not exist
Visual Changes
Notes
If the poll already exists we are just displaying a link to the poll
=> Create budget polls

app/helpers/officers_helper.rb, app/views/officing/_menu.html.erb, app/views/officing/dashboard/index.html.erb, config/locales/en/officing.yml, config/locales/es/officing.yml, spec/features/budget_polls/officing_spec.rb, spec/features/officing/residence_spec.rb
Objectives
Hides sidebar menu if officer has no shifts assigned. Also show "You don't have officing shifts today" message.
Visual Changes
=> Officing sidebar menu

app/models/budget/ballot.rb, app/models/budget/ballot/line.rb, app/models/poll/ballot.rb, app/models/poll/ballot_sheet.rb, db/migrate/20180704093831_create_poll_ballot.rb, db/migrate/20180704095538_add_physical_to_budget_ballot.rb, db/schema.rb, spec/factories.rb, spec/models/poll/ballot_sheet_spec.rb, spec/models/poll/ballot_spec.rb
References
**Issue:** https://github.com/AyuntamientoMadrid/consul/issues/1527
Objectives
Verify `poll ballots` and create the corresponding `budget ballot lines`
Visual Changes
None
Pending
===
Comprehensive test coverage
=> Verify poll ballots

app/views/admin/budgets/_form.html.erb, spec/features/admin/budgets_spec.rb, spec/features/budgets/budgets_spec.rb
What
===
Use custom urls for results page
Visual Changes
None
Notes
Too early for a bakport, we don't have custom urls in CONSUL yet
Review when the time comes
=> Use custom urls for results page

app/assets/stylesheets/layout.scss, app/controllers/account_controller.rb, app/controllers/debates_controller.rb, app/controllers/proposals_controller.rb, app/models/debate.rb, app/models/proposal.rb, app/views/account/show.html.erb, app/views/custom/debates/index.html.erb, app/views/custom/proposals/index.html.erb, app/views/debates/index.html.erb, app/views/proposals/index.html.erb, app/views/shared/_recommended_index.html.erb, app/views/shared/_section_header.html.erb, config/locales/en/general.yml, config/locales/en/settings.yml, config/locales/es/general.yml, config/locales/es/settings.yml, db/dev_seeds/settings.rb, db/migrate/20180604124515_add_recommended_debates_setting_to_users.rb, db/migrate/20180604151014_add_recommended_proposals_setting_to_users.rb, db/schema.rb, db/seeds.rb, spec/features/account_spec.rb, spec/features/debates_spec.rb, spec/features/proposals_spec.rb
References
* Related issue: #2212
* Related PR: AyuntamientoMadrid#1389
Objectives
* This is a continuation of AyuntamientoMadrid#1389 with the "Pending requirements" stated in #2212 completed
Visual Changes
**NOTE**: For brevity, only the changes introduced by yours truly will be shown here. Feel free to check out the original PR for more images
* Settings shown to the user:
* Debates recommendations:
* Proposals recommendations:
Notes
* ~~[This spec](https://github.com/wairbut-m2c-aytomadrid/consul/blob/recommendations-index/spec/features/debates_spec.rb#L483) is failing (this spec was originally implemented on the original PR) —working on it as we speak to get it green~~
* Backport to CONSUL once approved & …
=> Debates and proposals recommendations for users

db/dev_seeds/newsletters.rb, lib/user_segments.rb
References
===
**PR: https://github.com/AyuntamientoMadrid/consul/pull/1579**
Objectives
Fix Travis Build
Notes
This PR should be backported alongside the referenced [PR](https://github.com/AyuntamientoMadrid/consul/pull/1579)
=> Fix Travis Build

app/views/custom/legislation/processes/index.html.erb, app/views/custom/mailer/budget_investment_created.html.erb, app/views/custom/mailer/budget_investment_selected.html.erb, app/views/custom/mailer/budget_investment_unfeasible.html.erb, app/views/custom/mailer/budget_investment_unselected.html.erb, app/views/custom/mailer/unfeasible_spending_proposal.html.erb, app/views/custom/management/budgets/investments/print.html.erb, app/views/custom/management/proposals/print.html.erb, app/views/custom/management/spending_proposals/print.html.erb, app/views/custom/proposals/_proposal.html.erb, app/views/custom/proposals/_votes.html.erb, app/views/pages/census_terms.html.erb, config/locales/custom/en/budgets.yml, config/locales/custom/en/general.yml, config/locales/custom/en/mailers.yml, config/locales/custom/en/management.yml, config/locales/custom/en/pages.yml, config/locales/custom/es/budgets.yml, config/locales/custom/es/general.yml, config/locales/custom/es/mailers.yml, config/locales/custom/es/management.yml, config/locales/custom/es/pages.yml, spec/features/management/users_spec.rb
References
Related PR: https://github.com/consul/consul/pull/2817
Objectives
The related PR on CONSUL repo https://github.com/consul/consul/pull/2817 cleans a lot of custom content. 
This PR move all these customized contents to the correct `custom` folder and `.yml` files to avoid losing content when syncing the repositories 😌
=> Custom content

app/assets/stylesheets/custom/_welcome.scss
Objectives
Changed color of the `<span>` tag on top of the welcome page main banner.
Visual Changes
Notes
This PR doesn't need backport to CONSUL, as it only modifies custom files.
=> Add pink color to welcome text span

app/controllers/management/base_controller.rb, app/models/user.rb, spec/models/user_spec.rb
References
Issue: https://github.com/consul/consul/issues/2812
Objectives
Fix flacky spec in management section where the 'My activity' link was not showing up
Visual Changes
None
Notes
Big up to @javierm for this one!
=> Fix admin menu not showing for high IDs

app/assets/javascripts/application.js
References
* N/A
Objectives
* Removes duplicated lines on `application.js` manifest file
Visual Changes
* N/A
Notes
* Patch is specific to this repo, no need to backport
=> Remove duplicated lines on application manifest

app/views/custom/legislation/_filmoteca.html.erb, app/views/custom/legislation/processes/index.html.erb
Objectives
Show custom filmotecas proccess on processes index.
Notes
Don't backport this PR.
=> Filmotecas

app/controllers/legislation/processes_controller.rb, app/views/legislation/proposals/_categories.html.erb, config/locales/en/legislation.yml, config/locales/es/legislation.yml, spec/factories.rb, spec/features/tags/custom/legislation/proposals_spec.rb
References
https://github.com/AyuntamientoMadrid/consul/pull/1635
Objectives
Filter proposals by tag for legislation proposals
=> Add legislation proposal's categories

config/locales/en/admin.yml, config/locales/en/legislation.yml, config/locales/es/admin.yml, config/locales/es/legislation.yml, spec/features/legislation/draft_versions_spec.rb
Objectives
Changes allegations dates label "Allegations" to "Comments".
Notes
=> Changes allegations dates label

.hound.yml
* Add a Hound configuration file so Hound uses our SCSS-Lint and Rubocop rules.
* Help us follow our own coding standards by automatically catching things we might forget like indentation issues.
* We need to activate [Hound](https://houndci.com) so it will automatically scan pull requests in this repository.
* Do **not** backport to CONSUL. We don't want to bother contributors until we've tested it properly.
=> Add Hound configuration

app/controllers/admin/widget/cards_controller.rb, app/models/widget/card.rb, app/views/admin/widget/cards/_form.html.erb, db/dev_seeds/widgets.rb, db/migrate/20180730120800_add_homepage_content_translations.rb, db/schema.rb, spec/features/admin/widgets/cards_spec.rb, spec/features/localization_spec.rb, spec/shared/features/translatable.rb
References
Origin PR https://github.com/AyuntamientoMadrid/consul/pull/1588
Objectives
- Solved conflicts.
=> Make homepage content translatable

lib/user_segments.rb, spec/lib/user_segments_spec.rb
Objectives
Removes old emails from beta testers segment.
Notes
I think would be nice move this `beta_testers` info to secret.yml.
=> Beta testers segment

app/views/pages/processes/filmotecas/index.html.erb
Adds winners movies to filmotecas custom page
=> Filmotecas winners

app/assets/stylesheets/custom/_guides.scss, app/assets/stylesheets/participation.scss
PR: https://github.com/consul/consul/pull/2823
Since we merged [Removes guide feature](https://github.com/consul/consul/pull/2823) on CONSUL and we keep maintaining this feature on Madrid I move `_guides.scss` to a custom file.
=> Guide feature

app/assets/stylesheets/admin.scss, app/assets/stylesheets/datepicker_overrides.scss, app/assets/stylesheets/layout.scss, app/assets/stylesheets/mixins.scss, app/views/admin/budgets/_max_headings_label.html.erb, app/views/budgets/investments/_view_mode.html.erb, app/views/debates/_view_mode.html.erb, app/views/proposals/_proposal.html.erb, app/views/proposals/_view_mode.html.erb
PR: https://github.com/consul/consul/pull/2983
Objectives
This PR fix some UI details:
- Updates `active` to `is-active` class for view mode.
- Fixes color of **datepicker calendar**.
- Removes unnecessary styles for admin budgets groups.
- Removes styles to fix logo size on devise views.
- Removes condition to allow images and data equalizer on proposals (the proposal image only can be present if feature `:allow_images` is enabled, so there is no need to include both conditions. The `data-equalizer` also is unnecessary because the `:thumb` image already has an fix height).
- Removes unnecessary style to orbit slide.
=> [Upstream] UI design

config/initializers/delayed_job_config.rb
**PR**: https://github.com/AyuntamientoMadrid/consul/pull/1682
- Speed up processing of jobs by reducing sleep time
- Avoid restarting newsletter job and sending duplicate emails, by reducing max attempts to 1
Nope
=> Reduce delayed job limits

app/models/poll/question.rb, spec/models/i18n_content_spec.rb, spec/models/poll/question_spec.rb
* Adds the last two commits in consul#2985
* The rest of the commits in that pull request came from #1669
* Fix a bug in poll question with non-underscored locales
* Make a spec compatible with the new languages added to CONSUL.
=> [Upstream] Fix poll question with non-underscored locales 

.rubocop.yml
* Reduce the amount of noise generated by Hound removing rules which are ignored by developers.
Yes.
=> Remove described class cop

db/migrate/20180323190027_add_translate_milestones.rb, db/schema.rb, lib/tasks/migrate_milestones_and_statuses.rake, spec/lib/tasks/milestones_spec.rb
* Issue consul#2763
* Pull request #1698
* Fix the existing migration so it doesn't use a model which no longer exists
* Migrate milestones images and documents
Yes; backport after backporting #1698.
=> Fix milestones migrations

app/helpers/legislation_helper.rb, app/views/admin/legislation/processes/_subnav.html.erb, config/locales/de-DE/admin.yml, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/es-AR/admin.yml, config/locales/es-CL/admin.yml, config/locales/es/activerecord.yml, config/locales/es/admin.yml, config/locales/fr/admin.yml, config/locales/gl/admin.yml, config/locales/it/admin.yml, config/locales/nl/admin.yml, config/locales/pl-PL/admin.yml, config/locales/pt-BR/admin.yml, config/locales/sq-AL/admin.yml, config/locales/sv-SE/admin.yml, config/locales/val/admin.yml, config/locales/zh-CN/admin.yml, config/locales/zh-TW/admin.yml
* Issue consul#2743
Simplify the code rendering the tabs in the legislation process subnav, so it's easier to add a new tab.
Yes.
=> Refactor legislation process subnav

app/controllers/admin/poll/officers_controller.rb, app/views/admin/poll/officers/edit.html.erb, app/views/admin/poll/officers/show.html.erb, config/routes/admin.rb
Removes unused admin poll officers views, routes and controller for `edit` and `show`.
=> Admin poll officers

config/locales/es/rails.yml
Objectives
Fix 500 error when verifying account due to missing date order translations
Visual Changes
None
Notes
Review for other languages
=> Fix exception when verifying account

app/models/poll/shift.rb
References
https://github.com/consul/consul/issues/3060
=> [Upstream] Fix failing spec: Poll::Shift officer_assignments creates and destroy corresponding officer_assignments

app/views/admin/homepage/show.html.erb
References
Issue https://github.com/consul/consul/issues/3024
Objectives
Improve visualization for small screens in `/admin/homepage`
Visual Changes
=> [Upstream] Improve visualization for small resolution

spec/features/custom/legislation/proposals_spec.rb, spec/features/legislation/proposals_spec.rb, spec/sessions_helper.rb
https://github.com/consul/consul/pull/3076
=> [Upstream] Fix flaky spec: Each user has a different and consistent random proposals order

spec/features/admin/budget_investments_spec.rb, spec/features/admin/poll/questions_spec.rb
PR https://github.com/consul/consul/pull/3065
PR https://github.com/consul/consul/pull/3064
=> [Upstream] Add missing specs

app/views/custom/welcome/index.html.erb, app/views/welcome/index.html.erb, spec/features/home_spec.rb
* Pull request consul#2899
* Pull request consul#3094
* Issue consul#2890
Hide the "featured" section if there's nothing to show in that section.
**Before:**
**After:**
=> [Upstream] Hide Featured section on Home Page if there are no cards 

db/migrate/20180323190027_add_translate_milestones.rb, db/schema.rb
* Pull request consul#3097
* Commit b15ffe9
* Avoid conflicts in the schema file if users had already run the migration before we modified it.
=> [Upstream] Fix budget investment milestone translations migration

app/helpers/stats_helper.rb, app/models/budget/stats.rb, app/models/concerns/statisticable.rb, app/models/poll/stats.rb, app/views/polls/stats.html.erb
* Pull request #1749
* Move gender and age stats methods so they can be reused in all places where we display stats.
Yes, but only when the whole stats section is finished.
=> Refactor gender and age stats methods

app/controllers/budgets/executions_controller.rb, app/controllers/custom/budgets/executions_controller.rb, app/helpers/budget_executions_helper.rb, app/models/budget/investment.rb
* Pull request #1543
* Pull request consul#2864
* Move the code belonging to Madrid to custom files
* Refactor methods in budget executions
Yes! While backporting, remove the spec testing the heading with "Toda la ciudad" is ordered first. And don't backport the custom file :wink:
=> Move "Toda la ciudad" code to custom files

db/dev_seeds/polls.rb, db/dev_seeds/users.rb, spec/features/tracks_spec.rb
* Pull request #1749
* Correctly create  booth voters and recounts when executing `rake:dev_seed`
* Correctly set genders for users
* We've assumed `total_amount` represents just the valid votes, just like it's done when calculating the stats
=> Fix poll dev seeds

config/schedule.rb, lib/tasks/votes.rake
The task to update the hot_score for votes has been optimized.
A cron job has been added to daily update the score.
Yes
=> Most active score daily update

.rubocop.yml, .rubocop_basic.yml
This rule help to keep an easier to read code 😌 
=> Enable line length rubocop rule

app/assets/javascripts/forms.js.coffee, app/assets/stylesheets/admin.scss, app/controllers/admin/budget_investment_progress_bars_controller.rb, app/controllers/admin/legislation/progress_bars_controller.rb, app/controllers/admin/progress_bars_controller.rb, app/controllers/admin/proposal_progress_bars_controller.rb, app/models/concerns/milestoneable.rb, app/models/progress_bar.rb, app/models/progress_bar/translation.rb, app/views/admin/legislation/progress_bars/index.html.erb, app/views/admin/milestones/_milestones.html.erb, app/views/admin/progress_bars/_form.html.erb, app/views/admin/progress_bars/_progress_bars.html.erb, app/views/admin/progress_bars/edit.html.erb, app/views/admin/progress_bars/index.html.erb, app/views/admin/progress_bars/new.html.erb, config/initializers/foundation_rails_helper.rb, config/initializers/routes_hierarchy.rb, config/locales/en/activerecord.yml, config/locales/en/admin.yml, config/locales/es/activerecord.yml, config/locales/es/admin.yml, config/routes/admin.rb, db/migrate/20190103132925_create_progress_bars.rb, db/schema.rb, spec/factories/budgets.rb, spec/factories/milestones.rb, spec/models/progress_bar_spec.rb, spec/shared/features/admin_milestoneable.rb, spec/shared/features/progressable.rb
Issue consul#3135
Add sections in the administration to handle progress bars for proposals, budget investments and legislation processes.
TODO
Yes.
=> Manage milestone progress bars

app/controllers/admin/budget_phases_controller.rb, app/controllers/admin/budgets_controller.rb, app/controllers/graphql_controller.rb
Remove all semicolons from controllers to be more consistent with the rest of the project 😃.
Yes
=> [Consistency] Remove semicolons from controllers

app/views/admin/stats/proposal_notifications.html.erb
https://github.com/consul/consul/pull/3154/files#diff-e422ad077e6ba8cf9546006f4a7c65e7R34
- Remove duplicated tags `<small>`
- To have the same code than in repo `consul` https://github.com/consul/consul/blob/e3eb87addb1389aaccd29ee359c3a2dcfbc7afde/app/views/admin/stats/proposal_notifications.html.erb#L34
No.
=> [Refactor] Delete duplicated tags <small> and be more consistent with consul repository

app/helpers/content_blocks_helper.rb
Commit https://github.com/consul/consul/pull/3150/commits/1ea18f0c89c137b8396cc44d30a9783ce32bfe48 from PR https://github.com/consul/consul/pull/3150
=> [Upstream] Refactor - correct place for block variable

config/locales/es/budgets.yml
Updates budgets confirm group es translation.
=> Update budgets confirm group es translation

app/controllers/admin/legislation/processes_controller.rb, app/controllers/legislation/processes_controller.rb, app/models/legislation/process.rb, spec/features/admin/legislation/processes_spec.rb, spec/features/legislation/processes_spec.rb
Sort Legislation Processes by descending start date
Yes
=> Sort Legislation Processes by descending start date

app/models/concerns/statisticable.rb, app/models/poll/stats.rb, spec/factories/polls.rb, spec/models/poll/stats_spec.rb
* Pull request #1753
* Add more specific tests for poll stats
* Make it easier to add more tests in the future
Yes, backport when backporting everything related to stats.
=> Add specs to poll stats

app/views/spending_proposals/_sidebar.html.erb, app/views/spending_proposals/select_district.html.erb, app/views/spending_proposals/stats.html.erb
Update links after removing a path that was missing and could cause to raise exceptions.
Yes
=> Redirect to Budgets landing page after deleting missing path

app/assets/javascripts/legislation_admin.js.coffee, app/assets/stylesheets/pages.scss, app/controllers/admin/legislation/processes_controller.rb, app/helpers/legislation_helper.rb, app/models/legislation/process.rb, app/views/admin/legislation/processes/_form.html.erb, app/views/legislation/processes/_header.html.erb, app/views/legislation/processes/_header_full.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, db/migrate/20181220163447_add_header_color_settings_to_legislation_processes.rb, db/schema.rb, spec/features/admin/legislation/processes_spec.rb, spec/helpers/legislation_helper_spec.rb, spec/models/legislation/process_spec.rb
**PR**: https://github.com/consul/consul/pull/3152
Add an image and banner color for a legislation process
No, this comes from upstream.
=> [Upstsream] Add image to legislation processes and banner colors

app/assets/stylesheets/layout.scss, app/controllers/admin/site_customization/cards_controller.rb, app/controllers/admin/widget/cards_controller.rb, app/controllers/pages_controller.rb, app/helpers/admin_helper.rb, app/models/site_customization/page.rb, app/models/widget/card.rb, app/views/admin/_menu.html.erb, app/views/admin/site_customization/cards/_card.html.erb, app/views/admin/site_customization/cards/_cards.html.erb, app/views/admin/site_customization/cards/index.html.erb, app/views/admin/site_customization/pages/index.html.erb, app/views/admin/widget/cards/_form.html.erb, app/views/pages/_card.html.erb, app/views/pages/_cards.html.erb, app/views/pages/custom_page.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, config/routes/admin.rb, db/migrate/20181218164126_add_site_customization_page_to_widget_cards.rb, db/schema.rb, spec/features/admin/widgets/cards_spec.rb, spec/features/site_customization/custom_pages_spec.rb, spec/models/widget/card_spec.rb
**PR**: https://github.com/consul/consul/pull/3149
Add cards to custom pages
No, this comes from upstream.
=> [Upstream] Add cards to custom pages

app/views/custom/polls/_footer.html.erb, app/views/polls/index.html.erb
A little mistake was made when extracting custom code from the file `app/views/polls/index.html.erb` in this PR https://github.com/AyuntamientoMadrid/consul/pull/1800
Extract shared code from the custom partial
No, with this change the code will match the code at CONSUL. 😉
=> Extract shared code from custom partial

spec/features/legislation/processes_spec.rb
https://github.com/AyuntamientoMadrid/consul/pull/1861/ and https://github.com/AyuntamientoMadrid/consul/pull/1862
After two mentioned PRs this one include a missing case spec. Added on https://github.com/consul/consul/pull/3280. 😌
=> [Upstream] Removes next/incoming filters

db/dev_seeds/settings.rb
Initialize settings for development environment.
Yes
=> Initialize settings in development environment

app/controllers/budgets/investments_controller.rb, spec/features/budgets/investments_spec.rb
* Pull request #1850
* Fix a bug causing the map to show only the investments being displayed on the current page
* Remove unused code
Yes.
=> Show all investments in the map

spec/features/budget_polls/voter_spec.rb, spec/features/polls/voter_spec.rb
* Pull request consul#3343
Keep the code in Madrid's fork as similar to CONSUL's code as possible.
No, the code is already in CONSUL.
=> [Upstream] Move side menu specs to poll voter

spec/factories/polls.rb, spec/features/admin/poll/polls_spec.rb, spec/models/poll/poll_spec.rb, spec/models/poll/stats_spec.rb, spec/models/poll/voter_spec.rb
* Make it easier to write tests using poll voters in booths
* Generate less records in the database during tests
Yes.
=> Simplify poll factories

db/dev_seeds.rb, db/dev_seeds/pages.rb
Include the recently added by default custom pages in dev_seeds
Sure! ☺️
=> Include default custom pages in developers seed

app/models/budget.rb, app/models/budget/stats.rb, app/models/concerns/statisticable.rb, app/models/concerns/stats_versionable.rb, app/models/poll.rb, app/models/poll/stats.rb, app/models/stats_version.rb, config/schedule.rb, db/migrate/20190408133956_create_stats_versions.rb, db/schema.rb, lib/tasks/stats.rake, spec/models/poll/stats_spec.rb, spec/models/stats_version_spec.rb
* Depends on #1950
* Make it easy to expire the stats cache
* Make it possible to expire the stats cache for a specific record
* Make it possible to expire stats cache without changing the source code
Yes, backport alongside everything related to stats.
=> Add tasks to generate stats cache

app/models/poll/question/answer.rb, app/views/polls/_stats_2018.html.erb
* Pull request #1951
Fix a bug due to old methods still using poll stats `generate` method the old way.
Yes, backport when backporting everything related to stats.
=> Fix legacy use of poll stats

app/controllers/pages_controller.rb, spec/controllers/pages_controller_spec.rb
* [Avoid InvalidCrossOriginRequest Exceptions when Having a Catch-all Route](https://die-antwort.eu/techblog/2018-08-avoid-invalid-cross-origin-request-with-catch-all-route/)
Fix an `ActionController::InvalidCrossOriginRequest` exception we were getting when requesting non-existent JavaScript files.
Yes.
=> Fix InvalidCrossOriginRequest response

app/models/widget/card.rb, spec/models/widget/card_spec.rb
* Pull request consul#3149
* Remove unused code
* Remove a test for that code which was failing sometimes
Yes.
=> Remove unused (and flaky) card code and its spec

app/controllers/admin/api/stats_controller.rb, app/controllers/admin/milestone_statuses_controller.rb, app/controllers/admin/site_customization/information_texts_controller.rb, app/controllers/admin/stats_controller.rb, app/controllers/concerns/has_orders.rb, app/controllers/officing/letters_controller.rb, app/controllers/polls/nvotes_controller.rb, app/controllers/polls/questions_controller.rb, app/controllers/polls_controller.rb, app/controllers/proposals_controller.rb, app/controllers/related_contents_controller.rb, app/controllers/stats_controller.rb
For consistency prefer to use double quotes.
No
=> Use double quotes in controllers

app/models/answer.rb, app/models/budget.rb, app/models/budget/investment.rb, app/models/budget/phase.rb, app/models/budget/stats.rb, app/models/custom/budget_poll.rb, app/models/custom/probe.rb, app/models/custom/volunteer_poll.rb, app/models/debate.rb, app/models/legislation/proposal.rb, app/models/officing/residence.rb, app/models/poll.rb, app/models/poll/final_recount.rb, app/models/poll/nvote.rb, app/models/poll/partial_result.rb, app/models/poll/question/answer.rb, app/models/poll/voter.rb, app/models/proposal.rb, app/models/redeemable_code.rb, app/models/signature.rb, app/models/user.rb, app/models/verification/residence.rb
For consistency prefer to use double quotes.
No
=> Use double quotes in models

app/controllers/proposals_controller.rb, spec/features/proposals_spec.rb
Include archived proposals in the list of selected proposals
Yes
=> Show archived proposals in selected proposals list

app/controllers/admin/poll/recounts_controller.rb, app/helpers/poll_recounts_helper.rb, app/models/poll/stats.rb, app/views/admin/poll/recounts/index.html.erb, config/locales/en/admin.yml, config/locales/en/officing.yml, config/locales/es/admin.yml, config/locales/es/officing.yml, spec/features/admin/poll/polls_spec.rb, spec/helpers/poll_recounts_helper_spec.rb
* Fix results shown in the admin section
* Clarify "total ballots" only include valid ballots
Yes.
=> Fix valid votes labels

app/views/custom/proposals/show.html.erb, app/views/proposals/_support_status.html.erb, app/views/proposals/show.html.erb
Upstream from https://github.com/consul/consul/pull/3515
Extract partial with mobile sticky content. 😌  
=> Extract partial with mobile sticky content

config/deploy.rb, lib/application_logger.rb, lib/tasks/budgets.rake, lib/tasks/consul.rake, lib/tasks/settings.rake, lib/tasks/stats.rake, lib/tasks/stats_and_results.rake
* Issue consul#2831
* Make it easier to upgrade CONSUL
* Make it easier to write release notes
Yes.
=> Add task to upgrade to a new release

Gemfile, Gemfile.lock, app/assets/javascripts/imageable.js.coffee, app/controllers/admin/settings_controller.rb, app/controllers/admin/system_emails_controller.rb, app/helpers/imageables_helper.rb, app/models/image.rb, app/models/setting.rb, app/models/site_customization/image.rb, app/views/admin/banners/_form.html.erb, app/views/custom/welcome/index.html.erb, app/views/images/_image.html.erb, app/views/images/_image_fields.html.erb, app/views/welcome/_card.html.erb, app/views/welcome/_feeds.html.erb, app/views/welcome/_header.html.erb, config/locales/custom/es/general.yml, config/locales/es/settings.yml, lib/tasks/settings.rake, spec/features/admin/system_emails_spec.rb
Related PR: #2109 
Fix system email preview for moderated content
=> Fix system email preview for moderated content
